openapi: 3.1.0
info:
  version: "1.0.0"
  title: "GrowthBook REST API"
servers:
  - url: "https://api.growthbook.io/api/v1"
    description: GrowthBook Cloud
  - url: "{domain}/api/v1"
    description: Self-hosted GrowthBook
    variables:
      domain:
        default: http://localhost:3100
paths:
  /features:
    $ref: "./paths/features/index.yml"
  /features/{id}:
    $ref: "./paths/features/id.yml"
  /features/{id}/toggle:
    $ref: "./paths/features/toggle.yml"
  /projects:
    $ref: "./paths/projects/index.yml"
  /projects/{id}:
    $ref: "./paths/projects/id.yml"
  /dimensions:
    $ref: "./paths/dimensions/index.yml"
  /dimensions/{id}:
    $ref: "./paths/dimensions/id.yml"
  /segments:
    $ref: "./paths/segments/index.yml"
  /segments/{id}:
    $ref: "./paths/segments/id.yml"
  /metrics:
    $ref: "./paths/metrics/index.yml"
  /metrics/{id}:
    $ref: "./paths/metrics/id.yml"
# PLOP_INSERT_PATHS_HERE
components:
  parameters:
    $ref: "./parameters/_index.yml"
  schemas:
    $ref: "./schemas/_index.yml"
  securitySchemas:
    bearerAuth:
      type: http
      scheme: bearer
    basicAuth:
      type: http
      scheme: basic
  responses:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
security:
  - bearerAuth: []
  - basicAuth: []
