id:
  name: id
  in: path
  required: true
  description: The id of the requested resource
  schema:
    type: string
limit:
  name: limit
  in: query
  description: The number of items to return
  schema:
    type: integer
    min: 1
    max: 100
    default: 10
offset:
  name: offset
  in: query
  description: How many items to skip (use in conjunction with limit for pagination)
  schema:
    type: integer
    min: 0
    default: 0
projectId:
  name: projectId
  in: query
  description: Filter by project id
  schema:
    type: string
datasourceId:
  name: datasourceId
  in: query
  description: Filter by Data Source
  schema:
    type: string
visualChangeId:
  name: visualChangeId
  in: path
  required: true
  description: Specify a specific visual change
  schema:
    type: string
factTableId:
  name: factTableId
  in: path
  required: true
  description: Specify a specific fact table
  schema:
    type: string
repo:
  name: repo
  in: query
  required: true
  description: Fully qualified name of repo either in GitHub or some other version control platform.
  schema:
    type: string
branch:
  name: branch
  in: query
  required: true
  description: Name of branch for git repo.
  schema:
    type: string
platform:
  name: platform
  in: query
  description: Name of version control platform like GitHub or Gitlab.
  schema:
    type: string
    enum:
      - github
      - gitlab
      - bitbucket
userName:
  name: userName
  in: query
  description: Name of the user.
  schema:
    type: string
userEmail:
  name: userEmail
  in: query
  description: Email address of the user.
  schema:
    type: string
globalRole:
  name: globalRole
  in: query
  description: Name of the global role
  schema:
    type: string
clientKey:
  name: clientKey
  in: query
  description: Filter by a SDK connection's client key
  schema:
    type: string
