/**
 * GrowthBook Features TypeScript Typings
 *
 * NOTE: This file is auto generated by the GrowthBook CLI (https://docs.growthbook.io/tools/cli).
 * See https://docs.growthbook.io/tools/cli#generating-types for more information.
 *
 * DO NOT EDIT this file manually.
 *
 * Exception: "pricing-phase-1-limits" is added ahead of the flag's creation in
 * GrowthBook's own account (Pricing Phase 1, P0). JSON flags are typed as
 * Record<string, unknown> here; the pricing config is schema-validated with
 * zod at the read site (back-end services/plan-limits.ts).
 */
export type AppFeatures = {
  "papercups-config": Record<string, unknown>;
  "show-experiment-groups": boolean;
  "show-experiment-targeting": boolean;
  "experiment-implementation": boolean;
  "feature-usage-code": boolean;
  "feature-list-realtime-graphs": boolean;
  chatwoot: Record<string, unknown>;
  "test-experiment": number;
  "webflow-ctas": boolean;
  "guided-onboarding-test-august-2022": boolean;
  "self-serve-billing": boolean;
  "self-serve-billing-overage-warning-banner": boolean;
  "mk-test-feature": boolean;
  "secret-api-keys": boolean;
  "stats-engine-setting": boolean;
  "proxy-cloud": boolean;
  "slack-integration": boolean;
  "new-experiment-modal": boolean;
  "visual-editor-ui": boolean;
  "proxy-cloud-sse": boolean;
  "organization-message-list": Record<string, unknown>;
  "remote-evaluation": boolean;
  "import-from-x": boolean;
  "demo-datasource": boolean;
  "new-experiment-rule": boolean;
  "visual-editor-ai-enabled": boolean;
  "team-permissions-enabled": boolean;
  "ff-approval-flow": boolean;
  "datasource-pipeline-mode": boolean;
  "fact-tables": boolean;
  "health-tab": boolean;
  "github-integration": boolean;
  "pylon-config": Record<string, unknown>;
  "no-access-role-type": boolean;
  "quantile-metrics": boolean;
  "new-message": boolean;
  "show-3.0-release": boolean;
  "improve-h1-heading-feature-flag": boolean;
  "apply-saved-group-id-list-size-limit": boolean;
  "use-new-setup-flow": boolean;
  bandits: boolean;
  "gb-ax5-bandit": boolean;
  "gb-ax10-bandit": boolean;
  "fact-metric-sql-preview": boolean;
  "inbuilt-data-warehouse": boolean;
  "datasource-first": boolean;
  "hide-optional-get-started-steps": boolean;
  "sdk-connections-new-empty-state": boolean;
  "kiosk-greeting": string;
  "feature-usage": boolean;
  "feature-usage-auto-refresh-interval": Record<string, unknown>;
  "experiment-decision-framework-status": boolean;
  "show-inbuilt-warehouse-onboarding-ui": boolean;
  ff1: boolean;
  ff_2: boolean;
  "use-new-setup-flow-2": boolean;
  "show-impact-near-top": boolean;
  ff_3_string: string;
  ff_4_json: Record<string, unknown>;
  ff_num: number;
  "cdn-usage-data": boolean;
  "pro-upgrade-modal": string;
  ff_2_extra: number;
  ff_5_prereq_exp: boolean;
  ff5_gated_by_prereq: boolean;
  "ff_payment-info": boolean;
  "ff_embedded-payment-form": boolean;
  "decision-framework-criteria": boolean;
  "holdout-test": string;
  "feature-test-for-holdout": string;
  "experiment-results-timeseries": boolean;
  "safe-rollout": boolean;
  "safe-rollout-promo": boolean;
  "ai-suggestions-for-experiment-analysis-input": boolean;
  "safe-rollout-auto-rollback": boolean;
  "safe-rollout-ramp-up": boolean;
  "new-exec-reports": boolean;
  "ideas-feature": boolean;
  "safe-rollout-timeseries": boolean;
  insights: boolean;
  "global-organization-holdout-2025-05-27": string;
  "sql-explorer": boolean;
  "pre-computed-dimensions": boolean;
  "ai-suggestions-temperature": number;
  asdf: boolean;
  "similar-experiments": boolean;
  "experiment-dashboards-enabled": boolean;
  holdouts_feature: boolean;
  "aa-test-holdout": boolean;
  "my-feature": boolean;
  "import-from-statsig": boolean;
  "metric-dimensions": boolean;
  "metric-slices": boolean;
  "new-sample-data": boolean;
  "october16-ff": boolean;
  "general-dashboards": boolean;
  "incremental-refresh": boolean;
  "top-banner": Record<string, unknown>;
  "gbdemo-checkout-layout": boolean;
  "post-stratification": boolean;
  liebenowflag9: boolean;
  "experimentation-focused-onboarding": boolean;
  teresatest: string;
  teresa_test_feature: boolean;
  "new-test-values": boolean;
  "test-feature": boolean;
  "pro-signup-flow": boolean;
  "kb-ff": boolean;
  "events-forwarder": boolean;
  "enable-error-tracking": boolean;
  "managed-warehouse-diagnostics": boolean;
  "managed-warehouse-json-ergonomics-sweep": boolean;
  "session-replays": boolean;
  "login-page-content": Record<string, unknown>;
  "slackbot-enabled": boolean;
  "slackbot-config": Record<string, unknown>;
  "oe-general-agent-gate": boolean;
  "event-forwarder-multi-step": string;
  "events-forwarder-multi-step": string;
  "ai-visual-editor-callout": boolean;
  "nps-survey": boolean;
  "home-marketing-banner": Record<string, unknown>;
  "visual-editor-free-access": boolean;
  "contextual-bandits": boolean;
  "show-switch-to-old-exp-create": boolean;
  "playstation-new-internal-dashboard": boolean;
  tester123: boolean;
  "pricing-phase-1-limits": Record<string, unknown>;
};
