import { AthenaConnectionParams } from "./integrations/athena";
import { BigQueryConnectionParams } from "./integrations/bigquery";
import { ClickHouseConnectionParams } from "./integrations/clickhouse";
import { GoogleAnalyticsParams } from "./integrations/googleanalytics";
import { MixpanelConnectionParams } from "./integrations/mixpanel";
import { MysqlConnectionParams } from "./integrations/mysql";
import { PostgresConnectionParams } from "./integrations/postgres";
import { PrestoConnectionParams } from "./integrations/presto";
import { SnowflakeConnectionParams } from "./integrations/snowflake";
import { DatabricksConnectionParams } from "./integrations/databricks";
import { MetricType } from "./metric";
import { MssqlConnectionParams } from "./integrations/mssql";
import { FactTableColumnType } from "./fact-table";
import type { PartitionSettings } from "./integrations";

export type DataSourceType =
  | "growthbook_clickhouse"
  | "redshift"
  | "athena"
  | "google_analytics"
  | "snowflake"
  | "postgres"
  | "mysql"
  | "mssql"
  | "bigquery"
  | "clickhouse"
  | "presto"
  | "databricks"
  | "mixpanel"
  | "vertica";

export type DataSourceParams =
  | PostgresConnectionParams
  | MysqlConnectionParams
  | MssqlConnectionParams
  | AthenaConnectionParams
  | PrestoConnectionParams
  | DatabricksConnectionParams
  | GoogleAnalyticsParams
  | SnowflakeConnectionParams
  | BigQueryConnectionParams
  | ClickHouseConnectionParams
  | MixpanelConnectionParams;

export type QueryLanguage = "sql" | "javascript" | "json" | "none";

export type SchemaFormat =
  | "segment"
  | "snowplow"
  | "jitsu"
  | "freshpaint"
  | "ga4"
  | "fullstory"
  | "matomo"
  | "heap"
  | "rudderstack"
  | "amplitude"
  | "mparticle"
  | "mixpanel"
  | "firebase"
  | "keen"
  | "clevertap"
  | "custom";

export type AutoFactTableSchemas = "segment" | "rudderstack" | "amplitude";

export type SchemaOption = {
  name: string;
  type: string;
  label: string;
  defaultValue: string | number;
  helpText?: string;
};

type GetExperimentSqlOptions = {
  exposureTableName?: string;
  actionName?: string;
  eventType?: string;
  projectId?: string;
  tablePrefix?: string;
  actionPrefix?: string;
  siteId?: string | number;
  categoryName?: string;
};

export interface SchemaInterface {
  getExperimentSQL(
    tablePrefix: string,
    userId: string,
    options?: GetExperimentSqlOptions,
  ): string;
  getIdentitySQL(
    tablePrefix: string,
    options?: Record<string, string | number>,
  ): IdentityJoinQuery[];
  experimentDimensions: string[];
  userIdTypes: string[];
  getMetricSQL(type: MetricType, tablePrefix: string): string;
}

export interface SchemaFormatConfig {
  userIdColumn: string;
  filterColumns: string[];
  anonymousIdColumn: string;
  trackedEventTableName: string;
  eventColumn: string;
  timestampColumn: string;
  getAdditionalEvents: () => {
    eventName: string;
    displayName: string;
    groupBy: string;
  }[];
  getTrackedEventTablePath: (options: {
    eventName: string;
    schema?: string;
  }) => string;
  getEventFilterWhereClause: (metricName?: string) => string;
  getDateLimitClause: (dates?: { start: Date; end: Date }) => string;
  displayNameColumn?: string;
}

export interface DataSourceProperties {
  queryLanguage: QueryLanguage;
  metricCaps?: boolean;
  segments?: boolean;
  experimentSegments?: boolean;
  exposureQueries?: boolean;
  dimensions?: boolean;
  hasSettings?: boolean;
  activationDimension?: boolean;
  events?: boolean;
  userIds?: boolean;
  pastExperiments?: boolean;
  separateExperimentResultQueries?: boolean;
  supportsInformationSchema?: boolean;
  supportsAutoGeneratedMetrics?: boolean;
  supportsWritingTables?: boolean;
  dropUnitsTable?: boolean;
  hasQuantileTesting?: boolean;
  hasEfficientPercentiles?: boolean;
  hasCountDistinctHLL?: boolean;
  hasIncrementalRefresh?: boolean;
  maxColumns: number;
}

type WithParams<B, P> = Omit<B, "params"> & {
  params: P;
  properties?: DataSourceProperties;
  decryptionError: boolean;
};

export type IdentityJoinQuery = {
  ids: string[];
  query: string;
};

export interface ExperimentDimensionMetadata {
  dimension: string;
  specifiedSlices: string[];
  customSlices?: boolean;
}

export interface ExposureQuery {
  id: string;
  name: string;
  description?: string;
  userIdType: string;
  query: string;
  hasNameCol?: boolean;
  dimensions: string[];
  dimensionSlicesId?: string;
  dimensionMetadata?: ExperimentDimensionMetadata[];
  error?: string;
}

export interface FeatureUsageQuery {
  id: string;
  query: string;
}

export interface UserIdType {
  userIdType: string;
  description?: string;
  attributes?: string[];
}

export type DataSourceEvents = {
  experimentEvent?: string;
  experimentIdProperty?: string;
  variationIdProperty?: string;
  extraUserIdProperty?: string;
};

export type DataSourcePipelineMode = "ephemeral" | "incremental";

export type DataSourcePipelineSettings = {
  /**
   * Controls if we run Pipeline Mode at all or not.
   */
  allowWriting: boolean;
  /**
   * If allowWriting is true, this controls how the pipeline is run.
   */
  mode: DataSourcePipelineMode;
  /**
   * The top level directory.
   * If undefined, we use the default.
   */
  writeDatabase?: string;
  /**
   * The mid level name (aka schema).
   */
  writeDataset: string;
  /**
   * The number of hours to keep the units table.
   * Note: For some datasources we use this to automatically expire tables.
   */
  unitsTableRetentionHours: number;
  /**
   * Only used for ephemeral mode.
   * Controls if we drop the units table when the analysis finishes.
   */
  unitsTableDeletion?: boolean;
  /**
   * If specified, we will use the configured pipeline mode only for these experiment IDs.
   * If not specified, we will use the configured pipeline mode for all experiments.
   */
  includedExperimentIds?: string[];
  /**
   * If specified, these experiment IDs will NOT use incremental refresh
   * even when mode is "incremental". They will fall back to standard queries.
   */
  excludedExperimentIds?: string[];
  /**
   * Optional partition pruning strategy used by incremental refresh.
   */
  partitionSettings?: PartitionSettings;
};

export type MaterializedColumnType = "" | "identifier" | "dimension";

export type MaterializedColumn = {
  columnName: string;
  sourceField: string;
  datatype: FactTableColumnType;
  type?: MaterializedColumnType;
};

export type DataSourceSettings = {
  // @deprecated
  experimentDimensions?: string[];
  notebookRunQuery?: string;
  informationSchemaId?: string;
  schemaFormat?: SchemaFormat;
  schemaOptions?: Record<string, string | number>;
  userIdTypes?: UserIdType[];
  queries?: {
    // @deprecated
    experimentsQuery?: string;
    exposure?: ExposureQuery[];
    identityJoins?: IdentityJoinQuery[];
    // @deprecated
    pageviewsQuery?: string;
    featureUsage?: FeatureUsageQuery[];
  };
  events?: DataSourceEvents;
  default?: {
    timestampColumn?: string;
    userIdColumn?: string;
    anonymousIdColumn?: string;
  };
  experiments?: {
    table?: string;
    timestampColumn?: string;
    userIdColumn?: string;
    anonymousIdColumn?: string;
    experimentIdColumn?: string;
    variationColumn?: string;
  };
  users?: {
    table?: string;
    userIdColumn?: string;
  };
  identifies?: {
    table?: string;
    anonymousIdColumn?: string;
    userIdColumn?: string;
  };
  pipelineSettings?: DataSourcePipelineSettings;
  maxConcurrentQueries?: string;
  queryCacheTTLMins?: string;
};

export interface GrowthbookClickhouseSettings extends DataSourceSettings {
  materializedColumns?: MaterializedColumn[];
}

interface DataSourceBase {
  id: string;
  name: string;
  description: string;
  organization: string;
  dateCreated: Date | null;
  dateUpdated: Date | null;
  params: string;
  projects?: string[];
  settings: DataSourceSettings;
  lockUntil?: Date | null;
  type: DataSourceType;
}

export interface GrowthbookClickhouseDataSource extends DataSourceBase {
  type: "growthbook_clickhouse";
  settings: GrowthbookClickhouseSettings;
}
interface RedshiftDataSource extends DataSourceBase {
  type: "redshift";
}

interface AthenaDataSource extends DataSourceBase {
  type: "athena";
}

interface PrestoDataSource extends DataSourceBase {
  type: "presto";
}

interface DatabricksDataSource extends DataSourceBase {
  type: "databricks";
}

interface GoogleAnalyticsDataSource extends DataSourceBase {
  type: "google_analytics";
}

interface SnowflakeDataSource extends DataSourceBase {
  type: "snowflake";
}

interface MysqlDataSource extends DataSourceBase {
  type: "mysql";
}

interface MssqlDataSource extends DataSourceBase {
  type: "mssql";
}

interface PostgresDataSource extends DataSourceBase {
  type: "postgres";
}

interface VerticaDataSource extends DataSourceBase {
  type: "vertica";
}

interface BigQueryDataSource extends DataSourceBase {
  type: "bigquery";
}

interface ClickHouseDataSource extends DataSourceBase {
  type: "clickhouse";
}

interface MixpanelDataSource extends DataSourceBase {
  type: "mixpanel";
}

export type GrowthbookClickhouseDataSourceWithParams = WithParams<
  GrowthbookClickhouseDataSource,
  ClickHouseConnectionParams
>;
export type RedshiftDataSourceWithParams = WithParams<
  RedshiftDataSource,
  PostgresConnectionParams
>;
export type AthenaDataSourceWithParams = WithParams<
  AthenaDataSource,
  AthenaConnectionParams
>;
export type PrestoDataSourceWithParams = WithParams<
  PrestoDataSource,
  PrestoConnectionParams
>;
export type DatabricksDataSourceWithParams = WithParams<
  DatabricksDataSource,
  DatabricksConnectionParams
>;
export type GoogleAnalyticsDataSourceWithParams = WithParams<
  GoogleAnalyticsDataSource,
  GoogleAnalyticsParams
>;
export type SnowflakeDataSourceWithParams = WithParams<
  SnowflakeDataSource,
  SnowflakeConnectionParams
>;
export type PostgresDataSourceWithParams = WithParams<
  PostgresDataSource,
  PostgresConnectionParams
>;

export type VerticaDataSourceWithParams = WithParams<
  VerticaDataSource,
  PostgresConnectionParams
>;
export type MysqlDataSourceWithParams = WithParams<
  MysqlDataSource,
  MysqlConnectionParams
>;
export type MssqlDataSourceWithParams = WithParams<
  MssqlDataSource,
  MssqlConnectionParams
>;
export type BigQueryDataSourceWithParams = WithParams<
  BigQueryDataSource,
  BigQueryConnectionParams
>;
export type ClickHouseDataSourceWithParams = WithParams<
  ClickHouseDataSource,
  ClickHouseConnectionParams
>;
export type MixpanelDataSourceWithParams = WithParams<
  MixpanelDataSource,
  MixpanelConnectionParams
>;

export type DataSourceInterface =
  | GrowthbookClickhouseDataSource
  | RedshiftDataSource
  | AthenaDataSource
  | PrestoDataSource
  | DatabricksDataSource
  | GoogleAnalyticsDataSource
  | SnowflakeDataSource
  | PostgresDataSource
  | VerticaDataSource
  | MysqlDataSource
  | MssqlDataSource
  | BigQueryDataSource
  | ClickHouseDataSource
  | MixpanelDataSource;

export type DataSourceInterfaceWithParams =
  | GrowthbookClickhouseDataSourceWithParams
  | RedshiftDataSourceWithParams
  | AthenaDataSourceWithParams
  | PrestoDataSourceWithParams
  | DatabricksDataSourceWithParams
  | GoogleAnalyticsDataSourceWithParams
  | SnowflakeDataSourceWithParams
  | PostgresDataSourceWithParams
  | VerticaDataSourceWithParams
  | MysqlDataSourceWithParams
  | MssqlDataSourceWithParams
  | BigQueryDataSourceWithParams
  | ClickHouseDataSourceWithParams
  | MixpanelDataSourceWithParams;
