import { AthenaConnectionParams } from "./integrations/athena";
import { BigQueryConnectionParams } from "./integrations/bigquery";
import { ClickHouseConnectionParams } from "./integrations/clickhouse";
import { GoogleAnalyticsParams } from "./integrations/googleanalytics";
import { MixpanelConnectionParams } from "./integrations/mixpanel";
import { MysqlConnectionParams } from "./integrations/mysql";
import { PostgresConnectionParams } from "./integrations/postgres";
import { PrestoConnectionParams } from "./integrations/presto";
import { SnowflakeConnectionParams } from "./integrations/snowflake";
import { DatabricksConnectionParams } from "./integrations/databricks";
import { MetricType } from "./metric";
import { MssqlConnectionParams } from "./integrations/mssql";
import { FactTableColumnType } from "./fact-table";
import { EventForwarderConfigWithMetadata } from "./event-forwarder";

export type DataSourceType =
  | "growthbook_clickhouse"
  | "redshift"
  | "athena"
  | "google_analytics"
  | "snowflake"
  | "postgres"
  | "mysql"
  | "mssql"
  | "bigquery"
  | "clickhouse"
  | "presto"
  | "databricks"
  | "mixpanel"
  | "vertica";

export type DataSourceParams =
  | PostgresConnectionParams
  | MysqlConnectionParams
  | MssqlConnectionParams
  | AthenaConnectionParams
  | PrestoConnectionParams
  | DatabricksConnectionParams
  | GoogleAnalyticsParams
  | SnowflakeConnectionParams
  | BigQueryConnectionParams
  | ClickHouseConnectionParams
  | MixpanelConnectionParams;

export type QueryLanguage = "sql" | "javascript" | "json" | "none";

export type SchemaFormat =
  | "segment"
  | "snowplow"
  | "jitsu"
  | "freshpaint"
  | "ga4"
  | "fullstory"
  | "matomo"
  | "heap"
  | "rudderstack"
  | "amplitude"
  | "mparticle"
  | "mixpanel"
  | "firebase"
  | "keen"
  | "clevertap"
  | "eventForwarder"
  | "custom";

export type AutoFactTableSchemas = "segment" | "rudderstack" | "amplitude";

export type SchemaOption = {
  name: string;
  type: string;
  label: string;
  defaultValue: string | number;
  helpText?: string;
};

type GetExperimentSqlOptions = {
  exposureTableName?: string;
  actionName?: string;
  eventType?: string;
  projectId?: string;
  tablePrefix?: string;
  actionPrefix?: string;
  siteId?: string | number;
  categoryName?: string;
};

export interface SchemaInterface {
  getExperimentSQL(
    tablePrefix: string,
    userId: string,
    options?: GetExperimentSqlOptions,
  ): string;
  getIdentitySQL(
    tablePrefix: string,
    options?: Record<string, string | number>,
  ): IdentityJoinQuery[];
  experimentDimensions: string[];
  userIdTypes: string[];
  getMetricSQL(type: MetricType, tablePrefix: string): string;
  getFactTableSQL(
    tablePrefix: string,
    userIdTypes: string[],
    options?: GetExperimentSqlOptions,
  ): string;
}

export interface SchemaFormatConfig {
  userIdColumn: string;
  filterColumns: string[];
  anonymousIdColumn: string;
  trackedEventTableName: string;
  eventColumn: string;
  timestampColumn: string;
  getAdditionalEvents: () => {
    eventName: string;
    displayName: string;
    groupBy: string;
  }[];
  getTrackedEventTablePath: (options: {
    eventName: string;
    schema?: string;
  }) => string;
  getEventFilterWhereClause: (metricName: string) => string;
  getDateLimitClause: (dates?: { start: Date; end: Date }) => string;
  displayNameColumn?: string;
}

export interface DataSourceProperties {
  queryLanguage: QueryLanguage;
  metricCaps?: boolean;
  segments?: boolean;
  experimentSegments?: boolean;
  exposureQueries?: boolean;
  dimensions?: boolean;
  hasSettings?: boolean;
  activationDimension?: boolean;
  events?: boolean;
  userIds?: boolean;
  pastExperiments?: boolean;
  separateExperimentResultQueries?: boolean;
  supportsInformationSchema?: boolean;
  supportsAutoGeneratedMetrics?: boolean;
  supportsWritingTables?: boolean;
  dropUnitsTable?: boolean;
  hasQuantileTesting?: boolean;
  hasEfficientPercentiles?: boolean;
  canGroupPercentileCappedMetrics?: boolean;
  hasCountDistinctHLL?: boolean;
  hasQuantileSketch?: boolean;
  hasIncrementalRefresh?: boolean;
  hasArrayQuantileGrid?: boolean;
  maxColumns: number;
}

type WithParams<B, P> = Omit<B, "params"> & {
  params: P;
  properties?: DataSourceProperties;
  decryptionError: boolean;
  eventForwarderConfig?: EventForwarderConfigWithMetadata | null;
};

export type IdentityJoinQuery = {
  ids: string[];
  query: string;
};

export interface ExperimentDimensionMetadata {
  dimension: string;
  specifiedSlices: string[];
  customSlices?: boolean;
}

export interface ExposureQuery {
  id: string;
  name: string;
  description?: string;
  userIdType: string;
  query: string;
  hasNameCol?: boolean;
  dimensions: string[];
  dimensionSlicesId?: string;
  dimensionMetadata?: ExperimentDimensionMetadata[];
  error?: string;
  /** Set to "api" for queries auto-created by Event Forwarder (not deletable in UI). */
  managedBy?: "" | "api";
}

export interface FeatureUsageQuery {
  id: string;
  query: string;
  description?: string;
  error?: string;
  /** Set to "api" for queries auto-created by Event Forwarder (not deletable in UI). */
  managedBy?: "" | "api";
}

export interface UserIdType {
  userIdType: string;
  description?: string;
  attributes?: string[];
}

export type DataSourceEvents = {
  experimentEvent?: string;
  experimentIdProperty?: string;
  variationIdProperty?: string;
  extraUserIdProperty?: string;
};

export type DataSourcePipelineMode = "ephemeral" | "incremental";

export type DataSourcePipelineSettings = {
  /**
   * Controls if we run Pipeline Mode at all or not.
   */
  allowWriting: boolean;
  /**
   * If allowWriting is true, this controls how the pipeline is run.
   */
  mode: DataSourcePipelineMode;
  /**
   * The top level directory.
   * If undefined, we use the default.
   */
  writeDatabase?: string;
  /**
   * The mid level name (aka schema).
   */
  writeDataset: string;
  /**
   * The number of hours to keep the units table.
   * Note: For some datasources we use this to automatically expire tables.
   */
  unitsTableRetentionHours: number;
  /**
   * Only used for ephemeral mode.
   * Controls if we drop the units table when the analysis finishes.
   */
  unitsTableDeletion?: boolean;
  /**
   * If specified, we will use the configured pipeline mode only for these experiment IDs.
   * If not specified, we will use the configured pipeline mode for all experiments.
   */
  includedExperimentIds?: string[];
  /**
   * If specified, these experiment IDs will NOT use incremental refresh
   * even when mode is "incremental". They will fall back to standard queries.
   */
  excludedExperimentIds?: string[];
  /**
   * Experiments explicitly opted into incremental refresh while the data
   * source's default `mode` is not `"incremental"` (typically `"ephemeral"`).
   * Ignored when `mode === "incremental"` — use `includedExperimentIds` /
   * `excludedExperimentIds` for per-experiment scoping in that mode.
   *
   * If incremental fails at run time, these experiments fall back to whatever
   * `mode` says. The incremental write configuration (writeDataset, etc.)
   * must still be valid; the UI enforces this by running the incremental
   * validation probes whenever this list is non-empty.
   */
  incrementalOptInExperimentIds?: string[];
};

export type MaterializedColumnType = "" | "identifier" | "dimension";

export type MaterializedColumn = {
  columnName: string;
  sourceField: string;
  datatype: FactTableColumnType;
  type?: MaterializedColumnType;
};

/**
 * A schema-declared attribute exposed as a typed ALIAS column literally named
 * `attributes.<property>` on the per-org managed-warehouse JSON tables, so
 * hand-written SQL can reference the path bare (typed, drift-safe) instead of
 * casting. `number` maps to Nullable(Float64) via toFloat64OrNull; everything
 * else to Nullable(String) (mirroring the dialect's jsonExtract semantics).
 */
export type TypedAttributeColumn = {
  property: string;
  datatype: "string" | "number";
};

export type DataSourceSettings = {
  // @deprecated
  experimentDimensions?: string[];
  notebookRunQuery?: string;
  informationSchemaId?: string;
  schemaFormat?: SchemaFormat;
  schemaOptions?: Record<string, string | number>;
  userIdTypes?: UserIdType[];
  queries?: {
    // @deprecated
    experimentsQuery?: string;
    exposure?: ExposureQuery[];
    identityJoins?: IdentityJoinQuery[];
    // @deprecated
    pageviewsQuery?: string;
    featureUsage?: FeatureUsageQuery[];
  };
  events?: DataSourceEvents;
  default?: {
    timestampColumn?: string;
    userIdColumn?: string;
    anonymousIdColumn?: string;
  };
  experiments?: {
    table?: string;
    timestampColumn?: string;
    userIdColumn?: string;
    anonymousIdColumn?: string;
    experimentIdColumn?: string;
    variationColumn?: string;
  };
  users?: {
    table?: string;
    userIdColumn?: string;
  };
  identifies?: {
    table?: string;
    anonymousIdColumn?: string;
    userIdColumn?: string;
  };
  pipelineSettings?: DataSourcePipelineSettings;
  maxConcurrentQueries?: string;
  queryCacheTTLMins?: string;
};

export interface GrowthbookClickhouseSettings extends DataSourceSettings {
  /** When false, the warehouse exists in GrowthBook but ClickHouse was not provisioned yet. */
  hasBeenProvisioned?: boolean;
  sessionReplayProvisioned?: boolean;
  /** @deprecated Replaced by native JSON columns (`useJsonColumns`); kept for legacy warehouses. */
  materializedColumns?: MaterializedColumn[];
  /**
   * When true, per-org tables store `attributes`/`properties` as native JSON columns
   * (vs String + materialized columns), with identifiers aliased in the fact-table SQL.
   */
  useJsonColumns?: boolean;
  /**
   * Transient: set while a provisioned warehouse's per-org tables are being recreated
   * for the JSON-columns migration. Queries are blocked and the UI shows an "upgrading"
   * state during this window. Distinct from `hasBeenProvisioned: false` (never set up).
   */
  migrating?: boolean;
  /**
   * Custom identifiers preserved from a legacy materialized-column warehouse during the
   * JSON migration that aren't current `hashAttribute`s. They're aliased out of the
   * `attributes` JSON column (like hashAttribute identifiers) so legacy `userIdType`s and
   * the joins keyed on them survive. Persisted so the attribute-change sync re-includes
   * them rather than regenerating identifiers from the schema alone.
   */
  migratedIdentifiers?: string[];
  /**
   * Non-identifier materialized columns (dimensions) preserved from a legacy warehouse
   * during the JSON migration. Like `migratedIdentifiers`, each is re-exposed as a
   * top-level SELECT alias out of the `attributes` JSON column (`attributes.<sourceField>
   * AS <columnName>`, cast to its declared datatype) so bare references to it — raw-SQL
   * fact filters, `sql_expr` row filters, exposure breakdowns, fact-table-routed metrics —
   * keep resolving without rewriting any stored SQL. Persisted so the attribute-change
   * sync re-emits the aliases. A live attribute also remains an `attributes.<field>` JSON
   * field; that duplicate listing is harmless — both resolve to the same data.
   */
  migratedColumns?: MaterializedColumn[];
  /**
   * Schema-declared attributes exposed as typed `attributes.<property>` ALIAS
   * columns on the per-org JSON tables (see TypedAttributeColumn). Derived from
   * the org attribute schema on every attribute-change sync and persisted here
   * so the license server (which applies the DDL at provision/recreate/sync
   * time) reads the desired state from this doc.
   */
  typedAttributeColumns?: TypedAttributeColumn[];
  /**
   * Version of the JSON-ergonomics setup (user settings + typed attribute
   * columns) last applied to this warehouse. The backfill sweep enqueues
   * provisioned JSON warehouses whose version is behind
   * MANAGED_WAREHOUSE_JSON_ERGONOMICS_VERSION; bump that constant to re-sweep.
   */
  jsonErgonomicsVersion?: number;
}

interface DataSourceBase {
  id: string;
  name: string;
  description: string;
  organization: string;
  dateCreated: Date | null;
  dateUpdated: Date | null;
  params: string;
  projects?: string[];
  settings: DataSourceSettings;
  type: DataSourceType;
}

export interface GrowthbookClickhouseDataSource extends DataSourceBase {
  type: "growthbook_clickhouse";
  settings: GrowthbookClickhouseSettings;
}
interface RedshiftDataSource extends DataSourceBase {
  type: "redshift";
}

interface AthenaDataSource extends DataSourceBase {
  type: "athena";
}

interface PrestoDataSource extends DataSourceBase {
  type: "presto";
}

interface DatabricksDataSource extends DataSourceBase {
  type: "databricks";
}

interface GoogleAnalyticsDataSource extends DataSourceBase {
  type: "google_analytics";
}

interface SnowflakeDataSource extends DataSourceBase {
  type: "snowflake";
}

interface MysqlDataSource extends DataSourceBase {
  type: "mysql";
}

interface MssqlDataSource extends DataSourceBase {
  type: "mssql";
}

interface PostgresDataSource extends DataSourceBase {
  type: "postgres";
}

interface VerticaDataSource extends DataSourceBase {
  type: "vertica";
}

interface BigQueryDataSource extends DataSourceBase {
  type: "bigquery";
}

interface ClickHouseDataSource extends DataSourceBase {
  type: "clickhouse";
}

interface MixpanelDataSource extends DataSourceBase {
  type: "mixpanel";
}

export type GrowthbookClickhouseDataSourceWithParams = WithParams<
  GrowthbookClickhouseDataSource,
  ClickHouseConnectionParams
>;
export type RedshiftDataSourceWithParams = WithParams<
  RedshiftDataSource,
  PostgresConnectionParams
>;
export type AthenaDataSourceWithParams = WithParams<
  AthenaDataSource,
  AthenaConnectionParams
>;
export type PrestoDataSourceWithParams = WithParams<
  PrestoDataSource,
  PrestoConnectionParams
>;
export type DatabricksDataSourceWithParams = WithParams<
  DatabricksDataSource,
  DatabricksConnectionParams
>;
export type GoogleAnalyticsDataSourceWithParams = WithParams<
  GoogleAnalyticsDataSource,
  GoogleAnalyticsParams
>;
export type SnowflakeDataSourceWithParams = WithParams<
  SnowflakeDataSource,
  SnowflakeConnectionParams
>;
export type PostgresDataSourceWithParams = WithParams<
  PostgresDataSource,
  PostgresConnectionParams
>;

export type VerticaDataSourceWithParams = WithParams<
  VerticaDataSource,
  PostgresConnectionParams
>;
export type MysqlDataSourceWithParams = WithParams<
  MysqlDataSource,
  MysqlConnectionParams
>;
export type MssqlDataSourceWithParams = WithParams<
  MssqlDataSource,
  MssqlConnectionParams
>;
export type BigQueryDataSourceWithParams = WithParams<
  BigQueryDataSource,
  BigQueryConnectionParams
>;
export type ClickHouseDataSourceWithParams = WithParams<
  ClickHouseDataSource,
  ClickHouseConnectionParams
>;
export type MixpanelDataSourceWithParams = WithParams<
  MixpanelDataSource,
  MixpanelConnectionParams
>;

export type DataSourceInterface =
  | GrowthbookClickhouseDataSource
  | RedshiftDataSource
  | AthenaDataSource
  | PrestoDataSource
  | DatabricksDataSource
  | GoogleAnalyticsDataSource
  | SnowflakeDataSource
  | PostgresDataSource
  | VerticaDataSource
  | MysqlDataSource
  | MssqlDataSource
  | BigQueryDataSource
  | ClickHouseDataSource
  | MixpanelDataSource;

export type DataSourceInterfaceWithParams =
  | GrowthbookClickhouseDataSourceWithParams
  | RedshiftDataSourceWithParams
  | AthenaDataSourceWithParams
  | PrestoDataSourceWithParams
  | DatabricksDataSourceWithParams
  | GoogleAnalyticsDataSourceWithParams
  | SnowflakeDataSourceWithParams
  | PostgresDataSourceWithParams
  | VerticaDataSourceWithParams
  | MysqlDataSourceWithParams
  | MssqlDataSourceWithParams
  | BigQueryDataSourceWithParams
  | ClickHouseDataSourceWithParams
  | MixpanelDataSourceWithParams;
