import cloneDeep from "lodash/cloneDeep";
import { getValidDate } from "shared/dates";
import { parseIntWithDefault } from "shared/util";
import { format as formatDate, subDays } from "date-fns";
import {
  ExperimentMetricInterface,
  getFactTableTemplateVariables,
  isRatioMetric,
  quantileMetricType,
} from "shared/experiments";
import {
  DEFAULT_TEST_QUERY_DAYS,
  DEFAULT_METRIC_HISTOGRAM_BINS,
} from "shared/constants";
import {
  generateProductAnalyticsSQL,
  calculateProductAnalyticsDateRange,
  PIPELINE_MODE_SUPPORTED_DATA_SOURCE_TYPES,
} from "shared/enterprise";
import {
  ensureLimit,
  format,
  isMultiStatementSQL,
  SQL_ROW_LIMIT,
} from "shared/sql";
import { TemplateVariables, SqlDialect } from "shared/types/sql";
import {
  MetricValueParams,
  ExperimentMetricQueryParams,
  PastExperimentParams,
  PastExperimentQueryResponse,
  ExperimentMetricQueryResponse,
  ExperimentMetricQueryResponseRows,
  MetricValueQueryResponse,
  MetricValueQueryResponseRow,
  ExperimentQueryResponses,
  Dimension,
  TestQueryResult,
  InformationSchema,
  RawInformationSchema,
  ExperimentUnitsQueryParams,
  QueryResponse,
  TrackedEventResponseRow,
  ExperimentUnitsQueryResponse,
  ExperimentAggregateUnitsQueryResponse,
  ExperimentAggregateUnitsQueryParams,
  ExperimentDimension,
  ExternalIdCallback,
  DimensionSlicesQueryResponse,
  DimensionSlicesQueryParams,
  ExperimentFactMetricsQueryParams,
  ExperimentFactMetricsQueryResponse,
  MetricAnalysisParams,
  MetricAnalysisQueryResponse,
  MetricAnalysisQueryResponseRow,
  TrackedEventData,
  AutoMetricTrackedEvent,
  AutoMetricToCreate,
  DropTableQueryResponse,
  DropTableQueryParams,
  TestQueryParams,
  ColumnTopValuesParams,
  ColumnTopValuesResponse,
  PopulationMetricQueryParams,
  PopulationFactMetricsQueryParams,
  VariationPeriodWeight,
  DataType,
  IncrementalWithNoOutputQueryResponse,
  CreateExperimentIncrementalUnitsQueryParams,
  UpdateExperimentIncrementalUnitsQueryParams,
  DropOldIncrementalUnitsQueryParams,
  AlterNewIncrementalUnitsQueryParams,
  FeatureEvalDiagnosticsQueryParams,
  MaxTimestampIncrementalUnitsQueryParams,
  MaxTimestampMetricSourceQueryParams,
  CreateMetricSourceTableQueryParams,
  InsertMetricSourceDataQueryParams,
  DimensionColumnData,
  DropMetricSourceCovariateTableQueryParams,
  MaxTimestampQueryResponse,
  ExperimentFactMetricsQueryResponseRows,
  IncrementalRefreshStatisticsQueryParams,
  FeatureEvalDiagnosticsQueryResponse,
  UserExperimentExposuresQueryParams,
  UserExperimentExposuresQueryResponse,
  CovariateWindowType,
  InsertMetricSourceCovariateDataQueryParams,
  CreateMetricSourceCovariateTableQueryParams,
  PipelineIntegration,
} from "shared/types/integrations";
import { MetricInterface, MetricType } from "shared/types/metric";
import {
  DataSourceProperties,
  ExposureQuery,
  SchemaFormatConfig,
  DataSourceInterface,
  AutoFactTableSchemas,
  SchemaFormat,
} from "shared/types/datasource";
import {
  ExperimentSnapshotSettings,
  SnapshotBanditSettings,
  SnapshotSettingsVariation,
} from "shared/types/experiment-snapshot";
import {
  FactMetricInterface,
  MetricQuantileSettings,
} from "shared/types/fact-table";
import { ExplorationConfig } from "shared/validators";
import {
  AdditionalQueryMetadata,
  QueryMetadata,
  QueryType,
} from "shared/types/query";
import { MissingDatasourceParamsError } from "back-end/src/util/errors";
import { ReqContext } from "back-end/types/request";
import { SourceIntegrationInterface } from "back-end/src/types/Integration";
import { compileSqlTemplate } from "back-end/src/util/sql";
import { formatInformationSchema } from "back-end/src/util/informationSchemas";
import { FactTableMap } from "back-end/src/models/FactTableModel";
import { logger } from "back-end/src/util/logger";
import { ReqContextClass } from "back-end/src/services/context";
import { addCaseWhenTimeFilter } from "back-end/src/integrations/sql/clauses/add-case-when-time-filter";
import { getAutoGeneratedMetricSqlQuery as getAutoGeneratedMetricSqlQueryFromSql } from "back-end/src/integrations/sql/queries/auto-generated-metric-sql-query";
import { getAggregationMetadata } from "back-end/src/integrations/sql/fact-metrics/aggregation-metadata";
import { getAlterNewIncrementalUnitsQuery } from "back-end/src/integrations/sql/queries/alter-new-incremental-units-query";
import { getBanditVariationPeriodWeights as getBanditVariationPeriodWeightsFromSql } from "back-end/src/integrations/sql/clauses/bandit-variation-period-weights";
import { getColumnsTopValuesQuery as getColumnsTopValuesQueryStandalone } from "back-end/src/integrations/sql/queries/columns-top-values-query";
import { castToTimestamp } from "back-end/src/integrations/sql/primitives/cast-to-timestamp";
import { getDimensionCTE } from "back-end/src/integrations/sql/ctes/dimension-cte";
import { getDimensionCol } from "back-end/src/integrations/sql/columns/dimension-col";
import { getDimensionInStatement } from "back-end/src/integrations/sql/fact-metrics/dimension-in-statement";
import { getDimensionSlicesQuery as getDimensionSlicesQueryFromSql } from "back-end/src/integrations/sql/queries/dimension-slices-query";
import { getDimensionValuePerUnit } from "back-end/src/integrations/sql/fact-metrics/dimension-value-per-unit";
import { getDropMetricSourceCovariateTableQuery } from "back-end/src/integrations/sql/queries/drop-metric-source-covariate-table-query";
import { getDropOldIncrementalUnitsQuery } from "back-end/src/integrations/sql/queries/drop-old-incremental-units-query";
import { getDropUnitsTableQuery } from "back-end/src/integrations/sql/queries/drop-units-table-query";
import { encodeMetricIdForColumnName } from "back-end/src/integrations/sql/fact-metrics/encode-metric-id-for-column-name";
import { getExperimentAggregateUnitsQuery as getExperimentAggregateUnitsQueryFromSql } from "back-end/src/integrations/sql/queries/experiment-aggregate-units-query";
import { getExperimentEndDate } from "back-end/src/integrations/sql/dates/experiment-end-date";
import { getExperimentFactMetricStatisticsCTE } from "back-end/src/integrations/sql/ctes/experiment-fact-metric-statistics-cte";
import { getExperimentFactMetricsQuery as getExperimentFactMetricsQueryFromSql } from "back-end/src/integrations/sql/queries/experiment-fact-metrics-query";
import { getExperimentMetricQuery as buildExperimentMetricQuerySql } from "back-end/src/integrations/sql/queries/experiment-metric-query";
import { getExperimentResultsQuery } from "back-end/src/integrations/sql/queries/experiment-results-query";
import { getExperimentUnitsQuery as buildExperimentUnitsQuerySql } from "back-end/src/integrations/sql/queries/experiment-units-query";
import { getExposureQuery } from "back-end/src/integrations/sql/queries/exposure-query";
import { getFactMetricCTE } from "back-end/src/integrations/sql/ctes/fact-metric-cte";
import { getFeatureEvalDiagnosticsQuery as getFeatureEvalDiagnosticsQueryFromSql } from "back-end/src/integrations/sql/queries/feature-eval-diagnostics-query";
import { getFilterColumnsClause } from "back-end/src/integrations/sql/clauses/filter-columns-clause";
import { getFreeFormQuery } from "back-end/src/integrations/sql/queries/free-form-query";
import { getIdentitiesCTE } from "back-end/src/integrations/sql/ctes/identities-cte";
import { getKllQuantileGridColumns as getKllQuantileGridColumnsFromSql } from "back-end/src/integrations/sql/columns/kll-quantile-grid-columns";
import { getMetricAnalysisQuery as buildMetricAnalysisQuerySql } from "back-end/src/integrations/sql/queries/metric-analysis-query";
import { getMetricSourceTableSchema } from "back-end/src/integrations/sql/fact-metrics/metric-source-table-schema";
import { getMetricValueQuery as buildMetricValueQuerySql } from "back-end/src/integrations/sql/queries/metric-value-query";
import { getPastExperimentQuery as buildPastExperimentQuerySql } from "back-end/src/integrations/sql/queries/past-experiment-query";
import { getPipelineValidationInsertQuery } from "back-end/src/integrations/sql/queries/pipeline-validation-insert-query";
import { getPowerPopulationCTEs } from "back-end/src/integrations/sql/ctes/power-population-ctes";
import { processActivationMetric } from "back-end/src/integrations/sql/processing/process-activation-metric";
import { processDimensions } from "back-end/src/integrations/sql/processing/process-dimensions";
import { parseExperimentFactMetricsParams } from "back-end/src/integrations/sql/fact-metrics/parse-experiment-fact-metrics-params";
import { processExperimentFactMetricsQueryRows as processExperimentFactMetricsQueryRowsFromSql } from "back-end/src/integrations/sql/processing/process-experiment-fact-metrics-query-rows";
import { getQuantileBoundsFromQueryResponse } from "back-end/src/integrations/sql/columns/quantile-bounds-from-query-response";
import { getSampleUnitsCTE } from "back-end/src/integrations/sql/ctes/sample-units-cte";
import { getSegmentCTE } from "back-end/src/integrations/sql/ctes/segment-cte";
import { toTimestampWithMs } from "back-end/src/integrations/sql/primitives/to-timestamp-with-ms";
import { getUserExperimentExposuresQuery as getUserExperimentExposuresQueryFromSql } from "back-end/src/integrations/sql/queries/user-experiment-exposures-query";
export { MAX_ROWS_UNIT_AGGREGATE_QUERY } from "back-end/src/services/experimentQueries/constants";
export { MAX_ROWS_PAST_EXPERIMENTS_QUERY } from "back-end/src/integrations/sql/queries/past-experiment-query";
export const TEST_QUERY_SQL = "SELECT 1";

const supportedEventTrackers: Record<AutoFactTableSchemas, true> = {
  segment: true,
  rudderstack: true,
  amplitude: true,
};

export default abstract class SqlIntegration
  implements SourceIntegrationInterface, PipelineIntegration
{
  datasource: DataSourceInterface;
  context: ReqContext;
  // Metadata set by the individual query runners
  additionalMetadata?: AdditionalQueryMetadata;
  decryptionError: boolean;
  // eslint-disable-next-line
  params: any;
  abstract setParams(encryptedParams: string): void;
  abstract runQuery(
    sql: string,
    setExternalId?: ExternalIdCallback,
    metadata?: QueryMetadata,
  ): Promise<QueryResponse>;
  async cancelQuery(externalId: string): Promise<void> {
    logger.debug(`Cancel query: ${externalId} - not implemented`);
  }
  abstract getSensitiveParamKeys(): string[];

  abstract getSqlDialect(): SqlDialect;

  constructor(context: ReqContextClass, datasource: DataSourceInterface) {
    this.wrapRunQuery();
    this.datasource = datasource;
    this.context = context;
    this.decryptionError = false;
    try {
      this.setParams(datasource.params);
    } catch (e) {
      this.params = {};
      this.decryptionError = true;
    }
  }

  private wrapRunQuery() {
    const originalRunQuery = this.runQuery;
    this.runQuery = async (
      sql: string,
      setExternalId?: ExternalIdCallback,
      metadata?: QueryMetadata,
    ) => {
      if (isMultiStatementSQL(sql)) {
        throw new Error("Multi-statement queries are not supported");
      }
      metadata = {
        ...metadata,
        userId: this.context.userId,
        userName: this.context.userName,
        ...this.additionalMetadata,
      };
      return originalRunQuery.call(this, sql, setExternalId, metadata);
    };
  }

  setAdditionalQueryMetadata(additionalQueryMetadata: AdditionalQueryMetadata) {
    this.additionalMetadata = additionalQueryMetadata;
  }

  getSourceProperties(): DataSourceProperties {
    return {
      queryLanguage: "sql",
      metricCaps: true,
      segments: true,
      dimensions: true,
      exposureQueries: true,
      separateExperimentResultQueries: true,
      hasSettings: true,
      userIds: true,
      experimentSegments: true,
      activationDimension: true,
      pastExperiments: true,
      supportsInformationSchema: true,
      supportsAutoGeneratedMetrics: this.isAutoGeneratingMetricsSupported(),
      supportsWritingTables: this.isWritingTablesSupported(),
      dropUnitsTable: this.dropUnitsTable(),
      hasQuantileTesting: this.hasQuantileTesting(),
      hasEfficientPercentiles: this.hasEfficientPercentile(),
      canGroupPercentileCappedMetrics: this.canGroupPercentileCappedMetrics(),
      hasCountDistinctHLL: this.getSqlDialect().hasCountDistinctHLL(),
      hasQuantileKLL: this.hasQuantileKLL(),
      hasIncrementalRefresh: this.canRunIncrementalRefreshQueries(),
      maxColumns: 1000,
    };
  }

  canRunIncrementalRefreshQueries(): boolean {
    return PIPELINE_MODE_SUPPORTED_DATA_SOURCE_TYPES["incremental"].includes(
      this.datasource.type,
    );
  }

  async testConnection(): Promise<boolean> {
    await this.runQuery(TEST_QUERY_SQL);
    return true;
  }

  isAutoGeneratingFactTablesSupported(): boolean {
    if (
      this.datasource.settings.schemaFormat &&
      supportedEventTrackers[
        this.datasource.settings.schemaFormat as AutoFactTableSchemas
      ]
    ) {
      return true;
    }
    return false;
  }

  // Currently, if auto generating fact tables is supported, so is generating auto metrics
  isAutoGeneratingMetricsSupported(): boolean {
    return this.isAutoGeneratingFactTablesSupported();
  }

  schemaFormatisAutoFactTablesSchemas(
    schemaFormat: SchemaFormat,
  ): schemaFormat is AutoFactTableSchemas {
    return (
      supportedEventTrackers[schemaFormat as AutoFactTableSchemas] || false
    );
  }

  isWritingTablesSupported(): boolean {
    return false;
  }

  dropUnitsTable(): boolean {
    return false;
  }

  requiresDatabase = true;
  requiresSchema = true;
  escapePathCharacter: string | null = null;

  ensureMaxLimit(sql: string, limit: number): string {
    return ensureLimit(sql, limit);
  }

  getCurrentTimestamp(): string {
    return this.getSqlDialect().getCurrentTimestamp();
  }

  hasQuantileTesting(): boolean {
    return true;
  }
  hasEfficientPercentile(): boolean {
    return true;
  }
  canGroupPercentileCappedMetrics(): boolean {
    return true;
  }
  hasQuantileKLL(): boolean {
    return false;
  }
  supportsLimitZeroColumnValidation(): boolean {
    return false;
  }
  getPastExperimentQuery(params: PastExperimentParams): string {
    // TODO: for past experiments, UNION all exposure queries together
    const experimentQueries = (
      this.datasource.settings.queries?.exposure || []
    ).map(({ id }) => getExposureQuery(this.datasource, id));

    return buildPastExperimentQuerySql(
      this.getSqlDialect(),
      experimentQueries,
      params.from,
      new Date(),
    );
  }
  async runPastExperimentQuery(
    query: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<PastExperimentQueryResponse> {
    const { rows, statistics } = await this.runQuery(
      query,
      setExternalId,
      queryMetadata,
    );

    return {
      rows: rows.map((row) => {
        return {
          exposure_query: row.exposure_query,
          experiment_id: row.experiment_id,
          experiment_name: row.experiment_name,
          variation_id: row.variation_id ?? "",
          variation_name: row.variation_name,
          users: parseIntWithDefault(row.users, 0),
          end_date: getValidDate(row.end_date).toISOString(),
          start_date: getValidDate(row.start_date).toISOString(),
          latest_data: getValidDate(row.latest_data).toISOString(),
        };
      }),
      statistics: statistics,
    };
  }

  getMetricValueQuery(params: MetricValueParams): string {
    return buildMetricValueQuerySql(
      this.getSqlDialect(),
      this.datasource,
      params,
    );
  }

  getMetricAnalysisQuery(
    metric: FactMetricInterface,
    params: Omit<MetricAnalysisParams, "metric">,
  ): string {
    return buildMetricAnalysisQuerySql(
      this.getSqlDialect(),
      this.datasource,
      metric,
      params,
    );
  }

  async runMetricAnalysisQuery(
    query: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<MetricAnalysisQueryResponse> {
    const { rows, statistics } = await this.runQuery(
      query,
      setExternalId,
      queryMetadata,
    );

    function parseUnitsBinData(
      // eslint-disable-next-line
      row: Record<string, any>,
    ): Partial<MetricAnalysisQueryResponseRow> {
      const data: Record<string, number> = {};

      for (let i = 0; i < DEFAULT_METRIC_HISTOGRAM_BINS; i++) {
        const key = `units_bin_${i}`;
        const parsed = parseFloat(row[key]);
        if (parsed) {
          data[key] = parsed;
        }
      }

      return data as Partial<MetricAnalysisQueryResponseRow>;
    }

    return {
      rows: rows.map((row) => {
        const {
          date,
          data_type,
          units,
          capped,
          main_sum,
          main_sum_squares,
          denominator_sum,
          denominator_sum_squares,
          main_denominator_sum_product,
          value_min,
          value_max,
        } = row;

        const ret: MetricAnalysisQueryResponseRow = {
          date: date ? getValidDate(date).toISOString() : "",
          data_type: data_type ?? "",
          capped: (capped ?? "uncapped") == "capped",
          units: parseFloat(units) || 0,
          main_sum: parseFloat(main_sum) || 0,
          main_sum_squares: parseFloat(main_sum_squares) || 0,
          denominator_sum: parseFloat(denominator_sum) || 0,
          denominator_sum_squares: parseFloat(denominator_sum_squares) || 0,
          main_denominator_sum_product:
            parseFloat(main_denominator_sum_product) || 0,

          value_min: parseFloat(value_min) || 0,
          value_max: parseFloat(value_max) || 0,
          ...(parseFloat(row.bin_width) && {
            bin_width: parseFloat(row.bin_width),
          }),
          ...parseUnitsBinData(row),
        };
        return ret;
      }),
      statistics: statistics,
    };
  }

  async runPopulationFactMetricsQuery(
    query: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<ExperimentFactMetricsQueryResponse> {
    return this.runExperimentFactMetricsQuery(
      query,
      setExternalId,
      queryMetadata,
    );
  }

  processExperimentFactMetricsQueryRows(
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    rows: Record<string, any>[],
  ): ExperimentFactMetricsQueryResponseRows {
    return processExperimentFactMetricsQueryRowsFromSql(rows);
  }

  async runExperimentFactMetricsQuery(
    query: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<ExperimentFactMetricsQueryResponse> {
    const { rows, statistics } = await this.runQuery(
      query,
      setExternalId,
      queryMetadata,
    );

    return {
      rows: this.processExperimentFactMetricsQueryRows(rows),
      statistics: statistics,
    };
  }

  async runPopulationMetricQuery(
    query: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<ExperimentMetricQueryResponse> {
    return this.runExperimentMetricQuery(query, setExternalId, queryMetadata);
  }

  async runExperimentMetricQuery(
    query: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<ExperimentMetricQueryResponse> {
    const { rows, statistics } = await this.runQuery(
      query,
      setExternalId,
      queryMetadata,
    );

    // Helper function to parse a single float field
    const parseFloatField = (
      row: Record<string, unknown>,
      field: string,
    ): Record<string, number> => {
      return row[field] !== undefined
        ? { [field]: parseFloat(row[field] as string) || 0 }
        : {};
    };

    // Helper function to parse non-float fields (cap values)
    const parseNonFloatField = (
      row: Record<string, unknown>,
      field: string,
    ): Record<string, unknown> => {
      return row[field] !== undefined ? { [field]: row[field] } : {};
    };

    return {
      rows: rows.map((row) => {
        const dimensionData: Record<string, string> = {};
        Object.entries(row)
          .filter(([key, _]) => key.startsWith("dim_") || key === "dimension")
          .forEach(([key, value]) => {
            dimensionData[key] = value;
          });

        // Build result object by processing all field types
        const result: ExperimentMetricQueryResponseRows[number] = {
          variation: row.variation ?? "",
          ...dimensionData,
          users: parseIntWithDefault(row.users, 0),
          count: parseIntWithDefault(row.users, 0),
          main_sum: parseFloat(row.main_sum as string) || 0,
          main_sum_squares: parseFloat(row.main_sum_squares as string) || 0,
        };

        // Quantile case
        if (row.quantile !== undefined) {
          result.quantile = parseFloat(row.quantile as string) || 0;
          Object.assign(result, getQuantileBoundsFromQueryResponse(row, ""));
        }

        Object.assign(
          result,
          // Ratio case
          parseFloatField(row, "denominator_sum"),
          parseFloatField(row, "denominator_sum_squares"),
          parseFloatField(row, "main_denominator_sum_product"),
          // CUPED case
          parseFloatField(row, "covariate_sum"),
          parseFloatField(row, "covariate_sum_squares"),
          parseFloatField(row, "main_covariate_sum_product"),
          // Ratio CUPED case
          parseFloatField(row, "denominator_pre_sum"),
          parseFloatField(row, "denominator_pre_sum_squares"),
          parseFloatField(row, "main_post_denominator_pre_sum_product"),
          parseFloatField(row, "main_pre_denominator_post_sum_product"),
          parseFloatField(row, "main_pre_denominator_pre_sum_product"),
          parseFloatField(row, "denominator_post_denominator_pre_sum_product"),
          // Capping case
          parseNonFloatField(row, "main_cap_value"),
          parseNonFloatField(row, "denominator_cap_value"),
          // Bandits case
          parseFloatField(row, "theta"),
          // Uncapped main case
          parseFloatField(row, "main_sum_uncapped"),
          parseFloatField(row, "main_sum_squares_uncapped"),
          // Uncapped ratio case
          parseFloatField(row, "denominator_sum_uncapped"),
          parseFloatField(row, "denominator_sum_squares_uncapped"),
          parseFloatField(row, "main_denominator_sum_product_uncapped"),
          // Uncapped CUPED case
          parseFloatField(row, "covariate_sum_uncapped"),
          parseFloatField(row, "covariate_sum_squares_uncapped"),
          parseFloatField(row, "main_covariate_sum_product_uncapped"),
          // Uncapped CUPED ratio case
          parseFloatField(row, "denominator_pre_sum_uncapped"),
          parseFloatField(row, "denominator_pre_sum_squares_uncapped"),
          parseFloatField(
            row,
            "main_post_denominator_pre_sum_product_uncapped",
          ),
          parseFloatField(
            row,
            "main_pre_denominator_post_sum_product_uncapped",
          ),
          parseFloatField(row, "main_pre_denominator_pre_sum_product_uncapped"),
          parseFloatField(
            row,
            "denominator_post_denominator_pre_sum_product_uncapped",
          ),
        );
        return result;
      }),
      statistics: statistics,
    };
  }

  async runExperimentAggregateUnitsQuery(
    query: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<ExperimentAggregateUnitsQueryResponse> {
    const { rows, statistics } = await this.runQuery(
      query,
      setExternalId,
      queryMetadata,
    );
    return {
      rows: rows.map((row) => {
        return {
          variation: row.variation ?? "",
          units: parseFloat(row.units) || 0,
          dimension_value: row.dimension_value ?? "",
          dimension_name: row.dimension_name ?? "",
        };
      }),
      statistics: statistics,
    };
  }

  async runExperimentUnitsQuery(
    query: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<ExperimentUnitsQueryResponse> {
    return await this.runQuery(query, setExternalId, queryMetadata);
  }

  async runMetricValueQuery(
    query: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<MetricValueQueryResponse> {
    const { rows, statistics } = await this.runQuery(
      query,
      setExternalId,
      queryMetadata,
    );

    return {
      rows: rows.map((row) => {
        const { date, count, main_sum, main_sum_squares } = row;

        const ret: MetricValueQueryResponseRow = {
          date: date ? getValidDate(date).toISOString() : "",
          count: parseFloat(count) || 0,
          main_sum: parseFloat(main_sum) || 0,
          main_sum_squares: parseFloat(main_sum_squares) || 0,
        };

        return ret;
      }),
      statistics: statistics,
    };
  }

  //Test the validity of a query as cheaply as possible
  getTestValidityQuery(
    query: string,
    testDays?: number,
    templateVariables?: TemplateVariables,
    timestampColumn?: string,
  ): string {
    // Use LIMIT 0 for datasources that support column metadata without data
    const limit = this.supportsLimitZeroColumnValidation() ? 0 : 1;
    return this.getTestQuery({
      query,
      templateVariables,
      testDays: testDays ?? DEFAULT_TEST_QUERY_DAYS,
      limit,
      timestampColumn,
    });
  }

  getFreeFormQuery(sql: string, limit?: number): string {
    return getFreeFormQuery(this.getSqlDialect(), sql, limit);
  }

  getTestQuery(params: TestQueryParams): string {
    const { query, templateVariables, timestampColumn } = params;
    const limit = params.limit ?? 5;
    const testDays = params.testDays ?? DEFAULT_TEST_QUERY_DAYS;
    const startDate = new Date();
    startDate.setDate(startDate.getDate() - testDays);

    const dialect = this.getSqlDialect();

    if (timestampColumn && !/^[\w.]+$/.test(timestampColumn)) {
      throw new Error(`Invalid timestamp column: ${timestampColumn}`);
    }
    const tableWhereClause = timestampColumn
      ? `WHERE ${timestampColumn} >= ${dialect.toTimestamp(startDate)}`
      : "";

    const limitedQuery = compileSqlTemplate(
      `WITH __table as (
        ${query}
      )
      ${dialect.selectStarLimit("__table", limit, tableWhereClause)}`,
      {
        startDate,
        templateVariables,
      },
      this.getSqlDialect(),
    );
    return format(limitedQuery, dialect.formatDialect);
  }

  async runTestQuery(
    sql: string,
    timestampCols?: string[],
    queryType?: QueryType,
  ): Promise<TestQueryResult> {
    const queryStartTime = Date.now();
    const results = await this.runQuery(
      sql,
      undefined,
      queryType ? { queryType } : undefined,
    ).catch((e) => {
      // If the user forgets to include a timestamp column in their SQL
      // The error message from the db will be confusing, so make it more clear.
      for (const col of timestampCols ?? []) {
        if (e.message.includes(col)) {
          throw new Error(`The column '${col}' is required. ${e.message}`);
        }
      }
      throw e;
    });
    const queryEndTime = Date.now();
    const duration = queryEndTime - queryStartTime;

    if (timestampCols) {
      results.rows.forEach((row) => {
        timestampCols.forEach((col) => {
          if (row[col]) {
            row[col] = getValidDate(row[col]);
          }
        });
      });
    }

    return { results: results.rows, columns: results.columns, duration };
  }

  getDropUnitsTableQuery(params: DropTableQueryParams): string {
    return getDropUnitsTableQuery(params);
  }

  async runDropTableQuery(
    sql: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<DropTableQueryResponse> {
    const results = await this.runQuery(sql, setExternalId, queryMetadata);
    return results;
  }

  createUnitsTableOptions() {
    return "";
  }

  createTablePartitions(_columns: string[]) {
    return "";
  }

  getExperimentUnitsTableQueryFromCte(
    unitsTableFullName: string,
    cteSql: string,
  ): string {
    return format(
      `
      CREATE OR REPLACE TABLE ${unitsTableFullName}
      ${this.createUnitsTableOptions()}
      AS (
        WITH
        ${cteSql}
        SELECT * FROM __experimentUnits
      );
    `,
      this.getSqlDialect().formatDialect,
    );
  }

  getExperimentUnitsTableQuery(params: ExperimentUnitsQueryParams): string {
    if (!params.unitsTableFullName) {
      throw new Error("Units table full name is required");
    }

    const cteSql = this.getExperimentUnitsQuery(params);

    return this.getExperimentUnitsTableQueryFromCte(
      params.unitsTableFullName,
      cteSql,
    );
  }

  getPopulationMetricQuery(params: PopulationMetricQueryParams): string {
    const { factTableMap, segment, populationSettings } = params;
    // dimension date?
    const populationSQL = getPowerPopulationCTEs(this.getSqlDialect(), {
      settings: populationSettings,
      factTableMap,
      segment,
    });

    return this.getExperimentMetricQuery({
      ...params,
      unitsSource: "otherQuery",
      unitsSql: populationSQL,
      forcedUserIdType: params.populationSettings.userIdType,
    });
  }

  getPopulationFactMetricsQuery(
    params: PopulationFactMetricsQueryParams,
  ): string {
    const { factTableMap, segment, populationSettings } = params;

    const populationSQL = getPowerPopulationCTEs(this.getSqlDialect(), {
      settings: populationSettings,
      factTableMap,
      segment,
    });
    return this.getExperimentFactMetricsQuery({
      ...params,
      unitsSource: "otherQuery",
      unitsSql: populationSQL,
      forcedUserIdType: params.populationSettings.userIdType,
    });
  }

  getExperimentUnitsQuery(params: ExperimentUnitsQueryParams): string {
    return buildExperimentUnitsQuerySql(
      this.getSqlDialect(),
      this.datasource,
      params,
    );
  }
  getBanditVariationPeriodWeights(
    banditSettings: SnapshotBanditSettings,
    variations: SnapshotSettingsVariation[],
  ): VariationPeriodWeight[] | undefined {
    return getBanditVariationPeriodWeightsFromSql(banditSettings, variations);
  }

  getExperimentAggregateUnitsQuery(
    params: ExperimentAggregateUnitsQueryParams,
  ): string {
    return getExperimentAggregateUnitsQueryFromSql(
      this.getSqlDialect(),
      this.datasource,
      params,
    );
  }

  getDimensionSlicesQuery(params: DimensionSlicesQueryParams): string {
    return getDimensionSlicesQueryFromSql(
      this.getSqlDialect(),
      this.datasource,
      params,
    );
  }

  async runDimensionSlicesQuery(
    query: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<DimensionSlicesQueryResponse> {
    const { rows, statistics } = await this.runQuery(
      query,
      setExternalId,
      queryMetadata,
    );
    return {
      rows: rows.map((row) => {
        return {
          dimension_value: row.dimension_value ?? "",
          dimension_name: row.dimension_name ?? "",
          units: parseIntWithDefault(row.units, 0),
          total_units: parseIntWithDefault(row.total_units, 0),
        };
      }),
      statistics: statistics,
    };
  }

  getUserExperimentExposuresQuery(
    params: UserExperimentExposuresQueryParams,
  ): string {
    return getUserExperimentExposuresQueryFromSql(
      this.getSqlDialect(),
      this.datasource,
      params,
    );
  }

  getFeatureEvalDiagnosticsQuery(
    params: FeatureEvalDiagnosticsQueryParams,
  ): string {
    return getFeatureEvalDiagnosticsQueryFromSql(
      this.getSqlDialect(),
      this.datasource,
      params,
    );
  }

  public async runUserExperimentExposuresQuery(
    query: string,
  ): Promise<UserExperimentExposuresQueryResponse> {
    const { rows, statistics } = await this.runQuery(query, undefined, {
      queryType: "userExposure",
    });

    // Check if SQL_ROW_LIMIT was reached
    const truncated = rows.length === SQL_ROW_LIMIT;

    return {
      rows: rows.map((row) => {
        return {
          timestamp: row.timestamp,
          experiment_id: row.experiment_id,
          variation_id: row.variation_id,
          ...row,
        };
      }),
      statistics,
      truncated,
    };
  }

  public async runFeatureEvalDiagnosticsQuery(
    query: string,
  ): Promise<FeatureEvalDiagnosticsQueryResponse> {
    const { rows, statistics } = await this.runQuery(query, undefined, {
      queryType: "featureEvalDiagnostics",
    });

    // Check if SQL_ROW_LIMIT was reached
    const truncated = rows.length === SQL_ROW_LIMIT;

    return {
      rows: rows.map((row) => {
        return {
          timestamp: row.timestamp,
          feature_key: row.feature_key,
          ...row,
        };
      }),
      statistics,
      truncated,
    };
  }

  getExperimentFactMetricsQuery(
    params: ExperimentFactMetricsQueryParams,
  ): string {
    return getExperimentFactMetricsQueryFromSql(
      this.getSqlDialect(),
      this.datasource,
      params,
    );
  }

  getExperimentMetricQuery(params: ExperimentMetricQueryParams): string {
    return buildExperimentMetricQuerySql(
      this.getSqlDialect(),
      this.datasource,
      params,
    );
  }

  getExperimentResultsQuery(): string {
    return getExperimentResultsQuery();
  }
  async getExperimentResults(): Promise<ExperimentQueryResponses> {
    throw new Error("Not implemented");
  }

  getDefaultDatabase() {
    return "";
  }

  generateTablePath(
    tableName: string,
    schema?: string,
    database?: string,
    queryRequiresSchema?: boolean,
  ) {
    let path = "";
    // Add database if required
    if (this.requiresDatabase) {
      database = database || this.getDefaultDatabase();
      if (!database) {
        throw new MissingDatasourceParamsError(
          "No database provided. Please edit the connection settings and try again.",
        );
      }
      path += database + ".";
    }

    // Add schema if required
    if (this.requiresSchema || queryRequiresSchema) {
      if (!schema) {
        throw new MissingDatasourceParamsError(
          "No schema provided. Please edit the connection settings and try again.",
        );
      }
      path += schema + ".";
    }

    // Add table name
    path += tableName;
    return this.escapePathCharacter
      ? `${this.escapePathCharacter}${path}${this.escapePathCharacter}`
      : path;
  }

  getInformationSchemaTable(schema?: string, database?: string): string {
    return this.generateTablePath(
      "information_schema.columns",
      schema,
      database,
    );
  }

  getInformationSchemaWhereClause(): string {
    return "table_schema NOT IN ('information_schema')";
  }
  async getInformationSchema(): Promise<InformationSchema[]> {
    const sql = `
  SELECT 
    table_name as table_name,
    table_catalog as table_catalog,
    table_schema as table_schema,
    count(column_name) as column_count 
  FROM
    ${this.getInformationSchemaTable()}
    WHERE ${this.getInformationSchemaWhereClause()}
    GROUP BY table_name, table_schema, table_catalog`;

    const results = await this.runQuery(
      format(sql, this.getSqlDialect().formatDialect),
    );

    if (!results.rows.length) {
      throw new Error(`No tables found.`);
    }

    return formatInformationSchema(results.rows as RawInformationSchema[]);
  }
  async getTableData(
    databaseName: string,
    tableSchema: string,
    tableName: string,
  ): Promise<{ tableData: null | unknown[] }> {
    const sql = `
  SELECT 
    data_type as data_type,
    column_name as column_name 
  FROM
    ${this.getInformationSchemaTable(tableSchema, databaseName)}
  WHERE 
    table_name = '${tableName}'
    AND table_schema = '${tableSchema}'
    AND table_catalog = '${databaseName}'`;

    const results = await this.runQuery(
      format(sql, this.getSqlDialect().formatDialect),
    );

    return { tableData: results.rows };
  }
  getSchemaFormatConfig(
    schemaFormat: AutoFactTableSchemas,
  ): SchemaFormatConfig {
    switch (schemaFormat) {
      case "amplitude": {
        return {
          trackedEventTableName: `EVENTS_${
            this.datasource.settings.schemaOptions?.projectId || `*`
          }`,
          eventColumn: "event_type",
          timestampColumn: "event_time",
          userIdColumn: "user_id",
          filterColumns: [
            "device_family as device",
            "os_name as os",
            "country",
            "paying",
          ],
          anonymousIdColumn: "amplitude_id",
          getTrackedEventTablePath: ({ schema }) =>
            this.generateTablePath(
              `EVENTS_${
                this.datasource.settings.schemaOptions?.projectId || `*`
              }`,
              schema,
            ),
          // If dates are provided, format them, otherwise use Sql template variables
          getDateLimitClause: (dates?: { start: Date; end: Date }) => {
            const start = dates
              ? `${formatDate(dates.start, "yyyy-MM-dd")}`
              : `{{date startDateISO "yyyy-MM-dd"}}`;
            const end = dates
              ? `${formatDate(dates.end, "yyyy-MM-dd")}`
              : `{{date endDateISO "yyyy-MM-dd"}}`;

            return `event_time BETWEEN '${start}' AND '${end}'`;
          },
          getAdditionalEvents: () => [],
          getEventFilterWhereClause: (eventName: string) =>
            `event_name = '${eventName}'`,
        };
      }
      case "rudderstack":
      case "segment":
        return {
          trackedEventTableName: "tracks",
          eventColumn: "event",
          timestampColumn: "received_at",
          userIdColumn: "user_id",
          filterColumns: [
            "(CASE WHEN context_user_agent LIKE '%Mobile%' THEN 'Mobile' ELSE 'Tablet/Desktop' END) as device",
            "(CASE WHEN context_user_agent LIKE '% Firefox%' THEN 'Firefox' WHEN context_user_agent LIKE '% OPR%' THEN 'Opera' WHEN context_user_agent LIKE '% Edg%' THEN ' Edge' WHEN context_user_agent LIKE '% Chrome%' THEN 'Chrome' WHEN context_user_agent LIKE '% Safari%' THEN 'Safari' ELSE 'Other' END) as browser",
          ],
          anonymousIdColumn: "anonymous_id",
          displayNameColumn: "event_text",
          getTrackedEventTablePath: ({ eventName, schema }) =>
            this.generateTablePath(eventName, schema),
          getDateLimitClause: (dates?: { start: Date; end: Date }) => {
            // If dates are provided, format them, otherwise use Sql template variables
            const start = dates
              ? `${formatDate(dates.start, "yyyy-MM-dd")}`
              : `{{date startDateISO "yyyy-MM-dd"}}`;
            const end = dates
              ? `${formatDate(dates.end, "yyyy-MM-dd")}`
              : `{{date endDateISO "yyyy-MM-dd"}}`;
            return `received_at BETWEEN '${start}' AND '${end}'`;
          },
          getAdditionalEvents: () => [
            {
              eventName: "pages",
              displayName: "Page Viewed",
              groupBy: "event",
            },
            {
              eventName: "screens",
              displayName: "Screen Viewed",
              groupBy: "event",
            },
          ],
          getEventFilterWhereClause: (_eventName: string) => "",
        };
    }
  }

  getAutoGeneratedMetricSqlQuery(
    eventName: string,
    hasUserId: boolean,
    schemaFormat: AutoFactTableSchemas,
    type: MetricType,
    schema?: string,
  ): string {
    return getAutoGeneratedMetricSqlQueryFromSql(
      this.getSqlDialect(),
      this.getSchemaFormatConfig(schemaFormat),
      eventName,
      hasUserId,
      type,
      schema,
    );
  }

  doesMetricExist(
    existingMetrics: MetricInterface[],
    sqlQuery: string,
    type: MetricType,
  ): boolean {
    return existingMetrics.some(
      (metric) => metric.sql === sqlQuery && metric.type === type,
    );
  }

  getAutoGeneratedFactTableSqlQuery(
    eventName: string,
    hasUserId: boolean,
    schemaFormat: AutoFactTableSchemas,
    schema?: string,
  ): string {
    const {
      timestampColumn,
      userIdColumn,
      anonymousIdColumn,
      getTrackedEventTablePath,
      getEventFilterWhereClause,
      filterColumns,
      getDateLimitClause,
    } = this.getSchemaFormatConfig(schemaFormat);

    const sqlQuery = `
      SELECT
        ${hasUserId ? `${userIdColumn} as user_id, ` : ""}
        ${anonymousIdColumn} as anonymous_id,
        ${timestampColumn} as timestamp
        ${getFilterColumnsClause(filterColumns)}
        FROM ${getTrackedEventTablePath({ eventName, schema })}
        WHERE ${getDateLimitClause()} ${
          getEventFilterWhereClause(eventName).length
            ? ` AND ${getEventFilterWhereClause(eventName)}`
            : ""
        }
`;
    return format(sqlQuery, this.getSqlDialect().formatDialect);
  }
  getMetricsToCreate(
    result: TrackedEventData,
    schemaFormat: AutoFactTableSchemas,
    existingMetrics: MetricInterface[],
    schema?: string,
  ): AutoMetricToCreate[] {
    const metricsToCreate: AutoMetricToCreate[] = [];

    const userIdTypes: string[] = ["anonymous_id"];

    if (result.hasUserId) {
      userIdTypes.push("user_id");
    }

    const binomialSqlQuery = this.getAutoGeneratedMetricSqlQuery(
      result.eventName,
      result.hasUserId,
      schemaFormat,
      "binomial",
      schema,
    );

    const binomialExists = this.doesMetricExist(
      existingMetrics,
      binomialSqlQuery,
      "binomial",
    );

    //TODO Build some logic where based on the event, we determine what metrics to create (by default, we create binomial and count) for every event
    metricsToCreate.push({
      name: result.displayName,
      type: "binomial",
      alreadyExists: binomialExists,
      shouldCreate: !binomialExists,
      sql: binomialSqlQuery,
      userIdTypes,
    });

    const countSqlQuery = this.getAutoGeneratedMetricSqlQuery(
      result.eventName,
      result.hasUserId,
      schemaFormat,
      "count",
      schema,
    );

    const countExists = this.doesMetricExist(
      existingMetrics,
      binomialSqlQuery,
      "binomial",
    );

    metricsToCreate.push({
      name: `Count of ${result.displayName}`,
      type: "count",
      alreadyExists: countExists,
      shouldCreate: !countExists,
      sql: countSqlQuery,
      userIdTypes,
    });

    return metricsToCreate;
  }

  private getTrackedEventSql(
    eventColumn: string,
    displayNameColumn: string,
    userIdColumn: string,
    timestampColumn: string,
    trackedEventTableName: string,
    getDateLimitClause: (dates?: { start: Date; end: Date }) => string,
    schema: string,
    groupByColumn?: string,
  ) {
    const end = new Date();
    const start = subDays(new Date(), 7);

    return `
      SELECT
        ${eventColumn} as event,
        MAX(${displayNameColumn}) as display_name,
        (CASE WHEN COUNT(${userIdColumn}) > 0 THEN 1 ELSE 0 END) as has_user_id,
        COUNT (*) as count,
        MAX(${timestampColumn}) as last_tracked_at
      FROM
        ${this.generateTablePath(
          trackedEventTableName,
          schema,
          undefined,
          !!schema,
        )}
      WHERE ${getDateLimitClause({ start, end })}
      AND ${eventColumn} NOT IN ('experiment_viewed', 'experiment_started')
      GROUP BY ${groupByColumn || eventColumn}
    `;
  }

  async getAutoMetricsToCreate(
    existingMetrics: MetricInterface[],
    schema: string,
  ): Promise<AutoMetricTrackedEvent[]> {
    const schemaFormat = this.datasource.settings.schemaFormat;

    if (
      schemaFormat &&
      this.schemaFormatisAutoFactTablesSchemas(schemaFormat)
    ) {
      const trackedEvents = await this.getEventsTrackedByDatasource(
        schemaFormat,
        schema,
      );

      if (!trackedEvents.length) {
        throw new Error(
          "No events found. The query we run to identify tracked events only looks at events from the last 7 days.",
        );
      }

      return trackedEvents.map((event) => {
        return {
          ...event,
          metricsToCreate: this.getMetricsToCreate(
            event,
            schemaFormat,
            existingMetrics,
            schema,
          ),
        };
      });
    } else {
      throw new Error(
        "Data Source does not support automatic metric generation.",
      );
    }
  }

  async getEventsTrackedByDatasource(
    // schemaFormat: SchemaFormat,
    schemaFormat: AutoFactTableSchemas,
    schema?: string,
  ): Promise<TrackedEventData[]> {
    const {
      trackedEventTableName,
      userIdColumn,
      eventColumn,
      timestampColumn,
      displayNameColumn,
      getAdditionalEvents,
      getDateLimitClause,
    } = this.getSchemaFormatConfig(schemaFormat);

    const sql = this.getTrackedEventSql(
      eventColumn,
      displayNameColumn || eventColumn,
      userIdColumn,
      timestampColumn,
      trackedEventTableName,
      getDateLimitClause,
      schema || "",
    );

    const { rows: resultRows } = await this.runQuery(
      format(sql, this.getSqlDialect().formatDialect),
    );

    const additionalEvents = getAdditionalEvents();

    for (const additionalEvent of additionalEvents) {
      const sql = this.getTrackedEventSql(
        `'${additionalEvent.eventName}'`,
        `'${additionalEvent.displayName}'`,
        userIdColumn,
        timestampColumn,
        additionalEvent.eventName,
        getDateLimitClause,
        schema || "",
        additionalEvent.groupBy,
      );

      try {
        const { rows: additionalEventResults } = await this.runQuery(
          format(sql, this.getSqlDialect().formatDialect),
        );

        additionalEventResults.forEach((result) => {
          if (result.count > 0) {
            resultRows.push(result);
          }
        });
      } catch (e) {
        // This happens when the table doesn't exists - this is optional, so just ignoring
      }
    }

    if (!resultRows) {
      throw new Error(`No events found.`);
    }

    return resultRows.map((result) => {
      const row = result as TrackedEventResponseRow;
      const processedEventData: TrackedEventData = {
        eventName: row.event,
        displayName: row.display_name,
        hasUserId: row.has_user_id,
        count: row.count,
        lastTrackedAt: result.last_tracked_at.value
          ? new Date(result.last_tracked_at.value)
          : new Date(result.last_tracked_at),
      };
      return processedEventData;
    });
  }

  /**
   * Like getQuantileGridColumns but extracts points from a merged KLL sketch
   * column instead of calling APPROX_PERCENTILE on raw values. Used by the
   * incremental-refresh path where the metric source table stores per-user-date
   * sketches that are merged at stats time.
   */
  getKllQuantileGridColumns(
    metricQuantileSettings: MetricQuantileSettings,
    sketchCol: string,
    prefix: string,
  ) {
    return getKllQuantileGridColumnsFromSql(
      this.getSqlDialect(),
      metricQuantileSettings,
      sketchCol,
      prefix,
    );
  }

  public getColumnsTopValuesQuery(params: ColumnTopValuesParams) {
    return getColumnsTopValuesQueryStandalone(this.getSqlDialect(), params);
  }

  public async runColumnsTopValuesQuery(
    sql: string,
  ): Promise<ColumnTopValuesResponse> {
    const { rows, statistics } = await this.runQuery(sql);

    return {
      statistics,
      rows: rows.map((r) => ({
        column: r.column_name + "",
        value: r.value + "",
        count: parseFloat(r.count),
      })),
    };
  }

  // Pipeline validation queries (engine-aware)
  getPipelineValidationInsertQuery({
    tableFullName,
  }: {
    tableFullName: string;
  }): string {
    return getPipelineValidationInsertQuery(this.getSqlDialect(), {
      tableFullName,
    });
  }

  // Finally, one per fact table for now:
  // getExperimentIncrementalStatisticsQuery
  parseExperimentParams(params: {
    settings: ExperimentSnapshotSettings;
    activationMetric: ExperimentMetricInterface | null;
    dimensions: Dimension[];
    unitsTableFullName: string;
  }): {
    exposureQuery: ExposureQuery;
    activationMetric: ExperimentMetricInterface | null;
    experimentDimensions: ExperimentDimension[];
    unitDimensions: Dimension[];
  } {
    const { settings, activationMetric: activationMetricDoc } = params;

    const exposureQuery = getExposureQuery(
      this.datasource,
      settings.exposureQueryId || "",
      undefined,
    );

    const activationMetric = processActivationMetric(
      activationMetricDoc,
      settings,
    );

    const { experimentDimensions } = processDimensions(
      this.getSqlDialect(),
      params.dimensions,
      settings,
      activationMetric,
    );

    return {
      activationMetric,
      experimentDimensions,
      exposureQuery,
      unitDimensions: params.dimensions,
    };
  }

  getCreateExperimentIncrementalUnitsQuery(
    params: CreateExperimentIncrementalUnitsQueryParams,
  ): string {
    const { exposureQuery, activationMetric, experimentDimensions } =
      this.parseExperimentParams(params);

    return format(
      `
    CREATE TABLE ${params.unitsTableFullName}
    (
      ${exposureQuery.userIdType} ${this.getSqlDialect().getDataType("string")}
      , variation ${this.getSqlDialect().getDataType("string")}
      , first_exposure_timestamp ${this.getSqlDialect().getDataType("timestamp")}
      ${
        activationMetric
          ? `, first_activation_timestamp ${this.getSqlDialect().getDataType("timestamp")}`
          : ""
      }
      ${experimentDimensions
        .map(
          (d) =>
            `, dim_exp_${d.id} ${this.getSqlDialect().getDataType("string")}`,
        )
        .join("\n")}
      , max_timestamp ${this.getSqlDialect().getDataType("timestamp")}
    )
    ${this.createTablePartitions(["max_timestamp"])}
    `,
      this.getSqlDialect().formatDialect,
    );
  }

  getUpdateExperimentIncrementalUnitsQuery(
    params: UpdateExperimentIncrementalUnitsQueryParams,
  ): string {
    const { settings, segment, factTableMap } = params;
    const { exposureQuery, activationMetric, experimentDimensions } =
      this.parseExperimentParams(params);

    const { baseIdType, idJoinMap, idJoinSQL } = getIdentitiesCTE(
      this.getSqlDialect(),
      this.datasource.settings,
      {
        objects: [
          [exposureQuery.userIdType],
          // activationMetric ? getUserIdTypes(activationMetric, factTableMap) : [],
          segment ? [segment.userIdType || "user_id"] : [],
        ],
        from: settings.startDate,
        to: settings.endDate,
        forcedBaseIdType: exposureQuery.userIdType,
        experimentId: settings.experimentId,
      },
    );

    // TODO(incremental-refresh): activation metric
    if (activationMetric) {
      throw new Error(
        "Activation metrics are not yet supported for incremental refresh",
      );
    }

    const lastMaxTimestampBinds =
      params.lastMaxTimestamp && params.lastMaxTimestamp > settings.startDate;

    // TODO(incremental-refresh): What if "skip partial data" is true?
    // Does the conversionWindowsHour need to be set different?
    const endDate = getExperimentEndDate(settings, 0);

    // Segment and SQL filter only check against new exposures
    return format(
      `
      CREATE TABLE ${params.unitsTempTableFullName} 
      ${this.createTablePartitions(["max_timestamp"])}
        AS (
        WITH ${idJoinSQL}
        __existingUnits AS (
          SELECT 
            ${baseIdType}
            , variation
            , first_exposure_timestamp AS timestamp
            , max_timestamp
            ${
              activationMetric
                ? `, first_activation_timestamp AS activation_timestamp`
                : ""
            }
            ${experimentDimensions.map((d) => `, dim_exp_${d.id}`).join("\n")}
          FROM ${params.unitsTableFullName}
        )
        ${
          segment
            ? `, __segment as (${getSegmentCTE(
                this.getSqlDialect(),
                segment,
                baseIdType,
                idJoinMap,
                factTableMap,
                {
                  startDate: settings.startDate,
                  endDate: settings.endDate,
                  experimentId: settings.experimentId,
                },
              )})`
            : ""
        }
        , __newExposures AS (
          ${compileSqlTemplate(
            exposureQuery.query,
            {
              startDate: settings.startDate,
              endDate: settings.endDate,
              experimentId: settings.experimentId,
              // TODO(incremental-refresh): add incremental start data as template variable
            },
            this.getSqlDialect(),
          )}
        )
        , __filteredNewExposures AS (
          SELECT 
            ${this.getSqlDialect().castToString(`${baseIdType}`)} AS ${baseIdType}
            , ${this.getSqlDialect().castToString(`variation_id`)} AS variation
            , timestamp AS timestamp
            ${activationMetric ? `, NULL AS activation_timestamp` : ""}
            ${experimentDimensions
              .map(
                (d) =>
                  `, ${this.getSqlDialect().castToString(d.id)} AS dim_exp_${d.id}`,
              )
              .join("\n")}
          FROM __newExposures
          WHERE 
            experiment_id = '${settings.experimentId}'
            ${
              lastMaxTimestampBinds && params.lastMaxTimestamp
                ? `AND timestamp > ${toTimestampWithMs(params.lastMaxTimestamp)}`
                : `AND timestamp >= ${toTimestampWithMs(settings.startDate)}`
            }
            ${endDate ? `AND timestamp <= ${toTimestampWithMs(endDate)}` : ""}
            
        )
        , __jointExposures AS (
          SELECT * FROM __existingUnits
          UNION ALL
          (
            SELECT
              ${baseIdType}
              , variation
              , timestamp
              , MAX(timestamp) OVER () AS max_timestamp
              ${activationMetric ? `, activation_timestamp` : ""}
              ${experimentDimensions.map((d) => `, dim_exp_${d.id}`).join("\n")}
            FROM __filteredNewExposures
          )
        )
        , __experimentUnits AS (
          SELECT
            e.${baseIdType} AS ${baseIdType}
            , ${this.getSqlDialect().ifElse(
              "COUNT(DISTINCT e.variation) > 1",
              "'__multiple__'",
              "MAX(e.variation)",
            )} AS variation
            , MIN(e.timestamp) AS first_exposure_timestamp
            , MIN(e.max_timestamp) AS max_timestamp
            ${experimentDimensions
              .map(
                (d) => `
              , ${getDimensionValuePerUnit(this.getSqlDialect(), d, "dim_exp_")} AS dim_exp_${d.id}`,
              )
              .join("\n")}
          FROM __jointExposures e
          GROUP BY
            ${baseIdType}
        )
        SELECT 
          ${baseIdType}
          , variation
          , first_exposure_timestamp
          ${activationMetric ? `, first_activation_timestamp` : ""}
          ${experimentDimensions.map((d) => `, dim_exp_${d.id}`).join("\n")}
          , max_timestamp
        FROM __experimentUnits
      )
      `,
      this.getSqlDialect().formatDialect,
    );
  }

  getDropOldIncrementalUnitsQuery(
    params: DropOldIncrementalUnitsQueryParams,
  ): string {
    return getDropOldIncrementalUnitsQuery(this.getSqlDialect(), params);
  }

  getAlterNewIncrementalUnitsQuery(
    params: AlterNewIncrementalUnitsQueryParams,
  ): string {
    return getAlterNewIncrementalUnitsQuery(this.getSqlDialect(), params);
  }

  getMaxTimestampIncrementalUnitsQuery(
    params: MaxTimestampIncrementalUnitsQueryParams,
  ): string {
    return format(
      `
      SELECT MAX(max_timestamp) AS max_timestamp FROM ${params.unitsTableFullName}
      `,
      this.getSqlDialect().formatDialect,
    );
  }

  async runMaxTimestampQuery(
    sql: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<MaxTimestampQueryResponse> {
    const { rows, statistics } = await this.runQuery(
      sql,
      setExternalId,
      queryMetadata,
    );

    const row = rows?.[0];

    if (!row) {
      return {
        rows: [],
        statistics,
      };
    }

    return {
      rows: [{ max_timestamp: row.max_timestamp }],
      statistics,
    };
  }

  async runIncrementalWithNoOutputQuery(
    sql: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<IncrementalWithNoOutputQueryResponse> {
    const results = await this.runQuery(sql, setExternalId, queryMetadata);
    return results;
  }

  getDataType(dataType: DataType): string {
    switch (dataType) {
      case "string":
        return "VARCHAR";
      case "integer":
        return "INTEGER";
      case "float":
        return "DOUBLE";
      case "boolean":
        return "BOOLEAN";
      case "date":
        return "DATE";
      case "timestamp":
        return "TIMESTAMP";
      case "hll":
        return "VARBINARY";
      case "kll":
        return "VARBINARY";
      default: {
        const _: never = dataType;
        throw new Error(`Unsupported data type: ${dataType}`);
      }
    }
  }

  getMaxTimestampMetricSourceQuery(
    params: MaxTimestampMetricSourceQueryParams,
  ): string {
    return format(
      `
      SELECT MAX(max_timestamp) AS max_timestamp FROM ${params.metricSourceTableFullName}
      `,
      this.getSqlDialect().formatDialect,
    );
  }

  getDropMetricSourceCovariateTableQuery(
    params: DropMetricSourceCovariateTableQueryParams,
  ): string {
    return getDropMetricSourceCovariateTableQuery(this.getSqlDialect(), params);
  }

  getCreateMetricSourceCovariateTableQuery(
    params: CreateMetricSourceCovariateTableQueryParams,
  ): string {
    const exposureQuery = getExposureQuery(
      this.datasource,
      params.settings.exposureQueryId || "",
      undefined,
    );

    const baseIdType = exposureQuery.userIdType;
    const sortedMetrics = params.metrics.sort((a, b) =>
      a.id.localeCompare(b.id),
    );

    const columnDefinitions =
      this.getMetricSourceCovariateTableColumnDefinitions(
        baseIdType,
        sortedMetrics,
      );

    return format(
      `
    CREATE TABLE ${params.metricSourceCovariateTableFullName}
    (
      ${columnDefinitions.join("\n, ")}
    )
    `,
      this.getSqlDialect().formatDialect,
    );
  }

  getInsertMetricSourceCovariateDataQuery(
    params: InsertMetricSourceCovariateDataQueryParams,
  ): string {
    const exposureQuery = getExposureQuery(
      this.datasource,
      params.settings.exposureQueryId || "",
      undefined,
    );

    // sort metrics and add indices for tracking across sub-queries
    const sortedMetrics = cloneDeep(params.metrics)
      .map((m) => ({
        ...m,
        // turn off capping for covariate value creation as capping will be applied
        // in the statistics query
        cappingSettings: { type: "" as const, value: 0 },
      }))
      .sort((a, b) => a.id.localeCompare(b.id));
    const paramsMetricsSorted: {
      metrics: FactMetricInterface[];
      activationMetric: ExperimentMetricInterface | null;
      settings: ExperimentSnapshotSettings;
      factTableMap: FactTableMap;
      covariateWindowType: CovariateWindowType;
      covariateTableAlias: string;
      forcedUserIdType?: string;
      lastMaxTimestamp: Date | null;
    } = {
      ...params,
      metrics: sortedMetrics,
      covariateWindowType: "phaseStart",
      covariateTableAlias: "c",
      lastMaxTimestamp: null,
    };

    // TODO(incremental-refresh): use max hours to convert from here
    // for eventual "skipPartialData" feature
    const { factTablesWithMetricData } = parseExperimentFactMetricsParams(
      this.getSqlDialect(),
      paramsMetricsSorted,
    );

    if (factTablesWithMetricData.length !== 1) {
      throw new Error("Expected exactly one fact table with metric data");
    }
    const factTableWithMetricData = factTablesWithMetricData[0];
    const metricData = factTableWithMetricData.metricData;

    const { baseIdType, idJoinMap, idJoinSQL } = getIdentitiesCTE(
      this.getSqlDialect(),
      this.datasource.settings,
      {
        objects: [
          [exposureQuery.userIdType],
          factTableWithMetricData.factTable?.userIdTypes || [],
        ],
        // TODO(incremental-refresh): this gets all identities from history
        // of experiment, which we think is right, but could be improved
        from: params.settings.startDate,
        to: params.settings.endDate,
        forcedBaseIdType: exposureQuery.userIdType,
        experimentId: params.settings.experimentId,
      },
    );

    const columnNames = this.getMetricSourceCovariateTableColumns(
      baseIdType,
      sortedMetrics,
    );

    return format(
      `
    INSERT INTO ${params.metricSourceCovariateTableFullName}
    (${columnNames.join(", \n")})
    SELECT * FROM (
      WITH 
        ${idJoinSQL}
        __factTable AS (${getFactMetricCTE(this.getSqlDialect(), {
          baseIdType,
          idJoinMap,
          factTable: factTableWithMetricData.factTable,
          startDate: factTableWithMetricData.minCovariateStartDate,
          endDate: factTableWithMetricData.maxCovariateEndDate,
          metricsWithIndices: metricData.map((m, i) => ({
            metric: m.metric,
            index: i,
          })),
          addFiltersToWhere: true,
          // Need to do < the end date to exclude the end date itself
          exclusiveEndDateFilter: true,
          castIdToString: true,
        })})
          , __newCovariateValues AS (
          SELECT
            m.${baseIdType} AS ${baseIdType}
            ${metricData
              .map((m) => {
                const raSettings = m.raMetricPhaseStartSettings;
                // Use full aggregation function since we are
                // aggregating only once to the user level for CUPED data
                const aggfunction =
                  m.covariateNumeratorAggFns.fullAggregationFunction;
                const denomAggFunction =
                  m.covariateDenominatorAggFns.fullAggregationFunction;
                return `
                ${
                  m.numeratorSourceIndex === factTableWithMetricData.index
                    ? `, ${aggfunction(
                        this.getSqlDialect().ifElse(
                          `m.timestamp >= ${toTimestampWithMs(raSettings.covariateStartDate)} 
                            AND m.timestamp < ${toTimestampWithMs(raSettings.covariateEndDate)}`,
                          `${m.alias}_value`,
                          "NULL",
                        ),
                      )} AS ${m.alias}_covariate_value`
                    : ""
                }
                ${
                  !!denomAggFunction &&
                  isRatioMetric(m.metric) &&
                  m.denominatorSourceIndex === factTableWithMetricData.index
                    ? `, ${denomAggFunction(
                        this.getSqlDialect().ifElse(
                          `m.timestamp >= ${toTimestampWithMs(raSettings.covariateStartDate)} 
                            AND m.timestamp < ${toTimestampWithMs(raSettings.covariateEndDate)}`,
                          `${m.alias}_denominator`,
                          "NULL",
                        ),
                      )} AS ${m.alias}_covariate_denominator`
                    : ""
                }
              `;
              })
              .join("\n")}
          FROM __factTable m
          INNER JOIN (
            SELECT ${baseIdType}
            FROM ${params.unitsSourceTableFullName}
            ${
              params.lastCovariateSuccessfulMaxTimestamp
                ? `WHERE max_timestamp > ${toTimestampWithMs(params.lastCovariateSuccessfulMaxTimestamp)}`
                : ""
            }
          ) d
            ON (d.${baseIdType} = m.${baseIdType})
          GROUP BY
            m.${baseIdType}
        )
      SELECT
        ${baseIdType}
        ${metricData
          .map(
            (
              m, // test this is only RA metrics
            ) =>
              `, ${m.capCoalesceCovariate} AS ${encodeMetricIdForColumnName(m.id)}_value
              ${m.ratioMetric ? `, ${m.capCoalesceDenominatorCovariate} AS ${encodeMetricIdForColumnName(m.id)}_denominator_value` : ""}
        `,
          )
          .join("\n")}
      FROM __newCovariateValues c
      )
      `,
      this.getSqlDialect().formatDialect,
    );
  }

  getCreateMetricSourceTableQuery(
    params: CreateMetricSourceTableQueryParams,
  ): string {
    const exposureQuery = getExposureQuery(
      this.datasource,
      params.settings.exposureQueryId || "",
      undefined,
    );

    const baseIdType = exposureQuery.userIdType;
    const sortedMetrics = params.metrics.sort((a, b) =>
      a.id.localeCompare(b.id),
    );

    const columnDefinitions = this.getMetricSourceTableColumnDefinitions(
      baseIdType,
      sortedMetrics,
    );

    if (
      sortedMetrics.some((m) => quantileMetricType(m) === "event") &&
      !this.hasQuantileKLL()
    ) {
      throw new Error(
        "Event quantile metrics with incremental refresh require a data source that supports KLL quantile sketches.",
      );
    }

    // TODO(incremental-refresh)
    // Compute data types and columns elsewhere and store in metadata to govern this query
    // and for validating queries match going forward
    return format(
      `
    CREATE TABLE ${params.metricSourceTableFullName}
    (
      ${columnDefinitions.join("\n, ")}
    )
    ${this.createTablePartitions(["max_timestamp", "metric_date"])}
    `,
      this.getSqlDialect().formatDialect,
    );
  }

  protected getMetricSourceTableColumnDefinitions(
    baseIdType: string,
    metrics: FactMetricInterface[],
  ): string[] {
    const schema = getMetricSourceTableSchema(
      this.getSqlDialect(),
      baseIdType,
      metrics,
    );
    return Array.from(schema.entries()).map(
      ([columnName, dataType]) => `${columnName} ${dataType}`,
    );
  }

  protected getMetricSourceTableColumns(
    baseIdType: string,
    metrics: FactMetricInterface[],
  ): string[] {
    const schema = getMetricSourceTableSchema(
      this.getSqlDialect(),
      baseIdType,
      metrics,
    );
    return Array.from(schema.keys());
  }

  protected getMetricSourceCovariateTableSchema(
    baseIdType: string,
    metrics: FactMetricInterface[],
  ): Map<string, string> {
    const schema = new Map<string, string>();

    schema.set(baseIdType, this.getSqlDialect().getDataType("string"));

    metrics.forEach((metric) => {
      const numeratorMetadata = getAggregationMetadata(this.getSqlDialect(), {
        metric,
        useDenominator: false,
      });
      schema.set(
        `${encodeMetricIdForColumnName(metric.id)}_value`,
        this.getSqlDialect().getDataType(numeratorMetadata.finalDataType),
      );

      if (isRatioMetric(metric)) {
        const denominatorMetadata = getAggregationMetadata(
          this.getSqlDialect(),
          {
            metric,
            useDenominator: true,
          },
        );
        schema.set(
          `${encodeMetricIdForColumnName(metric.id)}_denominator_value`,
          this.getSqlDialect().getDataType(denominatorMetadata.finalDataType),
        );
      }
    });

    return schema;
  }

  protected getMetricSourceCovariateTableColumnDefinitions(
    baseIdType: string,
    metrics: FactMetricInterface[],
  ): string[] {
    const schema = this.getMetricSourceCovariateTableSchema(
      baseIdType,
      metrics,
    );
    return Array.from(schema.entries()).map(
      ([columnName, dataType]) => `${columnName} ${dataType}`,
    );
  }

  protected getMetricSourceCovariateTableColumns(
    baseIdType: string,
    metrics: FactMetricInterface[],
  ): string[] {
    const schema = this.getMetricSourceCovariateTableSchema(
      baseIdType,
      metrics,
    );
    return Array.from(schema.keys());
  }

  getInsertMetricSourceDataQuery(
    params: InsertMetricSourceDataQueryParams,
  ): string {
    const exposureQuery = getExposureQuery(
      this.datasource,
      params.settings.exposureQueryId || "",
      undefined,
    );

    const factTableMap = params.factTableMap;
    const factTable = factTableMap.get(
      params.metrics[0].numerator?.factTableId,
    );
    if (!factTable) {
      throw new Error("Could not find fact table");
    }

    const { baseIdType, idJoinMap, idJoinSQL } = getIdentitiesCTE(
      this.getSqlDialect(),
      this.datasource.settings,
      {
        objects: [[exposureQuery.userIdType], factTable?.userIdTypes || []],
        // TODO(incremental-refresh): this gets all identities from history
        // of experiment, which we think is right, but could be improved
        from: params.settings.startDate,
        to: params.settings.endDate,
        forcedBaseIdType: exposureQuery.userIdType,
        experimentId: params.settings.experimentId,
      },
    );

    const sortedMetrics = params.metrics.sort((a, b) =>
      a.id.localeCompare(b.id),
    );
    const paramsMetricsSorted = {
      ...params,
      metrics: sortedMetrics,
    };

    // TODO(incremental-refresh): use max hours to convert from here
    // for eventual "skipPartialData" feature
    const { factTablesWithMetricData } = parseExperimentFactMetricsParams(
      this.getSqlDialect(),
      {
        ...paramsMetricsSorted,
        covariateTableAlias: "c",
      },
    );

    // TODO(incremental-refresh): ensure only one fact table with metric data
    // at this part of the query; multi-fact table metrics should be split across
    // their own getInsertMetricSourceDataQuery calls
    if (factTablesWithMetricData.length !== 1) {
      throw new Error("Expected exactly one fact table with metric data");
    }
    const factTableWithMetricData = factTablesWithMetricData[0];
    const metricData = factTableWithMetricData.metricData;

    // Get consistent column names using the helper
    const columnNames = this.getMetricSourceTableColumns(
      baseIdType,
      sortedMetrics,
    );

    return format(
      `
    INSERT INTO ${params.metricSourceTableFullName}
    (${columnNames.join(", \n")})
    SELECT * FROM (
      WITH 
        ${idJoinSQL}
        __factTable AS (${getFactMetricCTE(this.getSqlDialect(), {
          baseIdType,
          idJoinMap,
          metricsWithIndices: factTableWithMetricData.metricData.map((m) => ({
            metric: m.metric,
            index: m.metricIndex,
          })),
          factTable: factTableWithMetricData.factTable,
          startDate: factTableWithMetricData.metricStart,
          endDate: factTableWithMetricData.metricEnd,
          castIdToString: true,
          addFiltersToWhere: true,
          // if last max timestamp is later than metric start and thus the start
          // date, we need to get data strictly greater than, not just greater than
          // or equal to the start date
          exclusiveStartDateFilter:
            factTableWithMetricData.bindingLastMaxTimestamp,
        })})
        , __maxTimestamp AS (
          SELECT ${castToTimestamp("MAX(timestamp)")} AS max_timestamp FROM __factTable
        )
        , __newMetricRows AS (
          SELECT
            m.${baseIdType} AS ${baseIdType}
            , m.timestamp AS timestamp
            ${metricData
              .map(
                (data) =>
                  `, ${addCaseWhenTimeFilter(this.getSqlDialect(), {
                    col: `m.${data.alias}_value`,
                    metric: data.metric,
                    overrideConversionWindows: data.overrideConversionWindows,
                    // The experiment end date, because this is used
                    // to filter metrics that only capture data during
                    // the experiment
                    endDate: params.settings.endDate,
                    metricQuantileSettings: data.quantileMetric
                      ? data.metricQuantileSettings
                      : undefined,
                    metricTimestampColExpr: castToTimestamp("m.timestamp"),
                    exposureTimestampColExpr: "d.first_exposure_timestamp",
                  })} AS ${data.alias}_value
                ${
                  data.ratioMetric
                    ? `, ${addCaseWhenTimeFilter(this.getSqlDialect(), {
                        col: `m.${data.alias}_denominator`,
                        metric: data.metric,
                        overrideConversionWindows:
                          data.overrideConversionWindows,
                        endDate: params.settings.endDate,
                        metricTimestampColExpr: castToTimestamp("m.timestamp"),
                        exposureTimestampColExpr: "d.first_exposure_timestamp",
                      })} AS ${data.alias}_denominator`
                    : ""
                }
                `,
              )
              .join("\n")}
          FROM __factTable m
          INNER JOIN ${params.unitsSourceTableFullName} d
            ON (d.${baseIdType} = m.${baseIdType})
        )
        , __newDailyValues AS (
          SELECT
            ${baseIdType}
            , ${this.getSqlDialect().castToDate("timestamp")} AS metric_date
            ${metricData
              .map((m) => {
                // Use partial aggregation function since we are
                // aggregating at the user-date level, not the user level
                const aggfunction =
                  m.numeratorAggFns.partialAggregationFunction;
                const denomAggFunction =
                  m.denominatorAggFns.partialAggregationFunction;
                return `
                , ${aggfunction(`${m.alias}_value`)} AS ${encodeMetricIdForColumnName(m.id)}_value
                ${
                  !!denomAggFunction && isRatioMetric(m.metric)
                    ? `, ${denomAggFunction(`${m.alias}_denominator`)} AS ${encodeMetricIdForColumnName(m.id)}_denominator_value`
                    : ""
                }
                ${
                  m.quantileMetric === "event"
                    ? `, COUNT(${m.alias}_value) AS ${encodeMetricIdForColumnName(m.id)}_n_events`
                    : ""
                }
              `;
              })
              .join("\n")}
          FROM __newMetricRows
          GROUP BY
            ${baseIdType}
            , ${this.getSqlDialect().castToDate("timestamp")}
        )
       SELECT
          dv.${baseIdType} AS ${baseIdType}
          ${metricData
            .map(
              (m) =>
                `, ${encodeMetricIdForColumnName(m.id)}_value AS ${encodeMetricIdForColumnName(m.id)}_value${
                  m.ratioMetric
                    ? `\n, ${encodeMetricIdForColumnName(m.id)}_denominator_value AS ${encodeMetricIdForColumnName(m.id)}_denominator_value`
                    : ""
                }${
                  m.quantileMetric === "event"
                    ? `\n, ${encodeMetricIdForColumnName(m.id)}_n_events AS ${encodeMetricIdForColumnName(m.id)}_n_events`
                    : ""
                }`,
            )
            .join("\n")}
          , ${this.getSqlDialect().getCurrentTimestamp()} AS refresh_timestamp
          , mt.max_timestamp AS max_timestamp
          , dv.metric_date AS metric_date
        FROM __newDailyValues dv
        CROSS JOIN __maxTimestamp mt
)
      `,
      this.getSqlDialect().formatDialect,
    );
  }

  // TODO(incremental-refresh): only need to run one per group, while the rest of the metrics pipeline
  // needs to run once per fact table, once we allow metrics that cross
  // fact tables to be added
  getIncrementalRefreshStatisticsQuery(
    params: IncrementalRefreshStatisticsQueryParams,
  ): string {
    const exposureQuery = getExposureQuery(
      this.datasource,
      params.settings.exposureQueryId || "",
      undefined,
    );

    const { factTablesWithMetricData } = parseExperimentFactMetricsParams(
      this.getSqlDialect(),
      {
        ...params,
        // Covariate data joined to single table with `m` alias before columns are extracted
        covariateTableAlias: "m",
      },
    );

    // TODO(incremental-refresh): generalize to multiple sources
    if (factTablesWithMetricData.length !== 1) {
      throw new Error("Expected exactly one fact table with metric data");
    }
    const factTableWithMetricData = factTablesWithMetricData[0];
    const metricData = factTableWithMetricData.metricData;
    const percentileData = factTableWithMetricData.percentileData;
    const eventQuantileData = factTableWithMetricData.eventQuantileData;
    const regressionAdjustedMetrics =
      factTableWithMetricData.regressionAdjustedMetrics;

    const regressionAdjustedTableIndices = new Set<number>();
    if (regressionAdjustedMetrics.length > 0) {
      regressionAdjustedTableIndices.add(0);
    }
    const percentileTableIndices = new Set<number>();
    if (percentileData.length > 0) {
      percentileTableIndices.add(0);
    }

    // exploratory dimensions
    const { experimentDimensions, unitDimensions, dateDimension } =
      processDimensions(
        this.getSqlDialect(),
        params.dimensionsForAnalysis,
        params.settings,
        params.activationMetric,
      );

    const idTypeObjects = [
      [exposureQuery.userIdType],
      ...unitDimensions.map((d) => [d.dimension.userIdType]),
    ];

    const { baseIdType, idJoinMap, idJoinSQL } = getIdentitiesCTE(
      this.getSqlDialect(),
      this.datasource.settings,
      {
        objects: idTypeObjects,
        from: params.settings.startDate,
        to: params.settings.endDate,
        forcedBaseIdType: exposureQuery.userIdType,
        experimentId: params.settings.experimentId,
      },
    );

    const unitDimensionCols = unitDimensions.map((d) => ({
      // override value with the a MAX statement that will get one
      // value per unit
      value: getDimensionValuePerUnit(this.getSqlDialect(), d),
      alias: getDimensionCol(this.getSqlDialect(), d).alias,
    }));

    const experimentDimensionCols = experimentDimensions.map((d) =>
      getDimensionCol(this.getSqlDialect(), d),
    );
    const precomputedDimensionCols: DimensionColumnData[] =
      params.dimensionsForPrecomputation.map((d) => {
        const col = getDimensionCol(this.getSqlDialect(), d);
        // override value with case when statement for precomputed dimensions
        const value = getDimensionInStatement(
          this.getSqlDialect(),
          col.alias,
          d.specifiedSlices,
        );
        return {
          value,
          alias: col.alias,
        };
      });
    const dateDimensionCol = dateDimension
      ? getDimensionCol(this.getSqlDialect(), dateDimension)
      : undefined;

    const nonUnitDimensionCols = [
      ...experimentDimensionCols,
      ...(dateDimensionCol ? [dateDimensionCol] : []),
      ...precomputedDimensionCols,
    ];
    const allDimensionCols = [...nonUnitDimensionCols, ...unitDimensionCols];
    // TODO(incremental-refresh): Handle activation metric in dimensions
    // like in getExperimentFactMetricsQuery
    // TODO(incremental-refresh): Validate with existing columns
    return format(
      `
      WITH 
      ${idJoinSQL}
      __metricSourceData AS (
        SELECT * FROM ${params.metricSourceTableFullName}
      )
      ${unitDimensions
        .map(
          (d) =>
            `, __dim_unit_${d.dimension.id} AS (${getDimensionCTE(
              d.dimension,
              baseIdType,
              idJoinMap,
            )})`,
        )
        .join("\n")}
      , __experimentUnits AS (${
        unitDimensions.length > 0
          ? `SELECT
            e.${baseIdType} AS ${baseIdType}
            , MIN(e.variation) AS variation
            , MIN(e.first_exposure_timestamp) AS first_exposure_timestamp
            ${unitDimensionCols.map((d) => `, ${d.value} AS ${d.alias}`).join("")}
            ${nonUnitDimensionCols.map((d) => `, MIN(${d.value}) AS ${d.alias}`).join("")}
          FROM ${params.unitsSourceTableFullName} e
          ${unitDimensions
            .map(
              (
                d,
              ) => `LEFT JOIN __dim_unit_${d.dimension.id} __dim_unit_${d.dimension.id} ON (
            ${this.getSqlDialect().castToString(`__dim_unit_${d.dimension.id}.${baseIdType}`)} = e.${baseIdType}
          )`,
            )
            .join("\n")}
          GROUP BY
            e.${baseIdType}
      `
          : `SELECT
          e.${baseIdType} AS ${baseIdType}
          , e.variation AS variation
          , e.first_exposure_timestamp AS first_exposure_timestamp
          ${nonUnitDimensionCols.map((d) => `, ${d.value} AS ${d.alias}`).join("")}
        FROM ${params.unitsSourceTableFullName} e`
      })
      , __metricDataAggregated AS (
        SELECT
          ${baseIdType}
          ${metricData
            .map((data) => {
              const reAggFunction = data.numeratorAggFns.reAggregationFunction;
              const denomReAggFunction =
                data.denominatorAggFns.reAggregationFunction;
              return `, ${reAggFunction(`umj.${encodeMetricIdForColumnName(data.metric.id)}_value`)} AS ${encodeMetricIdForColumnName(data.metric.id)}_value
                ${
                  data.ratioMetric && denomReAggFunction
                    ? `, ${denomReAggFunction(`umj.${encodeMetricIdForColumnName(data.metric.id)}_denominator_value`)} AS ${encodeMetricIdForColumnName(data.metric.id)}_denominator_value`
                    : ""
                }
                ${
                  data.quantileMetric === "event"
                    ? `, SUM(COALESCE(umj.${encodeMetricIdForColumnName(data.metric.id)}_n_events, 0)) AS ${encodeMetricIdForColumnName(data.metric.id)}_n_events`
                    : ""
                }`;
            })
            .join("\n")}
        FROM __metricSourceData umj
        GROUP BY
          ${baseIdType}
      )
      ${
        eventQuantileData.length > 0
          ? `
      , __eventQuantileSketch AS (
        -- Pass 1 of two-pass KLL rank recovery: merge per-user sketches by
        -- variation+dimension. __eventQuantileMetric extracts the quantile grid
        -- (including q_hat) from these merged sketches; __joinedData then uses
        -- q_hat as the threshold for per-user rank recovery (pass 2).
        SELECT
          u.variation AS variation
          ${allDimensionCols.map((c) => `, u.${c.alias} AS ${c.alias}`).join("")}
          ${metricData
            .filter((d) => d.quantileMetric === "event")
            .map(
              (d) =>
                `, ${this.getSqlDialect().kllMergePartial(`m.${encodeMetricIdForColumnName(d.metric.id)}_value`)} AS ${d.alias}_sketch`,
            )
            .join("\n")}
        FROM __experimentUnits u
        INNER JOIN __metricDataAggregated m ON u.${baseIdType} = m.${baseIdType}
        GROUP BY
          u.variation
          ${allDimensionCols.map((c) => `, u.${c.alias}`).join("")}
      )
      , __eventQuantileMetric AS (
        SELECT
          variation
          ${allDimensionCols.map((c) => `, ${c.alias}`).join("")}
          ${metricData
            .filter((d) => d.quantileMetric === "event")
            .map((d) =>
              this.getKllQuantileGridColumns(
                d.metricQuantileSettings,
                `${d.alias}_sketch`,
                `${d.alias}_`,
              ),
            )
            .join("\n")}
        FROM __eventQuantileSketch
      )
      `
          : ""
      }
      , __joinedData AS (
          SELECT
            u.${baseIdType}
            ${allDimensionCols.map((d) => `, u.${d.alias} AS ${d.alias}`).join("")}
            , u.variation
            ${metricData
              .map((data) => {
                if (data.quantileMetric === "event") {
                  // Two-pass KLL rank recovery: __eventQuantileMetric provides
                  // the global q_hat per variation+dimension (pass 1). Here we
                  // extract a 100-point CDF from each user's merged sketch and
                  // count the fraction below q_hat to recover a per-user
                  // "count below threshold" with ±0.5% rank precision (pass 2).
                  // This preserves per-user variance in both event volume and
                  // fraction-below-threshold, so the cluster-adjusted variance
                  // estimator in QuantileClusteredStatistic is correct.
                  // Note: ignoreZeros for event quantiles is handled upstream in
                  // addCaseWhenTimeFilter (zeros are filtered out of __newMetricRows
                  // before sketching, so they never enter the KLL sketch or n_events).
                  const nEventsCol = `COALESCE(m.${encodeMetricIdForColumnName(data.metric.id)}_n_events, 0)`;
                  const sketchCol = `m.${encodeMetricIdForColumnName(data.metric.id)}_value`;
                  const thresholdCol = `qm.${data.alias}_quantile`;
                  return `, ${this.getSqlDialect().kllRankApprox(sketchCol, thresholdCol, nEventsCol, 100)} AS ${data.alias}_value
                  , ${nEventsCol} AS ${data.alias}_n_events`;
                }
                // Unit quantiles with ignoreZeros: reAggregationFunction already
                // returns NULLIF(..., 0) so _value is NULL for zero-sum users.
                // Preserve that NULL here (don't COALESCE) so approxQuantile
                // excludes them. For all other metrics COALESCE is correct — a
                // NULL from the LEFT JOIN means zero events for that user.
                const nullIfZero =
                  data.quantileMetric === "unit" &&
                  data.metricQuantileSettings.ignoreZeros;
                const valueCol = nullIfZero
                  ? `m.${encodeMetricIdForColumnName(data.metric.id)}_value`
                  : `COALESCE(m.${encodeMetricIdForColumnName(data.metric.id)}_value, 0)`;
                return `, ${data.aggregatedValueTransformation({
                  column: valueCol,
                  initialTimestampColumn: "u.first_exposure_timestamp",
                  analysisEndDate: params.settings.endDate,
                })} AS ${data.alias}_value ${
                  data.ratioMetric
                    ? `, ${data.aggregatedValueTransformation({
                        column: `COALESCE(m.${encodeMetricIdForColumnName(data.metric.id)}_denominator_value, 0)`,
                        initialTimestampColumn: "u.first_exposure_timestamp",
                        analysisEndDate: params.settings.endDate,
                      })} AS ${data.alias}_denominator`
                    : ""
                }`;
              })
              .join("\n")}
            ${
              regressionAdjustedMetrics.length > 0
                ? regressionAdjustedMetrics
                    .map(
                      (data) =>
                        `, c.${data.alias}_covariate_value AS ${data.alias}_covariate_value
                        ${
                          data.ratioMetric
                            ? `, c.${data.alias}_covariate_denominator AS ${data.alias}_covariate_denominator`
                            : ""
                        }`,
                    )
                    .join("\n")
                : ""
            }
          FROM __experimentUnits u
          LEFT JOIN __metricDataAggregated m ON u.${baseIdType} = m.${baseIdType}
          ${
            // TODO(incremental-refresh): GROUP BY is not necessary but is a failsafe
            // against bad insertions into covariate table
            regressionAdjustedMetrics.length > 0
              ? `LEFT JOIN (
                SELECT
                  ${baseIdType}
                  ${regressionAdjustedMetrics
                    .map(
                      (data) =>
                        `, MAX(${encodeMetricIdForColumnName(data.id)}_value) AS ${data.alias}_covariate_value
                        ${
                          data.ratioMetric
                            ? `, MAX(${encodeMetricIdForColumnName(data.id)}_denominator_value) AS ${data.alias}_covariate_denominator`
                            : ""
                        }`,
                    )
                    .join("\n")}
                FROM ${params.metricSourceCovariateTableFullName}
                GROUP BY ${baseIdType}
              ) c ON u.${baseIdType} = c.${baseIdType}`
              : ""
          }
          ${
            // Dimension-equality join mirrors the existing pattern at
            // getExperimentFactMetricStatisticsCTE (NULL = NULL → false is
            // acceptable; dimensions are COALESCEd to a sentinel upstream).
            eventQuantileData.length > 0
              ? `LEFT JOIN __eventQuantileMetric qm ON (
                  qm.variation = u.variation
                  ${allDimensionCols.map((c) => `AND qm.${c.alias} = u.${c.alias}`).join("\n")}
                )`
              : ""
          }
      )
      ${
        percentileData.length > 0
          ? `
        , __capValue AS (
            ${this.getSqlDialect().percentileCapSelectClause(percentileData, "__joinedData")}
        )
        `
          : ""
      }
      ${getExperimentFactMetricStatisticsCTE(this.getSqlDialect(), {
        dimensionCols: allDimensionCols,
        metricData,
        eventQuantileData,
        baseIdType,
        joinedMetricTableName: "__joinedData",
        eventQuantileTableName: "__eventQuantileMetric",
        capValueTableName: "__capValue",
        factTablesWithIndices: [
          {
            factTable: factTableWithMetricData.factTable,
            index: 0,
          },
        ],
        percentileTableIndices,
      })}
      `,
      this.getSqlDialect().formatDialect,
    );
  }

  async runIncrementalRefreshStatisticsQuery(
    sql: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ): Promise<ExperimentFactMetricsQueryResponse> {
    const { rows, statistics } = await this.runQuery(
      sql,
      setExternalId,
      queryMetadata,
    );
    return {
      rows: this.processExperimentFactMetricsQueryRows(rows),
      statistics: statistics,
    };
  }

  getSampleUnitsCTE(): string {
    return getSampleUnitsCTE(this.getSqlDialect());
  }

  getProductAnalyticsQuery(
    config: ExplorationConfig,
    {
      factTableMap,
      metricMap,
    }: {
      factTableMap: FactTableMap;
      metricMap: Map<string, FactMetricInterface>;
    },
  ): {
    sql: string;
    orderedMetricIds: string[];
    startDate: Date;
    endDate: Date;
  } {
    const dialect = this.getSqlDialect();

    const dateRange = calculateProductAnalyticsDateRange(config.dateRange);

    const resolvedFactTableMap: FactTableMap = new Map(
      Array.from(factTableMap.entries()).map(([id, ft]) => {
        const templateVariables = getFactTableTemplateVariables(ft);
        const hasTemplateVars = Object.values(templateVariables).some(Boolean);
        if (!hasTemplateVars) return [id, ft];
        return [
          id,
          {
            ...ft,
            sql: compileSqlTemplate(
              ft.sql,
              {
                startDate: dateRange.startDate,
                endDate: dateRange.endDate,
                templateVariables,
              },
              this.getSqlDialect(),
            ),
          },
        ];
      }),
    );

    const { sql, orderedMetricIds } = generateProductAnalyticsSQL(
      config,
      resolvedFactTableMap,
      metricMap,
      dialect,
      this.datasource,
    );

    return {
      sql: compileSqlTemplate(
        sql,
        {
          startDate: dateRange.startDate,
          endDate: dateRange.endDate,
        },
        this.getSqlDialect(),
      ),
      orderedMetricIds,
      startDate: dateRange.startDate,
      endDate: dateRange.endDate,
    };
  }

  async runProductAnalyticsQuery(
    query: string,
    setExternalId: ExternalIdCallback,
    queryMetadata?: QueryMetadata,
  ) {
    return this.runQuery(query, setExternalId, queryMetadata);
  }
}
