// THIS FILE IS AUTOGENERATED BY `pnpm gen-sdk-resources`. DO NOT EDIT DIRECTLY.

export default {
  js: {
    name: "JS SDK",
    version: "1.6.4",
    github:
      "https://github.com/growthbook/growthbook/tree/main/packages/sdk-js",
    examples: [
      {
        url: "https://github.com/growthbook/examples/tree/main/vanilla-typescript",
        name: "Typescript example app",
      },
    ],
    packageRepos: [
      {
        name: "npm",
        url: "https://www.npmjs.com/package/@growthbook/growthbook",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        caseInsensitiveMembership: "≥ v1.6.4",
      },
      {
        caseInsensitiveRegex: "≥ v1.6.3",
      },
      {
        savedGroupReferences: "≥ v1.1.0",
      },
      {
        redirects: "≥ v0.36.0",
      },
      {
        prerequisites: "≥ v0.34.0",
      },
      {
        stickyBucketing: "≥ v0.32.0",
      },
      {
        visualEditorDragDrop: "≥ v0.30.0",
      },
      {
        remoteEval: "≥ v0.29.0",
      },
      {
        semverTargeting: "≥ v0.27.0",
      },
      {
        visualEditorJS: "≥ v0.27.0",
      },
      {
        visualEditor: "≥ v0.24.0",
      },
      {
        bucketingV2: "≥ v0.23.0",
      },
      {
        streaming: "≥ v0.21.0",
      },
      {
        encryption: "≥ v0.20.0",
      },
      {
        looseUnmarshalling: "≥ v0.0.0",
      },
    ],
  },
  react: {
    name: "React SDK",
    version: "1.6.4",
    github:
      "https://github.com/growthbook/growthbook/tree/main/packages/sdk-react",
    examples: [
      {
        url: "https://github.com/growthbook/examples/tree/main/next-js",
        name: "Next.js example app",
      },
      {
        url: "https://github.com/growthbook/examples/tree/main/next-js-pages",
        name: "Next.js pages example app",
      },
      {
        url: "https://docs.growthbook.io/guide/create-react-app-and-growthbook",
        name: "Create React App guide",
      },
    ],
    packageRepos: [
      {
        name: "npm",
        url: "https://www.npmjs.com/package/@growthbook/growthbook-react",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        caseInsensitiveMembership: "≥ v1.6.4",
      },
      {
        caseInsensitiveRegex: "≥ v1.6.3",
      },
      {
        savedGroupReferences: "≥ v1.1.0",
      },
      {
        redirects: "≥ v0.26.0",
      },
      {
        prerequisites: "≥ v0.24.0",
      },
      {
        stickyBucketing: "≥ v0.22.0",
      },
      {
        visualEditorDragDrop: "≥ v0.20.0",
      },
      {
        remoteEval: "≥ v0.19.0",
      },
      {
        semverTargeting: "≥ v0.17.0",
      },
      {
        visualEditorJS: "≥ v0.17.0",
      },
      {
        visualEditor: "≥ v0.14.0",
      },
      {
        bucketingV2: "≥ v0.13.0",
      },
      {
        streaming: "≥ v0.11.0",
      },
      {
        encryption: "≥ v0.10.1",
      },
      {
        looseUnmarshalling: "≥ v0.0.0",
      },
    ],
  },
  nextjs: {
    name: "Next.js SDK",
    version: "0.1.0",
    github:
      "https://github.com/vercel/flags/tree/main/packages/adapter-growthbook",
    examples: [
      {
        url: "https://github.com/vercel/examples/tree/main/flags-sdk/growthbook",
        name: "Next.js Flags SDK example app",
      },
    ],
    packageRepos: [
      {
        name: "npm",
        url: "https://www.npmjs.com/package/@flags-sdk/growthbook",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        savedGroupReferences: "≥ v0.1.0",
      },
      {
        redirects: "≥ v0.1.0",
      },
      {
        prerequisites: "≥ v0.1.0",
      },
      {
        stickyBucketing: "≥ v0.1.0",
      },
      {
        semverTargeting: "≥ v0.1.0",
      },
      {
        bucketingV2: "≥ v0.1.0",
      },
      {
        encryption: "≥ v0.1.0",
      },
      {
        looseUnmarshalling: "≥ v0.1.0",
      },
    ],
  },
  php: {
    name: "PHP SDK",
    version: "1.7.0",
    github: "https://github.com/growthbook/growthbook-php",
    examples: [],
    packageRepos: [
      {
        name: "Packagist (Composer)",
        url: "https://packagist.org/packages/growthbook/growthbook",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        savedGroupReferences: "≥ v1.7.0",
      },
      {
        prerequisites: "≥ v1.6.0",
      },
      {
        stickyBucketing: "≥ v1.6.0",
      },
      {
        semverTargeting: "≥ v1.5.0",
      },
      {
        bucketingV2: "≥ v1.2.0",
      },
      {
        encryption: "≥ v1.2.0",
      },
      {
        looseUnmarshalling: "≥ v1.0.0",
      },
    ],
  },
  node: {
    name: "Node SDK",
    version: "1.6.4",
    github:
      "https://github.com/growthbook/growthbook/tree/main/packages/sdk-js",
    examples: [
      {
        url: "https://docs.growthbook.io/guide/express-js",
        name: "Express.js guide",
      },
    ],
    packageRepos: [
      {
        name: "npm",
        url: "https://www.npmjs.com/package/@growthbook/growthbook",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        caseInsensitiveMembership: "≥ v1.6.4",
      },
      {
        caseInsensitiveRegex: "≥ v1.6.3",
      },
      {
        savedGroupReferences: "≥ v1.1.0",
      },
      {
        redirects: "≥ v0.36.0",
      },
      {
        prerequisites: "≥ v0.34.0",
      },
      {
        stickyBucketing: "≥ v0.32.0",
      },
      {
        semverTargeting: "≥ v0.27.0",
      },
      {
        bucketingV2: "≥ v0.23.0",
      },
      {
        streaming: "≥ v0.21.0",
      },
      {
        encryption: "≥ v0.20.0",
      },
      {
        looseUnmarshalling: "≥ v0.0.0",
      },
    ],
  },
  ruby: {
    name: "Ruby SDK",
    version: "1.3.0",
    github: "https://github.com/growthbook/growthbook-ruby",
    examples: [
      {
        url: "https://github.com/growthbook/examples/tree/main/acme_donuts_rails",
        name: "Rails example app",
      },
    ],
    packageRepos: [
      {
        name: "RubyGems",
        url: "https://rubygems.org/gems/growthbook",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        prerequisites: "≥ v1.3.0",
      },
      {
        stickyBucketing: "≥ v1.3.0",
      },
      {
        semverTargeting: "≥ v1.2.2",
      },
      {
        encryption: "≥ v1.1.0",
      },
      {
        bucketingV2: "≥ v1.0.0",
      },
      {
        looseUnmarshalling: "≥ v0.0.0",
      },
    ],
  },
  python: {
    name: "Python SDK",
    version: "2.1.1",
    github: "https://github.com/growthbook/growthbook-python",
    examples: [],
    packageRepos: [
      {
        name: "PyPi",
        url: "https://pypi.org/project/growthbook/",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        caseInsensitiveMembership: "≥ v2.1.1",
      },
      {
        caseInsensitiveRegex: "≥ v2.1.0",
      },
      {
        savedGroupReferences: "≥ v1.2.1",
      },
      {
        looseUnmarshalling: "≥ v1.1.0",
      },
      {
        prerequisites: "≥ v1.1.0",
      },
      {
        stickyBucketing: "≥ v1.1.0",
      },
      {
        semverTargeting: "≥ v1.1.0",
      },
      {
        bucketingV2: "≥ v1.0.0",
      },
      {
        encryption: "≥ v1.0.0",
      },
    ],
  },
  go: {
    name: "Go SDK",
    version: "0.2.6",
    github: "https://github.com/growthbook/growthbook-golang",
    examples: [
      {
        url: "https://github.com/growthbook/examples/tree/main/go-example",
        name: "Go example app",
      },
    ],
    packageRepos: [
      {
        name: "Go Modules",
        url: "https://pkg.go.dev/github.com/growthbook/growthbook-golang",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        stickyBucketing: "≥ v0.2.3",
      },
      {
        prerequisites: "≥ v0.2.0",
      },
      {
        savedGroupReferences: "≥ v0.2.0",
      },
      {
        bucketingV2: "≥ v0.1.4",
      },
      {
        streaming: "≥ v0.1.4",
      },
      {
        semverTargeting: "≥ v0.1.4",
      },
      {
        encryption: "≥ v0.1.4",
      },
      {
        looseUnmarshalling: "≥ v0.0.0",
      },
    ],
  },
  rust: {
    name: "Rust SDK",
    version: "0.0.3",
    github: "https://github.com/growthbook/growthbook-rust",
    examples: [
      {
        url: "https://github.com/growthbook/growthbook-rust/tree/main/examples/client",
        name: "Rust example app",
      },
    ],
    packageRepos: [
      {
        name: "crates.io",
        url: "https://crates.io/crates/growthbook-rust",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        caseInsensitiveRegex: "≥ v0.1.1",
      },
      {
        caseInsensitiveMembership: "≥ v0.1.1",
      },
      {
        stickyBucketing: "≥ v0.1.0",
      },
      {
        encryption: "≥ v0.0.1",
      },
      {
        looseUnmarshalling: "≥ v0.0.1",
      },
      {
        prerequisites: "≥ v0.0.1",
      },
      {
        semverTargeting: "≥ v0.0.1",
      },
      {
        bucketingV2: "≥ v0.0.1",
      },
    ],
  },
  java: {
    name: "Java SDK",
    version: "0.10.6",
    github: "https://github.com/growthbook/growthbook-sdk-java",
    examples: [
      {
        url: "https://github.com/growthbook/examples/tree/main/jvm-spring-web",
        name: "JVM with Spring Web example app",
      },
      {
        url: "https://github.com/growthbook/examples/tree/main/jvm-kotlin-ktor-example",
        name: "JVM with Kotlin Ktor example app",
      },
      {
        url: "https://github.com/growthbook/examples/tree/main/android-example",
        name: "Android example app",
      },
      {
        url: "https://growthbook.github.io/growthbook-sdk-java/",
        name: "JavaDoc class docs",
      },
    ],
    packageRepos: [
      {
        name: "JitPack",
        url: "https://jitpack.io/#growthbook/growthbook-sdk-java",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        caseInsensitiveRegex: "≥ v0.10.6",
      },
      {
        remoteEvaluation: "≥ v0.9.92",
      },
      {
        prerequisites: "≥ v0.9.3",
      },
      {
        stickyBucketing: "≥ v0.9.3",
      },
      {
        streaming: "≥ v0.9.0",
      },
      {
        semverTargeting: "≥ v0.7.0",
      },
      {
        bucketingV2: "≥ v0.6.0",
      },
      {
        encryption: "≥ v0.3.0",
      },
      {
        looseUnmarshalling: "≥ v0.0.0",
      },
    ],
  },
  csharp: {
    name: "C# SDK",
    version: "1.1.3",
    github: "https://github.com/growthbook/growthbook-c-sharp",
    examples: [
      {
        url: "https://github.com/growthbook/examples/tree/main/csharp-example/GrowthBookCSharpExamples",
        name: "C# example app",
      },
    ],
    packageRepos: [
      {
        name: "NuGet",
        url: "https://www.nuget.org/packages/growthbook-c-sharp",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        remoteEvaluation: "≥ v1.1.3",
      },
      {
        stickyBucketing: "≥ v1.1.0",
      },
      {
        prerequisites: "≥ v1.1.0",
      },
      {
        savedGroupReferences: "≥ v1.1.0",
      },
      {
        encryption: "≥ v1.0.0",
      },
      {
        streaming: "≥ v1.0.0",
      },
      {
        bucketingV2: "≥ v1.0.0",
      },
      {
        semverTargeting: "≥ v1.0.0",
      },
      {
        looseUnmarshalling: "≥ v0.0.0",
      },
    ],
  },
  elixir: {
    name: "Elixir SDK",
    version: "0.3.0",
    github: "https://github.com/growthbook/growthbook-elixir",
    examples: [],
    packageRepos: [
      {
        name: "Hex",
        url: "https://www.hex.pm/packages/growthbook",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        encryption: "≥ v0.3.0",
      },
      {
        prerequisites: "≥ v0.2.0",
      },
      {
        semverTargeting: "≥ v0.2.0",
      },
      {
        bucketingV2: "≥ v0.2.0",
      },
      {
        looseUnmarshalling: "≥ v0.2.0",
      },
    ],
  },
  kotlin: {
    name: "Kotlin SDK",
    version: "6.1.1",
    github: "https://github.com/growthbook/growthbook-kotlin",
    examples: [],
    packageRepos: [
      {
        name: "Maven Central",
        url: "https://mvnrepository.com/artifact/io.growthbook.sdk/GrowthBook",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        remoteEval: "≥ v1.1.50",
      },
      {
        streaming: "≥ v1.1.50",
      },
      {
        prerequisites: "≥ v1.1.44",
      },
      {
        stickyBucketing: "≥ v1.1.44",
      },
      {
        bucketingV2: "≥ v1.1.38",
      },
      {
        semverTargeting: "≥ v1.1.31",
      },
      {
        encryption: "≥ v1.1.23",
      },
      {
        looseUnmarshalling: "≥ v0.0.0",
      },
    ],
  },
  swift: {
    name: "Swift SDK",
    version: "1.0.95",
    github: "https://github.com/growthbook/growthbook-swift",
    examples: [],
    packageRepos: [
      {
        name: "Swift Package Manager (SPM)",
        url: "https://swiftpackageindex.com/growthbook/growthbook-swift",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        remoteEval: "≥ v1.0.50",
      },
      {
        stickyBucketing: "≥ v1.0.49",
      },
      {
        prerequisites: "≥ v1.0.49",
      },
      {
        bucketingV2: "≥ v1.0.43",
      },
      {
        streaming: "≥ v1.0.43",
      },
      {
        semverTargeting: "≥ v1.0.38",
      },
      {
        encryption: "≥ v1.0.35",
      },
      {
        looseUnmarshalling: "≥ v0.0.0",
      },
    ],
  },
  reactNative: {
    name: "React Native SDK",
    version: "1.6.4",
    github:
      "https://github.com/growthbook/growthbook/tree/main/packages/sdk-react",
    examples: [
      {
        url: "https://github.com/growthbook/examples/tree/main/react-native-cli",
        name: "React Native CLI example app",
      },
    ],
    packageRepos: [
      {
        name: "npm",
        url: "https://www.npmjs.com/package/@growthbook/growthbook-react",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        caseInsensitiveMembership: "≥ v1.6.4",
      },
      {
        caseInsensitiveRegex: "≥ v1.6.3",
      },
      {
        savedGroupReferences: "≥ v1.1.0",
      },
      {
        redirects: "≥ v0.26.0",
      },
      {
        prerequisites: "≥ v0.24.0",
      },
      {
        stickyBucketing: "≥ v0.22.0",
      },
      {
        visualEditorDragDrop: "≥ v0.20.0",
      },
      {
        remoteEval: "≥ v0.19.0",
      },
      {
        semverTargeting: "≥ v0.17.0",
      },
      {
        visualEditorJS: "≥ v0.17.0",
      },
      {
        visualEditor: "≥ v0.14.0",
      },
      {
        bucketingV2: "≥ v0.13.0",
      },
      {
        streaming: "≥ v0.11.0",
      },
      {
        encryption: "≥ v0.10.1",
      },
      {
        looseUnmarshalling: "≥ v0.0.0",
      },
    ],
  },
  edgeCloudflare: {
    name: "Cloudflare Workers App & SDK",
    version: "0.2.6",
    github:
      "https://github.com/growthbook/growthbook-proxy/tree/main/packages/lib/edge-cloudflare",
    examples: [
      {
        url: "https://github.com/growthbook/growthbook-proxy/tree/main/packages/lib/edge-cloudflare/example",
        name: "Example worker",
      },
    ],
    packageRepos: [
      {
        name: "npm",
        url: "https://www.npmjs.com/package/@growthbook/edge-cloudflare",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        savedGroupReferences: "≥ v0.1.12",
      },
      {
        looseUnmarshalling: "≥ v0.1.11",
      },
      {
        encryption: "≥ v0.1.11",
      },
      {
        streaming: "≥ v0.1.11",
      },
      {
        bucketingV2: "≥ v0.1.11",
      },
      {
        visualEditor: "≥ v0.1.11",
      },
      {
        semverTargeting: "≥ v0.1.11",
      },
      {
        visualEditorJS: "≥ v0.1.11",
      },
      {
        visualEditorDragDrop: "≥ v0.1.11",
      },
      {
        prerequisites: "≥ v0.1.11",
      },
      {
        redirects: "≥ v0.1.11",
      },
      {
        stickyBucketing: "≥ v0.1.11",
      },
    ],
  },
  edgeFastly: {
    name: "Fastly Compute App & SDK",
    version: "0.2.6",
    github:
      "https://github.com/growthbook/growthbook-proxy/tree/main/packages/lib/edge-fastly",
    examples: [
      {
        url: "https://github.com/growthbook/growthbook-proxy/tree/main/packages/lib/edge-fastly/example",
        name: "Example compute worker",
      },
    ],
    packageRepos: [
      {
        name: "npm",
        url: "https://www.npmjs.com/package/@growthbook/edge-fastly",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        savedGroupReferences: "≥ v0.1.6",
      },
      {
        looseUnmarshalling: "≥ v0.1.5",
      },
      {
        encryption: "≥ v0.1.5",
      },
      {
        streaming: "≥ v0.1.5",
      },
      {
        bucketingV2: "≥ v0.1.5",
      },
      {
        visualEditor: "≥ v0.1.5",
      },
      {
        semverTargeting: "≥ v0.1.5",
      },
      {
        visualEditorJS: "≥ v0.1.5",
      },
      {
        visualEditorDragDrop: "≥ v0.1.5",
      },
      {
        prerequisites: "≥ v0.1.5",
      },
      {
        redirects: "≥ v0.1.5",
      },
      {
        stickyBucketing: "≥ v0.1.5",
      },
    ],
  },
  edgeLambda: {
    name: "Lambda@Edge App & SDK",
    version: "0.0.26",
    github:
      "https://github.com/growthbook/growthbook-proxy/tree/main/packages/lib/edge-lambda",
    examples: [],
    packageRepos: [
      {
        name: "npm",
        url: "https://www.npmjs.com/package/@growthbook/edge-lambda",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        savedGroupReferences: "≥ v0.0.7",
      },
      {
        looseUnmarshalling: "≥ v0.0.6",
      },
      {
        encryption: "≥ v0.0.6",
      },
      {
        streaming: "≥ v0.0.6",
      },
      {
        bucketingV2: "≥ v0.0.6",
      },
      {
        visualEditor: "≥ v0.0.6",
      },
      {
        semverTargeting: "≥ v0.0.6",
      },
      {
        visualEditorJS: "≥ v0.0.6",
      },
      {
        visualEditorDragDrop: "≥ v0.0.6",
      },
      {
        prerequisites: "≥ v0.0.6",
      },
      {
        redirects: "≥ v0.0.6",
      },
      {
        stickyBucketing: "≥ v0.0.6",
      },
    ],
  },
  edgeUtils: {
    name: "Edge Utils",
    version: "0.2.5",
    github:
      "https://github.com/growthbook/growthbook-proxy/tree/main/packages/lib/edge-utils",
    examples: [],
    packageRepos: [
      {
        name: "npm",
        url: "https://www.npmjs.com/package/@growthbook/edge-utils",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        savedGroupReferences: "≥ v0.1.5",
      },
      {
        looseUnmarshalling: "≥ v0.1.4",
      },
      {
        encryption: "≥ v0.1.4",
      },
      {
        streaming: "≥ v0.1.4",
      },
      {
        bucketingV2: "≥ v0.1.4",
      },
      {
        visualEditor: "≥ v0.1.4",
      },
      {
        semverTargeting: "≥ v0.1.4",
      },
      {
        visualEditorJS: "≥ v0.1.4",
      },
      {
        visualEditorDragDrop: "≥ v0.1.4",
      },
      {
        prerequisites: "≥ v0.1.4",
      },
      {
        redirects: "≥ v0.1.4",
      },
      {
        stickyBucketing: "≥ v0.1.4",
      },
    ],
  },
  flutter: {
    name: "Flutter SDK",
    version: "4.2.1",
    github: "https://github.com/growthbook/growthbook-flutter",
    examples: [],
    packageRepos: [
      {
        name: "pub.dev",
        url: "https://pub.dev/packages/growthbook_sdk_flutter",
      },
    ],
    capabilities: [
      {
        features: "All versions",
      },
      {
        experimentation: "All versions",
      },
      {
        stickyBucketing: "≥ v3.8.0",
      },
      {
        remoteEval: "≥ v3.7.0",
      },
      {
        streaming: "≥ v3.4.0",
      },
      {
        prerequisites: "≥ v3.2.0",
      },
      {
        encryption: "≥ v3.1.0",
      },
      {
        bucketingV2: "≥ v3.1.0",
      },
      {
        semverTargeting: "≥ v3.1.0",
      },
      {
        looseUnmarshalling: "≥ v0.0.0",
      },
    ],
  },
};
