import { SettingsSearchItem } from "./SettingsSearchBar";

export const SETTINGS_SEARCH_ITEMS: SettingsSearchItem[] = [
  {
    id: "org-license-settings",
    label: "Organization & License",
    keywords: [
      "organization",
      "license",
      "company",
      "name",
      "owner",
      "installation",
      "enterprise",
    ],
    tab: null,
    tabLabel: "General",
  },
  {
    id: "experiment-settings",
    label: "Experiment Settings",
    keywords: [
      "experiment",
      "pre-launch checklist",
      "checklist",
      "templates",
      "require experiment templates",
      "import length",
      "past experiments",
      "minimum experiment length",
      "fact table",
      "query optimization",
      "multi-metric",
      "BigQuery",
      "Snowflake",
      "precomputed",
      "dimension breakdowns",
      "conversion window",
      "attribution model",
      "first exposure",
      "auto-update",
      "auto update",
      "frequency",
      "refresh",
      "cron",
      "schedule",
      "stale",
      "sticky bucketing",
      "fallback attributes",
      "health",
      "SRM",
      "sample ratio mismatch",
      "traffic query",
      "multiple exposure",
      "decision framework",
      "decision criteria",
      "experiment length",
      "stats engine",
      "statistics",
      "bayesian",
      "frequentist",
      "confidence level",
      "p-value",
      "sequential testing",
      "CUPED",
      "regression adjustment",
      "post-stratification",
    ],
    tab: "experiment",
    tabLabel: "Experiment Settings",
  },
  {
    id: "bandit-settings",
    label: "Bandit Settings",
    keywords: [
      "bandit",
      "multi-armed bandit",
      "MAB",
      "burn-in",
      "update cadence",
    ],
    tab: "experiment",
    tabLabel: "Experiment Settings",
  },
  {
    id: "feature-settings",
    label: "Feature Settings",
    keywords: [
      "feature",
      "feature flag",
      "secure attribute",
      "salt",
      "feature key",
      "regex",
      "validator",
      "naming convention",
      "kill switch",
      "killswitch",
      "confirmation",
      "require project",
      "default rules",
      "all environments",
      "preferred environment",
      "approval",
      "require reviews",
      "code references",
      "code refs",
      "GitHub",
      "GitLab",
      "branches",
    ],
    tab: "feature",
    tabLabel: "Feature Settings",
  },
  {
    id: "metric-settings",
    label: "Metric Settings",
    keywords: [
      "metric",
      "historical data",
      "analysis days",
      "metric analysis",
      "minimum sample size",
      "minimum metric total",
      "maximum percentage change",
      "minimum percentage change",
      "target MDE",
      "minimum detectable effect",
      "currency",
      "USD",
      "display currency",
      "fact metrics",
      "legacy metrics",
      "metric slices",
      "slice levels",
    ],
    tab: "metrics",
    tabLabel: "Metrics & Data",
  },
  {
    id: "datasource-settings",
    label: "Data Source Settings",
    keywords: [
      "data source",
      "datasource",
      "default data source",
      "test query",
      "lookback",
      "query days",
    ],
    tab: "metrics",
    tabLabel: "Metrics & Data",
  },
  {
    id: "northstar-settings",
    label: "North Star Metrics",
    keywords: [
      "north star",
      "northstar",
      "goal metric",
      "home page",
      "focused metrics",
    ],
    tab: "metrics",
    tabLabel: "Metrics & Data",
  },
  {
    id: "sdk-configuration",
    label: "Saved Group Settings",
    keywords: ["saved group", "SDK", "ID list", "size limit", "configuration"],
    tab: "sdk",
    tabLabel: "SDK Configuration",
  },
  {
    id: "import-export",
    label: "Import & Export",
    keywords: [
      "import",
      "export",
      "config.yml",
      "yaml",
      "migrate",
      "backup",
      "restore",
    ],
    tab: "import",
    tabLabel: "Import & Export",
  },
  {
    id: "custom-markdown",
    label: "Custom Markdown",
    keywords: [
      "custom markdown",
      "markdown",
      "customization",
      "feature list",
      "experiment list",
    ],
    tab: "custom",
    tabLabel: "Custom Markdown",
  },
  {
    id: "ai-settings",
    label: "AI Settings",
    keywords: [
      "AI",
      "artificial intelligence",
      "GPT",
      "Claude",
      "Grok",
      "Gemini",
      "Mistral",
      "model",
      "embedding",
      "OpenAI",
      "Anthropic",
      "prompt",
      "experiment analysis prompt",
      "hypothesis format",
      "metric description",
      "text to SQL",
      "generate SQL",
      "semantic search",
      "similarity",
      "regenerate",
    ],
    tab: "ai",
    tabLabel: "AI Settings",
  },
];
