{{- if .Values.mongodb.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.secretName }}
  labels:
    {{- include "growthbook-chart.labels" . | nindent 4 }}
type: Opaque
data:
  myMongoUriKey: "bW9uZ29kYjovL3Jvb3Q6cGFzc3dvcmRAZ3Jvd3RoYm9vay1tb25nb2RiOjI3MDE3Lwo="
{{- end -}}