[libdefaults]
    default_realm = TEST.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false
    dns_canonicalize_hostname = false
    default_rcache_name = FILE:/tmp/krb5rcache

[realms]
    TEST.LOCAL = {
        kdc = kdc.docker.internal
        admin_server = kdc.docker.internal
    }

[domain_realm]
    .docker.internal = TEST.LOCAL
    docker.internal = TEST.LOCAL
