import { FeatureApiResponse } from "@growthbook/growthbook";

/**
 * Pure helpers for the fetch-gb-payload script. Kept side-effect free so the
 * validation and code generation are unit-testable.
 */

// Validate + normalize a raw CDN features response into the shape we bundle.
// `status` is a transport detail and dropped; encrypted* fields are dropped
// (a bundled encrypted payload would be useless without the decryption key).
// Feature keys are sorted so regenerated snapshots produce stable diffs.
export function sanitizePayload(raw: unknown): FeatureApiResponse {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error("GrowthBook payload is not an object");
  }
  const obj = raw as Record<string, unknown>;
  const features = obj.features;
  if (!features || typeof features !== "object" || Array.isArray(features)) {
    throw new Error("GrowthBook payload has no features object");
  }
  const keys = Object.keys(features);
  if (keys.length === 0) {
    throw new Error(
      "GrowthBook payload has zero features — refusing to bundle an empty snapshot",
    );
  }

  const sortedFeatures: Record<string, unknown> = {};
  keys.sort().forEach((k) => {
    sortedFeatures[k] = (features as Record<string, unknown>)[k];
  });

  const out: Record<string, unknown> = { features: sortedFeatures };
  if (typeof obj.dateUpdated === "string") {
    out.dateUpdated = obj.dateUpdated;
  }
  if (
    obj.savedGroups &&
    typeof obj.savedGroups === "object" &&
    !Array.isArray(obj.savedGroups)
  ) {
    out.savedGroups = obj.savedGroups;
  }
  return out as FeatureApiResponse;
}

// TS module wrapping the bundled snapshot. Formatting is applied by the
// caller (prettier), so this only needs to be syntactically valid.
export function buildDefaultPayloadModule(payload: FeatureApiResponse): string {
  return [
    "/**",
    " * GrowthBook SDK payload snapshot — the back-end client's offline default.",
    " *",
    " * AUTO-GENERATED by `pnpm --filter back-end fetch-gb-payload`.",
    " * DO NOT EDIT manually — refreshed by the gb-payload-sync workflow.",
    " *",
    ` * Source: cdn.growthbook.io features endpoint · dateUpdated ${
      payload.dateUpdated || "unknown"
    }`,
    " */",
    'import { FeatureApiResponse } from "@growthbook/growthbook";',
    "",
    `export const GB_DEFAULT_PAYLOAD: FeatureApiResponse = ${JSON.stringify(
      payload,
      null,
      2,
    )};`,
    "",
  ].join("\n");
}

export type GbFeatureListItem = {
  id: string;
  valueType?: string;
  archived?: boolean;
};

const VALUE_TYPE_TO_TS: Record<string, string> = {
  boolean: "boolean",
  string: "string",
  number: "number",
  json: "Record<string, unknown>",
};

// Keys that are valid bare TS identifiers don't need quoting.
const BARE_KEY = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

// Generate the AppFeatures type module from the account's feature list.
// `extras` declares keys the codebase references before they exist in the
// account (e.g. a flag that ships ahead of its creation); an extra is only
// emitted when the account doesn't already have the key.
export function buildAppFeaturesModule(
  features: GbFeatureListItem[],
  extras: Record<string, string> = {},
): string {
  const entries = new Map<string, string>();
  features
    .filter((f) => !f.archived && f.id)
    .forEach((f) => {
      entries.set(f.id, VALUE_TYPE_TO_TS[f.valueType || ""] || "unknown");
    });
  Object.entries(extras).forEach(([id, tsType]) => {
    if (!entries.has(id)) entries.set(id, tsType);
  });
  if (entries.size === 0) {
    throw new Error(
      "No features returned from the GrowthBook API — refusing to generate an empty AppFeatures type",
    );
  }

  const lines = [...entries.keys()].sort().map((id) => {
    const key = BARE_KEY.test(id) ? id : JSON.stringify(id);
    return `  ${key}: ${entries.get(id)};`;
  });

  return [
    "/**",
    " * GrowthBook Features TypeScript Typings",
    " *",
    " * AUTO-GENERATED by `pnpm --filter back-end fetch-gb-payload` from the",
    " * GrowthBook REST API (kept in sync by the gb-payload-sync workflow).",
    " *",
    " * DO NOT EDIT this file manually.",
    " */",
    "export type AppFeatures = {",
    ...lines,
    "};",
    "",
  ].join("\n");
}
