const BRAND_NAMES: Record<string, string> = {
  amex: "American Express",
  diners: "Diners Club",
  discover: "Discover",
  eftpos_au: "Eftpos Australia",
  jcb: "JCB",
  mastercard: "Mastercard",
  unionpay: "UnionPay",
  visa: "Visa",
  us_bank_account: "US Bank Account",
  apple_pay: "Apple Pay",
  google_pay: "Google Pay",
  link: "Link by Stripe",
  unknown: "Unknown Card Brand",
  acss_debit: "ACSS Debit",
  affirm: "Affirm",
  afterpay_clearpay: "Afterpay Clearpay",
  alipay: "Alipay",
  au_becs_debit: "AU BECS Debit",
  bacs_debit: "BACS Debit",
  bancontact: "Bancontact",
  blik: "BLIK",
  boleto: "Boleto",
  card: "Card",
  card_present: "Card Present",
  cashapp: "Cash App",
  customer_balance: "Customer Balance",
  eps: "EPS",
  fpx: "FPX",
  giropay: "Giropay",
  grabpay: "GrabPay",
  ideal: "iDEAL",
  interac_present: "Interac Present",
  klarna: "Klarna",
  konbini: "Konbini",
  oxxo: "OXXO",
  p24: "P24",
  paynow: "PayNow",
  paypal: "PayPal",
  pix: "Pix",
  promptpay: "PromptPay",
  sepa_debit: "SEPA Debit",
  sofort: "Sofort",
  wechat_pay: "WeChat Pay",
  zip: "Zip",
};

export function formatBrandName(name: string): string {
  return BRAND_NAMES[name] || name; // Fallback to the original name if not found
}
