const userJourneyData = [
  { step1: "Session Start", step2: "*", step3: "*", unit_count: 44319, avg_secs_to_step2: 0, avg_secs_step2_to_3: 0 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /features/[fid]", unit_count: 12870, avg_secs_to_step2: 37.86, avg_secs_step2_to_3: 42.75 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /experiment/[eid]", unit_count: 6531, avg_secs_to_step2: 56.67, avg_secs_step2_to_3: 32.61 },
  { step1: "Session Start", step2: "Page View: /features", step3: null, unit_count: 2092, avg_secs_to_step2: 50.04, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Page View: /features", step3: "Viewed Feature Modal", unit_count: 1961, avg_secs_to_step2: 40.32, avg_secs_step2_to_3: 69.48 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /experiments", unit_count: 1597, avg_secs_to_step2: 52.73, avg_secs_step2_to_3: 48.81 },
  { step1: "Session Start", step2: "Page View: /setup", step3: "Modal Open: setup-growthbook", unit_count: 957, avg_secs_to_step2: 3.62, avg_secs_step2_to_3: 0.19 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /features", unit_count: 895, avg_secs_to_step2: 55.68, avg_secs_step2_to_3: 43.14 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Feature Environment Toggle", unit_count: 797, avg_secs_to_step2: 30.31, avg_secs_step2_to_3: 100.94 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /features", unit_count: 711, avg_secs_to_step2: 31.74, avg_secs_step2_to_3: 459.51 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: null, unit_count: 676, avg_secs_to_step2: 104.98, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Modal Open: setup-growthbook", step3: "Page View: /setup", unit_count: 526, avg_secs_to_step2: 1.61, avg_secs_step2_to_3: 0 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: null, unit_count: 469, avg_secs_to_step2: 83.17, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Experiment Snapshot: create", unit_count: 431, avg_secs_to_step2: 50.73, avg_secs_step2_to_3: 62.42 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Page View: /features", unit_count: 414, avg_secs_to_step2: 72.76, avg_secs_step2_to_3: 137.63 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Page View: /features/[fid]", unit_count: 406, avg_secs_to_step2: 79.38, avg_secs_step2_to_3: 351.16 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: null, unit_count: 388, avg_secs_to_step2: 149.94, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Modal Open: edit-force-value-rule", unit_count: 348, avg_secs_to_step2: 47.85, avg_secs_step2_to_3: 128.66 },
  { step1: "Session Start", step2: "Page View: /sdks", step3: "Page View: /sdks/[sdkid]", unit_count: 287, avg_secs_to_step2: 64.43, avg_secs_step2_to_3: 22.08 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Page View: /experiments", unit_count: 257, avg_secs_to_step2: 138.56, avg_secs_step2_to_3: 165.33 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Modal Open: add-new-experiment", unit_count: 251, avg_secs_to_step2: 149.79, avg_secs_step2_to_3: 57.95 },
  { step1: "Session Start", step2: "Page View: /settings/team", step3: "Team Member Invited", unit_count: 248, avg_secs_to_step2: 60.83, avg_secs_step2_to_3: 84.05 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Page View: /experiment/[eid]", unit_count: 240, avg_secs_to_step2: 69.18, avg_secs_step2_to_3: 359.16 },
  { step1: "Session Start", step2: "Page View: /settings/team", step3: null, unit_count: 209, avg_secs_to_step2: 46.8, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Session Start", step3: "Page View: /features", unit_count: 206, avg_secs_to_step2: 0, avg_secs_step2_to_3: 1.12 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Viewed Rule Modal", unit_count: 201, avg_secs_to_step2: 64.79, avg_secs_step2_to_3: 102.71 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Feature Environment Toggle", unit_count: 195, avg_secs_to_step2: 48.01, avg_secs_step2_to_3: 117.56 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /sdks", unit_count: 191, avg_secs_to_step2: 26.9, avg_secs_step2_to_3: 92.63 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /experiments", unit_count: 174, avg_secs_to_step2: 52.56, avg_secs_step2_to_3: 332.26 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /settings/team", unit_count: 168, avg_secs_to_step2: 35.66, avg_secs_step2_to_3: 45.29 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Open health tab", unit_count: 153, avg_secs_to_step2: 39.33, avg_secs_step2_to_3: 45.73 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Page View: /features", unit_count: 140, avg_secs_to_step2: 41.29, avg_secs_step2_to_3: 74.72 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Page View: /features/[fid]", unit_count: 134, avg_secs_to_step2: 70.18, avg_secs_step2_to_3: 82.86 },
  { step1: "Session Start", step2: "Feature Created", step3: "Page View: /features/[fid]", unit_count: 134, avg_secs_to_step2: 195.91, avg_secs_step2_to_3: 0.1 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /bandits", unit_count: 115, avg_secs_to_step2: 82.72, avg_secs_step2_to_3: 10.42 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /saved-groups", unit_count: 93, avg_secs_to_step2: 12.16, avg_secs_step2_to_3: 33.53 },
  { step1: "Session Start", step2: "Page View: /datasources", step3: "Page View: /datasources/[did]", unit_count: 93, avg_secs_to_step2: 46.68, avg_secs_step2_to_3: 3.52 },
  { step1: "Session Start", step2: "Page View: /getstarted", step3: "Page View: /experiments", unit_count: 91, avg_secs_to_step2: 2.73, avg_secs_step2_to_3: 38.09 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Page View: /experiments", unit_count: 90, avg_secs_to_step2: 93.47, avg_secs_step2_to_3: 118.9 },
  { step1: "Session Start", step2: "Page View: /getstarted", step3: "Page View: /getstarted", unit_count: 84, avg_secs_to_step2: 6.36, avg_secs_step2_to_3: 302.75 },
  { step1: "Session Start", step2: "Page View: /settings/billing", step3: null, unit_count: 82, avg_secs_to_step2: 32.65, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Page View: /metrics", step3: "Page View: /fact-metrics/[fmid]", unit_count: 80, avg_secs_to_step2: 64.66, avg_secs_step2_to_3: 40.83 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /metrics", unit_count: 79, avg_secs_to_step2: 41.73, avg_secs_step2_to_3: 14.59 },
  { step1: "Session Start", step2: "Page View: /getstarted", step3: null, unit_count: 73, avg_secs_to_step2: 2.48, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Page View: /saved-groups", step3: "Page View: /saved-groups/[sgid]", unit_count: 69, avg_secs_to_step2: 63.55, avg_secs_step2_to_3: 24.96 },
  { step1: "Session Start", step2: "Page View: /getstarted", step3: "Page View: /features", unit_count: 68, avg_secs_to_step2: 2.32, avg_secs_step2_to_3: 21.31 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Modal Open: make-changes", unit_count: 67, avg_secs_to_step2: 72.6, avg_secs_step2_to_3: 37.51 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Feature Created", unit_count: 66, avg_secs_to_step2: 53.15, avg_secs_step2_to_3: 116.97 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Modal Open: edit-percentage-rollout-rule", unit_count: 65, avg_secs_to_step2: 39.71, avg_secs_step2_to_3: 49.43 },
  { step1: "Session Start", step2: "Page View: /product-analytics/dashboards", step3: "Page View: /experiments", unit_count: 59, avg_secs_to_step2: 30.02, avg_secs_step2_to_3: 3.49 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Page View: /experiment/[eid]", unit_count: 58, avg_secs_to_step2: 71.79, avg_secs_step2_to_3: 165.4 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /metrics", unit_count: 57, avg_secs_to_step2: 28.79, avg_secs_step2_to_3: 58.58 },
  { step1: "Session Start", step2: "Page View: /fact-tables", step3: "Page View: /fact-tables/[ftid]", unit_count: 57, avg_secs_to_step2: 83.05, avg_secs_step2_to_3: 13.32 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /product-analytics/dashboards", unit_count: 55, avg_secs_to_step2: 64.65, avg_secs_step2_to_3: 30.35 },
  { step1: "Session Start", step2: "Page View: /account/personal-access-tokens", step3: "Create API Key", unit_count: 54, avg_secs_to_step2: 149.8, avg_secs_step2_to_3: 23.59 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Feature Created", unit_count: 54, avg_secs_to_step2: 223.72, avg_secs_step2_to_3: 38.22 },
  { step1: "Session Start", step2: "Page View: /settings/team", step3: "Page View: /settings/team", unit_count: 49, avg_secs_to_step2: 46.61, avg_secs_step2_to_3: 677.33 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Modal Open: metric-details", unit_count: 48, avg_secs_to_step2: 7.52, avg_secs_step2_to_3: 121.81 },
  { step1: "Session Start", step2: "Page View: /projects", step3: "Page View: /settings/tags", unit_count: 47, avg_secs_to_step2: 2.04, avg_secs_step2_to_3: 3.89 },
  { step1: "Session Start", step2: "Page View: /metrics", step3: "Page View: /metric/[mid]", unit_count: 45, avg_secs_to_step2: 8.36, avg_secs_step2_to_3: 17.22 },
  { step1: "Session Start", step2: "Page View: /projects", step3: "Page View: /project/[pid]", unit_count: 43, avg_secs_to_step2: 65.81, avg_secs_step2_to_3: 97.14 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Page View: /saved-groups/[sgid]", unit_count: 42, avg_secs_to_step2: 27.19, avg_secs_step2_to_3: 120.79 },
  { step1: "Session Start", step2: "Page View: /sdks", step3: "View SDK Connection Form", unit_count: 42, avg_secs_to_step2: 19.5, avg_secs_step2_to_3: 109.67 },
  { step1: "Session Start", step2: "Page View: /metrics", step3: "Page View: /fact-tables", unit_count: 40, avg_secs_to_step2: 49.2, avg_secs_step2_to_3: 5.63 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Modal Open: stop-experiment-form", unit_count: 39, avg_secs_to_step2: 19, avg_secs_step2_to_3: 48.54 },
  { step1: "Session Start", step2: "Modal Open: setup-growthbook", step3: "Page View: /getstarted", unit_count: 38, avg_secs_to_step2: 0.05, avg_secs_step2_to_3: 0 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Page View: /report/[rid]", unit_count: 38, avg_secs_to_step2: 20.32, avg_secs_step2_to_3: 17.11 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Disable Feature Rule", unit_count: 38, avg_secs_to_step2: 72.34, avg_secs_step2_to_3: 126.53 },
  { step1: "Session Start", step2: "Page View: /saved-groups", step3: "Modal Open: saved-group-form", unit_count: 37, avg_secs_to_step2: 13.59, avg_secs_step2_to_3: 8.97 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /features/[fid]", unit_count: 37, avg_secs_to_step2: 29.08, avg_secs_step2_to_3: 415.95 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Session Start", unit_count: 35, avg_secs_to_step2: 0.09, avg_secs_step2_to_3: 340.69 },
  { step1: "Session Start", step2: "Page View: /settings", step3: "Page View: /settings/team", unit_count: 34, avg_secs_to_step2: 136.44, avg_secs_step2_to_3: 79.74 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Tooltip Open: premium-tooltip: prerequisites", unit_count: 32, avg_secs_to_step2: 54.13, avg_secs_step2_to_3: 34.88 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Delete Feature Rule", unit_count: 32, avg_secs_to_step2: 16, avg_secs_step2_to_3: 72.91 },
  { step1: "Session Start", step2: "Page View: /getstarted", step3: "Page View: /sdks", unit_count: 32, avg_secs_to_step2: 1.97, avg_secs_step2_to_3: 22.44 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /sdks", unit_count: 32, avg_secs_to_step2: 103.63, avg_secs_step2_to_3: 206.78 },
  { step1: "Session Start", step2: "Page View: /metrics", step3: "Page View: /experiments", unit_count: 31, avg_secs_to_step2: 39.84, avg_secs_step2_to_3: 76.03 },
  { step1: "Session Start", step2: "Page View: /metrics", step3: "Viewed Create Fact Metric Modal", unit_count: 30, avg_secs_to_step2: 77.77, avg_secs_step2_to_3: 25.7 },
  { step1: "Session Start", step2: "View Upgrade Modal", step3: "Modal Open: upgrade-modal", unit_count: 30, avg_secs_to_step2: 20.13, avg_secs_step2_to_3: 0 },
  { step1: "Session Start", step2: "Page View: /settings/keys", step3: "Create API Key", unit_count: 30, avg_secs_to_step2: 195.1, avg_secs_step2_to_3: 78.6 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /product-analytics/dashboards", unit_count: 29, avg_secs_to_step2: 104.17, avg_secs_step2_to_3: 178.31 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /settings", unit_count: 29, avg_secs_to_step2: 128.55, avg_secs_step2_to_3: 41.79 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /settings/team", unit_count: 29, avg_secs_to_step2: 6.38, avg_secs_step2_to_3: 59.07 },
  { step1: "Session Start", step2: "Page View: /settings/team", step3: "Page View: /features", unit_count: 29, avg_secs_to_step2: 11.1, avg_secs_step2_to_3: 246.28 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Modal Open: edit-feature-info", unit_count: 29, avg_secs_to_step2: 182.31, avg_secs_step2_to_3: 164.17 },
  { step1: "Session Start", step2: "Page View: /account/personal-access-tokens", step3: null, unit_count: 29, avg_secs_to_step2: 19.86, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Page View: /getstarted", step3: "Page View: /settings/team", unit_count: 29, avg_secs_to_step2: 110.59, avg_secs_step2_to_3: 94 },
  { step1: "Session Start", step2: "Page View: /getstarted", step3: "Create Sample Project", unit_count: 28, avg_secs_to_step2: 34.96, avg_secs_step2_to_3: 29.21 },
  { step1: "Session Start", step2: "Page View: /attributes", step3: null, unit_count: 28, avg_secs_to_step2: 222.71, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Modal Open: edit-variations-form", unit_count: 27, avg_secs_to_step2: 8.96, avg_secs_step2_to_3: 141.41 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /experiment/[eid]", unit_count: 27, avg_secs_to_step2: 10.26, avg_secs_step2_to_3: 238.63 },
  { step1: "Session Start", step2: "Page View: /settings/team", step3: "Page View: /experiments", unit_count: 26, avg_secs_to_step2: 36.62, avg_secs_step2_to_3: 626.31 },
  { step1: "Session Start", step2: "Page View: /metrics", step3: "Page View: /datasources", unit_count: 26, avg_secs_to_step2: 36.81, avg_secs_step2_to_3: 14.62 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "edit-metric-form-open", unit_count: 25, avg_secs_to_step2: 163.08, avg_secs_step2_to_3: 203.32 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /attributes", unit_count: 25, avg_secs_to_step2: 13.64, avg_secs_step2_to_3: 98.92 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Modal Open: analysis-form", unit_count: 25, avg_secs_to_step2: 88.2, avg_secs_step2_to_3: 33.88 },
  { step1: "Session Start", step2: "Page View: /product-analytics/dashboards", step3: "Page View: /metrics", unit_count: 24, avg_secs_to_step2: 50.25, avg_secs_step2_to_3: 4.63 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Enable Feature Rule", unit_count: 23, avg_secs_to_step2: 14.48, avg_secs_step2_to_3: 36.78 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /datasources", unit_count: 23, avg_secs_to_step2: 16, avg_secs_step2_to_3: 101 },
  { step1: "Session Start", step2: "Page View: /datasources", step3: "View Datasource Form", unit_count: 23, avg_secs_to_step2: 53.26, avg_secs_step2_to_3: 2.91 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /projects", unit_count: 23, avg_secs_to_step2: 179.39, avg_secs_step2_to_3: 121.87 },
  { step1: "Session Start", step2: "Page View: /metrics", step3: null, unit_count: 22, avg_secs_to_step2: 82.59, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /namespaces", unit_count: 22, avg_secs_to_step2: 15.18, avg_secs_step2_to_3: 13 },
  { step1: "Session Start", step2: "Page View: /settings/keys", step3: "Page View: /account/personal-access-tokens", unit_count: 22, avg_secs_to_step2: 83.77, avg_secs_step2_to_3: 85.09 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Page View: /bandits", unit_count: 22, avg_secs_to_step2: 152.36, avg_secs_step2_to_3: 121.27 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /fact-tables", unit_count: 22, avg_secs_to_step2: 162.23, avg_secs_step2_to_3: 99.77 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /getstarted", unit_count: 21, avg_secs_to_step2: 0.86, avg_secs_step2_to_3: 42.81 },
  { step1: "Session Start", step2: "Page View: /settings/team", step3: "Page View: /settings/billing", unit_count: 20, avg_secs_to_step2: 9.95, avg_secs_step2_to_3: 35.15 },
  { step1: "Session Start", step2: "Page View: /settings/team", step3: "Page View: /settings/team/[tid]", unit_count: 20, avg_secs_to_step2: 75.8, avg_secs_step2_to_3: 49.35 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Modal Open: import-experiment", unit_count: 20, avg_secs_to_step2: 43.6, avg_secs_step2_to_3: 5.25 },
  { step1: "Session Start", step2: "Page View: /settings/billing", step3: "Page View: /settings/billing", unit_count: 19, avg_secs_to_step2: 21.89, avg_secs_step2_to_3: 201.68 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /experiments/templates", unit_count: 19, avg_secs_to_step2: 67, avg_secs_step2_to_3: 16.68 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /datasources", unit_count: 19, avg_secs_to_step2: 6.95, avg_secs_step2_to_3: 42.53 },
  { step1: "Session Start", step2: "Page View: /experiments", step3: "Page View: /holdouts", unit_count: 19, avg_secs_to_step2: 113.26, avg_secs_step2_to_3: 29.58 },
  { step1: "Session Start", step2: "Page View: /settings/tags", step3: "Page View: /settings/customfields", unit_count: 18, avg_secs_to_step2: 50.06, avg_secs_step2_to_3: 2.78 },
  { step1: "Session Start", step2: "Page View: /sdks", step3: null, unit_count: 18, avg_secs_to_step2: 82.78, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Page View: /sdks", step3: "Page View: /attributes", unit_count: 17, avg_secs_to_step2: 26.29, avg_secs_step2_to_3: 28.94 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /settings/customfields", unit_count: 17, avg_secs_to_step2: 8.18, avg_secs_step2_to_3: 183.35 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Modal Open: compare-revisions", unit_count: 17, avg_secs_to_step2: 65.71, avg_secs_step2_to_3: 68.65 },
  { step1: "Session Start", step2: "Page View: /settings/billing", step3: "Edit Payment Method Modal", unit_count: 17, avg_secs_to_step2: 8.47, avg_secs_step2_to_3: 19.29 },
  { step1: "Session Start", step2: "Page View: /product-analytics/dashboards", step3: "Page View: /features", unit_count: 17, avg_secs_to_step2: 123.18, avg_secs_step2_to_3: 42.65 },
  { step1: "Session Start", step2: "Page View: /settings", step3: "Tooltip Open: premium-tooltip: custom-markdown", unit_count: 16, avg_secs_to_step2: 17.94, avg_secs_step2_to_3: 261.25 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /archetypes", unit_count: 16, avg_secs_to_step2: 103.63, avg_secs_step2_to_3: 107.44 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /account/personal-access-tokens", unit_count: 16, avg_secs_to_step2: 73.44, avg_secs_step2_to_3: 245.63 },
  { step1: "Session Start", step2: "Page View: /settings/usage", step3: null, unit_count: 16, avg_secs_to_step2: 25, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Page View: /settings/team", step3: "Page View: /settings", unit_count: 16, avg_secs_to_step2: 15.19, avg_secs_step2_to_3: 83.63 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /environments", unit_count: 16, avg_secs_to_step2: 7.56, avg_secs_step2_to_3: 101 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Page View: /metrics", unit_count: 16, avg_secs_to_step2: 20.06, avg_secs_step2_to_3: 345.06 },
  { step1: "Session Start", step2: "Page View: /sdks", step3: "Page View: /features", unit_count: 16, avg_secs_to_step2: 81.63, avg_secs_step2_to_3: 485.56 },
  { step1: "Session Start", step2: "Page View: /features/[fid]", step3: "Page View: /sdks", unit_count: 15, avg_secs_to_step2: 34.6, avg_secs_step2_to_3: 103.27 },
  { step1: "Session Start", step2: "Page View: /settings/webhooks", step3: "Page View: /settings/webhooks/event/[eventwebhookid]", unit_count: 15, avg_secs_to_step2: 112.87, avg_secs_step2_to_3: 143.27 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Modal Open: async-queries", unit_count: 15, avg_secs_to_step2: 16.47, avg_secs_step2_to_3: 319.87 },
  { step1: "Session Start", step2: "Viewed Feature Modal", step3: "Page View: /features", unit_count: 15, avg_secs_to_step2: 348.87, avg_secs_step2_to_3: 0.47 },
  { step1: "Session Start", step2: "Page View: /experiment/[eid]", step3: "Page View: /sdks", unit_count: 15, avg_secs_to_step2: 28.2, avg_secs_step2_to_3: 337.8 },
  { step1: "Session Start", step2: "Page View: /setup", step3: "Page View: /setup", unit_count: 15, avg_secs_to_step2: 1.4, avg_secs_step2_to_3: 90.47 },
  { step1: "Session Start", step2: "Page View: /attributes", step3: "Page View: /features", unit_count: 15, avg_secs_to_step2: 206.8, avg_secs_step2_to_3: 444.13 },
  { step1: "Session Start", step2: "Page View: /settings/team", step3: "Tooltip Open: premium-tooltip: advanced-permissions", unit_count: 14, avg_secs_to_step2: 24.79, avg_secs_step2_to_3: 65.86 },
  { step1: "Session Start", step2: "Page View: /settings/keys", step3: null, unit_count: 14, avg_secs_to_step2: 45, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Page View: /getstarted", step3: "Page View: /settings", unit_count: 14, avg_secs_to_step2: 3, avg_secs_step2_to_3: 23.57 },
  { step1: "Session Start", step2: "Page View: /settings", step3: null, unit_count: 14, avg_secs_to_step2: 388.79, avg_secs_step2_to_3: null },
  { step1: "Session Start", step2: "Page View: /settings/team", step3: "View Upgrade Modal", unit_count: 14, avg_secs_to_step2: 13.93, avg_secs_step2_to_3: 15.86 },
  { step1: "Session Start", step2: "Page View: /settings/billing", step3: "Page View: /settings/usage", unit_count: 13, avg_secs_to_step2: 75.15, avg_secs_step2_to_3: 14.62 },
  { step1: "Session Start", step2: "Page View: /404", step3: "Page View: /features", unit_count: 13, avg_secs_to_step2: 131.62, avg_secs_step2_to_3: 80.15 },
  { step1: "Session Start", step2: "Modal Open: add-new-experiment", step3: "Create Experiment", unit_count: 13, avg_secs_to_step2: 75.38, avg_secs_step2_to_3: 444.23 },
  { step1: "Session Start", step2: "Page View: /fact-tables", step3: "Viewed Create Fact Table Modal", unit_count: 13, avg_secs_to_step2: 68.92, avg_secs_step2_to_3: 3.08 },
  { step1: "Session Start", step2: "Page View: /settings", step3: "Page View: /projects", unit_count: 13, avg_secs_to_step2: 39.46, avg_secs_step2_to_3: 9.62 },
  { step1: "Session Start", step2: "Page View: /datasources", step3: "Data Source Type Selected", unit_count: 13, avg_secs_to_step2: 203, avg_secs_step2_to_3: 7.62 },
  { step1: "Session Start", step2: "Page View: /settings/keys", step3: "Page View: /sdks", unit_count: 13, avg_secs_to_step2: 27, avg_secs_step2_to_3: 31.62 },
  { step1: "Session Start", step2: "Page View: /features", step3: "Page View: /dashboard", unit_count: 13, avg_secs_to_step2: 5.85, avg_secs_step2_to_3: 14.69 }];