import { Response } from "express";
import { BaseScimRequest } from "back-end/types/scim";

export async function getSchemas(req: BaseScimRequest, res: Response) {
  return res.status(200).json({
    schemas: ["urn:ietf:params:scim:api:messages:2.0:ListResponse"],
    totalResults: 2,
    itemsPerPage: 2,
    startIndex: 1,
    Resources: [
      {
        id: "urn:ietf:params:scim:schemas:core:2.0:User",
        name: "User",
        description: "User Account",
        attributes: [
          {
            name: "userName",
            type: "string",
            multiValued: false,
            description:
              "Unique identifier for the User, typically the email address",
            required: true,
            caseExact: false,
            mutability: "readWrite",
            returned: "default",
            uniqueness: "server",
          },
          {
            name: "displayName",
            type: "string",
            multiValued: false,
            description: "The name of the User, suitable for display",
            required: true,
            caseExact: false,
            mutability: "readWrite",
            returned: "default",
            uniqueness: "none",
          },
          {
            name: "active",
            type: "boolean",
            multiValued: false,
            description:
              "A Boolean value indicating the User's administrative status",
            required: false,
            mutability: "readWrite",
            returned: "default",
          },
          {
            name: "externalId",
            type: "string",
            multiValued: false,
            description:
              "A String that is an identifier for the resource as defined by the provisioning client",
            required: false,
            caseExact: true,
            mutability: "readWrite",
            returned: "default",
            uniqueness: "none",
          },
          {
            name: "id",
            type: "string",
            multiValued: false,
            description: "Unique identifier for the SCIM resource",
            required: true,
            caseExact: true,
            mutability: "readOnly",
            returned: "always",
            uniqueness: "server",
          },
          {
            name: "growthbookRole",
            type: "string",
            multiValued: false,
            description: "GrowthBook role identifier for the user",
            required: false,
            caseExact: true,
            mutability: "readWrite",
            returned: "default",
            uniqueness: "none",
          },
        ],
        meta: {
          resourceType: "Schema",
          location:
            "/scim/v2/Schemas/urn:ietf:params:scim:schemas:core:2.0:User",
        },
      },
      {
        id: "urn:ietf:params:scim:schemas:core:2.0:Group",
        name: "Group",
        description: "Group",
        attributes: [
          {
            name: "displayName",
            type: "string",
            multiValued: false,
            description: "A human-readable name for the Group",
            required: true,
            caseExact: false,
            mutability: "readWrite",
            returned: "default",
            uniqueness: "none",
          },
          {
            name: "members",
            type: "complex",
            multiValued: true,
            description: "A list of members of the Group",
            required: false,
            mutability: "readWrite",
            returned: "default",
            subAttributes: [
              {
                name: "value",
                type: "string",
                multiValued: false,
                description: "Identifier of the member of this Group",
                required: true,
                caseExact: false,
                mutability: "immutable",
                returned: "default",
                uniqueness: "none",
              },
              {
                name: "display",
                type: "string",
                multiValued: false,
                description: "A human-readable name for the member",
                required: false,
                caseExact: false,
                mutability: "immutable",
                returned: "default",
                uniqueness: "none",
              },
            ],
          },
          {
            name: "id",
            type: "string",
            multiValued: false,
            description: "Unique identifier for the SCIM resource",
            required: true,
            caseExact: true,
            mutability: "readOnly",
            returned: "always",
            uniqueness: "server",
          },
          {
            name: "growthbookRole",
            type: "string",
            multiValued: false,
            description: "GrowthBook role identifier for the group",
            required: false,
            caseExact: true,
            mutability: "readWrite",
            returned: "default",
            uniqueness: "none",
          },
        ],
        meta: {
          resourceType: "Schema",
          location:
            "/scim/v2/Schemas/urn:ietf:params:scim:schemas:core:2.0:Group",
        },
      },
    ],
  });
}
