summary: Deletes a single environment
parameters:
  - $ref: "../parameters.yaml#/id"
requestBody:
  required: false
  content:
    application/json:
      schema:
        type: object
        properties:
          removeAssociatedFeatureRules:
            type: boolean
            description: "Whether to also remove rules from features for the environment to be deleted"
tags:
  - environments
operationId: deleteEnvironment
x-codeSamples:
  - lang: "cURL"
    source: |
      curl -X DELETE https://api.growthbook.io/api/v1/enviromnents/env-id \
        -u secret_abc123DEF456:
responses:
  "200":
    content:
      application/json:
        schema:
          type: object
          required:
            - deletedId
          properties:
            deletedId:
              type: string
