summary: Get organization settings
tags:
  - settings
operationId: getSettings
x-codeSamples:
  - lang: "cURL"
    source: |
      curl https://api.growthbook.io/api/v1/settings \
        -u secret_abc123DEF456:
responses:
  "200":
    content:
      application/json:
        schema:
          type: object
          required:
            - settings
          properties:
            settings:
              $ref: "../schemas/Settings.yaml"
