summary: Get the organization's environments
tags:
  - environments
operationId: listEnvironments
x-codeSamples:
  - lang: 'cURL'
    source: |
      curl https://api.growthbook.io/api/v1/environments \
        -u secret_abc123DEF456:
responses:
  "200":
    content:
      application/json:
        schema:
          allOf:
            - type: object
              required:
                - environments
              properties:
                environments:
                  type: array
                  items:
                    $ref: "../schemas/Environment.yaml"
