import { getUserPermissions } from "../src/util/organization.util";
import { OrganizationInterface } from "../types/organization";
import { findTeamById } from "../src/models/TeamModel";

jest.mock("../src/models/TeamModel", () => ({
  findTeamById: jest.fn(),
}));

describe("Build user permissions", () => {
  const testOrg: OrganizationInterface = {
    id: "org_sktwi1id9l7z9xkjb",
    name: "Test Org",
    ownerEmail: "test@test.com",
    url: "https://test.com",
    dateCreated: new Date(),
    invites: [],
    members: [
      {
        id: "basic_readonly_user",
        role: "readonly",
        dateCreated: new Date(),
        limitAccessByEnvironment: false,
        environments: [],
        projectRoles: [],
        teams: [],
      },
      {
        id: "basic_collaborator_user",
        role: "collaborator",
        dateCreated: new Date(),
        limitAccessByEnvironment: false,
        environments: [],
        projectRoles: [],
        teams: [],
      },
      {
        id: "basic_engineer_user",
        role: "engineer",
        dateCreated: new Date(),
        limitAccessByEnvironment: false,
        environments: [],
        projectRoles: [],
        teams: [],
      },
      {
        id: "basic_engineer_env_limited_user",
        role: "engineer",
        dateCreated: new Date(),
        limitAccessByEnvironment: true,
        environments: ["staging", "development"],
        projectRoles: [],
        teams: [],
      },
      {
        id: "basic_analyst_user",
        role: "analyst",
        dateCreated: new Date(),
        limitAccessByEnvironment: false,
        environments: [],
        projectRoles: [],
        teams: [],
      },
      {
        id: "basic_experimenter_user",
        role: "experimenter",
        dateCreated: new Date(),
        limitAccessByEnvironment: false,
        environments: [],
        projectRoles: [],
        teams: [],
      },
      {
        id: "basic_admin_user",
        role: "admin",
        dateCreated: new Date(),
        limitAccessByEnvironment: false,
        environments: [],
        projectRoles: [],
        teams: [],
      },
      {
        id: "slightly_advanced_readonly_user",
        role: "readonly",
        dateCreated: new Date(),
        limitAccessByEnvironment: false,
        environments: [],
        projectRoles: [
          {
            project: "prj_exl5jr5dl4rbw856",
            role: "engineer",
            limitAccessByEnvironment: false,
            environments: [],
          },
        ],
        teams: [],
      },
      {
        id: "slightly_advanced_readonly_user_2",
        role: "readonly",
        dateCreated: new Date(),
        limitAccessByEnvironment: false,
        environments: [],
        projectRoles: [
          {
            project: "prj_exl5jr5dl4rbw856",
            role: "engineer",
            limitAccessByEnvironment: false,
            environments: [],
          },
          {
            project: "prj_exl5jr5dl4rbw123",
            role: "analyst",
            limitAccessByEnvironment: false,
            environments: [],
          },
        ],
        teams: [],
      },
      {
        id: "slightly_advanced_engineer_user",
        role: "engineer",
        dateCreated: new Date(),
        limitAccessByEnvironment: true,
        environments: ["staging", "development"],
        projectRoles: [
          {
            project: "prj_exl5jr5dl4rbw856",
            role: "engineer",
            limitAccessByEnvironment: true,
            environments: ["production"],
          },
          {
            project: "prj_exl5jr5dl4rbw123",
            role: "analyst",
            limitAccessByEnvironment: false,
            environments: [],
          },
        ],
        teams: [],
      },
      {
        id: "advanced_readonly_user",
        role: "readonly",
        dateCreated: new Date(),
        limitAccessByEnvironment: false,
        environments: [],
        projectRoles: [
          {
            project: "prj_exl5jr5dl4rbw856",
            role: "engineer",
            limitAccessByEnvironment: true,
            environments: ["production"],
          },
          {
            project: "prj_exl5jr5dl4rbw123",
            role: "analyst",
            limitAccessByEnvironment: false,
            environments: [],
          },
        ],
        teams: ["team_collaborators"],
      },
    ],
  };
  // Basic user permissions - no project-level permissions or teams
  it("should handle a basic readonly user with no project-level permissions or teams correctly", async () => {
    const userPermissions = await getUserPermissions(
      "basic_readonly_user",
      testOrg
    );
    expect(userPermissions).toEqual({
      global: {
        environments: [],
        limitAccessByEnvironment: false,
        permissions: {
          createPresentations: false,
          createDimensions: false,
          createSegments: false,
          organizationSettings: false,
          superDelete: false,
          manageTeam: false,
          manageTags: false,
          manageApiKeys: false,
          manageIntegrations: false,
          manageWebhooks: false,
          manageBilling: false,
          manageNorthStarMetric: false,
          manageTargetingAttributes: false,
          manageNamespaces: false,
          manageSavedGroups: false,
          viewEvents: false,
          addComments: false,
          createFeatureDrafts: false,
          manageFeatures: false,
          manageProjects: false,
          createAnalyses: false,
          createIdeas: false,
          createMetrics: false,
          createDatasources: false,
          editDatasourceSettings: false,
          runQueries: false,
          publishFeatures: false,
          manageEnvironments: false,
          runExperiments: false,
        },
      },
      projects: {},
    });
  });

  it("should handle a basic collaborator user with no project-level permissions or teams correctly", async () => {
    const userPermissions = await getUserPermissions(
      "basic_collaborator_user",
      testOrg
    );
    expect(userPermissions).toEqual({
      global: {
        environments: [],
        limitAccessByEnvironment: false,
        permissions: {
          createPresentations: true,
          createDimensions: false,
          createSegments: false,
          organizationSettings: false,
          superDelete: false,
          manageTeam: false,
          manageTags: false,
          manageApiKeys: false,
          manageIntegrations: false,
          manageWebhooks: false,
          manageBilling: false,
          manageNorthStarMetric: false,
          manageTargetingAttributes: false,
          manageNamespaces: false,
          manageSavedGroups: false,
          viewEvents: false,
          addComments: true,
          createFeatureDrafts: false,
          manageFeatures: false,
          manageProjects: false,
          createAnalyses: false,
          createIdeas: true,
          createMetrics: false,
          createDatasources: false,
          editDatasourceSettings: false,
          runQueries: false,
          publishFeatures: false,
          manageEnvironments: false,
          runExperiments: false,
        },
      },
      projects: {},
    });
  });

  it("should handle a basic engineer user with no project-level permissions or teams correctly", async () => {
    const userPermissions = await getUserPermissions(
      "basic_engineer_user",
      testOrg
    );
    expect(userPermissions).toEqual({
      global: {
        environments: [],
        limitAccessByEnvironment: false,
        permissions: {
          createPresentations: true,
          createDimensions: false,
          createSegments: false,
          organizationSettings: false,
          superDelete: false,
          manageTeam: false,
          manageTags: true,
          manageApiKeys: false,
          manageIntegrations: false,
          manageWebhooks: false,
          manageBilling: false,
          manageNorthStarMetric: false,
          manageTargetingAttributes: true,
          manageNamespaces: true,
          manageSavedGroups: true,
          viewEvents: false,
          addComments: true,
          createFeatureDrafts: true,
          manageFeatures: true,
          manageProjects: false,
          createAnalyses: false,
          createIdeas: true,
          createMetrics: false,
          createDatasources: false,
          editDatasourceSettings: false,
          runQueries: false,
          publishFeatures: true,
          manageEnvironments: true,
          runExperiments: true,
        },
      },
      projects: {},
    });
  });

  it("should handle a basic analyst user with no project-level permissions or teams correctly", async () => {
    const userPermissions = await getUserPermissions(
      "basic_analyst_user",
      testOrg
    );
    expect(userPermissions).toEqual({
      global: {
        environments: [],
        limitAccessByEnvironment: false,
        permissions: {
          createPresentations: true,
          createDimensions: true,
          createSegments: false,
          organizationSettings: false,
          superDelete: false,
          manageTeam: false,
          manageTags: true,
          manageApiKeys: false,
          manageIntegrations: false,
          manageWebhooks: false,
          manageBilling: false,
          manageNorthStarMetric: false,
          manageTargetingAttributes: false,
          manageNamespaces: false,
          manageSavedGroups: false,
          viewEvents: false,
          addComments: true,
          createFeatureDrafts: false,
          manageFeatures: false,
          manageProjects: false,
          createAnalyses: true,
          createIdeas: true,
          createMetrics: true,
          createDatasources: false,
          editDatasourceSettings: true,
          runQueries: true,
          publishFeatures: false,
          manageEnvironments: false,
          runExperiments: false,
        },
      },
      projects: {},
    });
  });

  it("should handle a basic experimenter user with no project-level permissions or teams correctly", async () => {
    const userPermissions = await getUserPermissions(
      "basic_experimenter_user",
      testOrg
    );
    expect(userPermissions).toEqual({
      global: {
        environments: [],
        limitAccessByEnvironment: false,
        permissions: {
          createPresentations: true,
          createDimensions: true,
          createSegments: true,
          organizationSettings: false,
          superDelete: false,
          manageTeam: false,
          manageTags: true,
          manageApiKeys: false,
          manageIntegrations: false,
          manageWebhooks: false,
          manageBilling: false,
          manageNorthStarMetric: false,
          manageTargetingAttributes: true,
          manageNamespaces: true,
          manageSavedGroups: true,
          viewEvents: false,
          addComments: true,
          createFeatureDrafts: true,
          manageFeatures: true,
          manageProjects: false,
          createAnalyses: true,
          createIdeas: true,
          createMetrics: true,
          createDatasources: false,
          editDatasourceSettings: true,
          runQueries: true,
          publishFeatures: true,
          manageEnvironments: true,
          runExperiments: true,
        },
      },
      projects: {},
    });
  });

  it("should handle an admin user with no project-level permissions or teams correctly", async () => {
    const userPermissions = await getUserPermissions(
      "basic_admin_user",
      testOrg
    );
    expect(userPermissions).toEqual({
      global: {
        environments: [],
        limitAccessByEnvironment: false,
        permissions: {
          createPresentations: true,
          createDimensions: true,
          createSegments: true,
          organizationSettings: true,
          superDelete: true,
          manageTeam: true,
          manageTags: true,
          manageApiKeys: true,
          manageIntegrations: true,
          manageWebhooks: true,
          manageBilling: true,
          manageNorthStarMetric: true,
          manageTargetingAttributes: true,
          manageNamespaces: true,
          manageSavedGroups: true,
          viewEvents: true,
          addComments: true,
          createFeatureDrafts: true,
          manageFeatures: true,
          manageProjects: true,
          createAnalyses: true,
          createIdeas: true,
          createMetrics: true,
          createDatasources: true,
          editDatasourceSettings: true,
          runQueries: true,
          publishFeatures: true,
          manageEnvironments: true,
          runExperiments: true,
        },
      },
      projects: {},
    });
  });
  // Slightly advanced user permissions - project-level permissions, but no teams
  it("should handle a readonly user with a single engineer project-level permission and no teams correctly", async () => {
    const userPermissions = await getUserPermissions(
      "slightly_advanced_readonly_user",
      testOrg
    );

    expect(userPermissions).toEqual({
      global: {
        environments: [],
        limitAccessByEnvironment: false,
        permissions: {
          createPresentations: false,
          createDimensions: false,
          createSegments: false,
          organizationSettings: false,
          superDelete: false,
          manageTeam: false,
          manageTags: false,
          manageApiKeys: false,
          manageIntegrations: false,
          manageWebhooks: false,
          manageBilling: false,
          manageNorthStarMetric: false,
          manageTargetingAttributes: false,
          manageNamespaces: false,
          manageSavedGroups: false,
          viewEvents: false,
          addComments: false,
          createFeatureDrafts: false,
          manageFeatures: false,
          manageProjects: false,
          createAnalyses: false,
          createIdeas: false,
          createMetrics: false,
          createDatasources: false,
          editDatasourceSettings: false,
          runQueries: false,
          publishFeatures: false,
          manageEnvironments: false,
          runExperiments: false,
        },
      },
      projects: {
        prj_exl5jr5dl4rbw856: {
          environments: [],
          limitAccessByEnvironment: false,
          permissions: {
            createPresentations: true,
            createDimensions: false,
            createSegments: false,
            organizationSettings: false,
            superDelete: false,
            manageTeam: false,
            manageTags: true,
            manageApiKeys: false,
            manageIntegrations: false,
            manageWebhooks: false,
            manageBilling: false,
            manageNorthStarMetric: false,
            manageTargetingAttributes: true,
            manageNamespaces: true,
            manageSavedGroups: true,
            viewEvents: false,
            addComments: true,
            createFeatureDrafts: true,
            manageFeatures: true,
            manageProjects: false,
            createAnalyses: false,
            createIdeas: true,
            createMetrics: false,
            createDatasources: false,
            editDatasourceSettings: false,
            runQueries: false,
            publishFeatures: true,
            manageEnvironments: true,
            runExperiments: true,
          },
        },
      },
    });
  });

  it("should handle a readonly user with  multiple project-level permissions and no teams correctly", async () => {
    const userPermissions = await getUserPermissions(
      "slightly_advanced_readonly_user_2",
      testOrg
    );

    expect(userPermissions).toEqual({
      global: {
        environments: [],
        limitAccessByEnvironment: false,
        permissions: {
          createPresentations: false,
          createDimensions: false,
          createSegments: false,
          organizationSettings: false,
          superDelete: false,
          manageTeam: false,
          manageTags: false,
          manageApiKeys: false,
          manageIntegrations: false,
          manageWebhooks: false,
          manageBilling: false,
          manageNorthStarMetric: false,
          manageTargetingAttributes: false,
          manageNamespaces: false,
          manageSavedGroups: false,
          viewEvents: false,
          addComments: false,
          createFeatureDrafts: false,
          manageFeatures: false,
          manageProjects: false,
          createAnalyses: false,
          createIdeas: false,
          createMetrics: false,
          createDatasources: false,
          editDatasourceSettings: false,
          runQueries: false,
          publishFeatures: false,
          manageEnvironments: false,
          runExperiments: false,
        },
      },
      projects: {
        prj_exl5jr5dl4rbw856: {
          environments: [],
          limitAccessByEnvironment: false,
          permissions: {
            createPresentations: true,
            createDimensions: false,
            createSegments: false,
            organizationSettings: false,
            superDelete: false,
            manageTeam: false,
            manageTags: true,
            manageApiKeys: false,
            manageIntegrations: false,
            manageWebhooks: false,
            manageBilling: false,
            manageNorthStarMetric: false,
            manageTargetingAttributes: true,
            manageNamespaces: true,
            manageSavedGroups: true,
            viewEvents: false,
            addComments: true,
            createFeatureDrafts: true,
            manageFeatures: true,
            manageProjects: false,
            createAnalyses: false,
            createIdeas: true,
            createMetrics: false,
            createDatasources: false,
            editDatasourceSettings: false,
            runQueries: false,
            publishFeatures: true,
            manageEnvironments: true,
            runExperiments: true,
          },
        },
        prj_exl5jr5dl4rbw123: {
          environments: [],
          limitAccessByEnvironment: false,
          permissions: {
            createPresentations: true,
            createDimensions: true,
            createSegments: false,
            organizationSettings: false,
            superDelete: false,
            manageTeam: false,
            manageTags: true,
            manageApiKeys: false,
            manageIntegrations: false,
            manageWebhooks: false,
            manageBilling: false,
            manageNorthStarMetric: false,
            manageTargetingAttributes: false,
            manageNamespaces: false,
            manageSavedGroups: false,
            viewEvents: false,
            addComments: true,
            createFeatureDrafts: false,
            manageFeatures: false,
            manageProjects: false,
            createAnalyses: true,
            createIdeas: true,
            createMetrics: true,
            createDatasources: false,
            editDatasourceSettings: true,
            runQueries: true,
            publishFeatures: false,
            manageEnvironments: false,
            runExperiments: false,
          },
        },
      },
    });
  });

  it("should handle an engineer user with environment specific permissions correctly", async () => {
    const userPermissions = await getUserPermissions(
      "basic_engineer_env_limited_user",
      testOrg
    );

    expect(userPermissions).toEqual({
      global: {
        environments: ["staging", "development"],
        limitAccessByEnvironment: true,
        permissions: {
          createPresentations: true,
          createDimensions: false,
          createSegments: false,
          organizationSettings: false,
          superDelete: false,
          manageTeam: false,
          manageTags: true,
          manageApiKeys: false,
          manageIntegrations: false,
          manageWebhooks: false,
          manageBilling: false,
          manageNorthStarMetric: false,
          manageTargetingAttributes: true,
          manageNamespaces: true,
          manageSavedGroups: true,
          viewEvents: false,
          addComments: true,
          createFeatureDrafts: true,
          manageFeatures: true,
          manageProjects: false,
          createAnalyses: false,
          createIdeas: true,
          createMetrics: false,
          createDatasources: false,
          editDatasourceSettings: false,
          runQueries: false,
          publishFeatures: true,
          manageEnvironments: true,
          runExperiments: true,
        },
      },
      projects: {},
    });
  });

  it("should handle an engineer user with environment specific permissions and project-level roles that have environment specific permissions correctly", async () => {
    const userPermissions = await getUserPermissions(
      "slightly_advanced_engineer_user",
      testOrg
    );

    expect(userPermissions).toEqual({
      global: {
        environments: ["staging", "development"],
        limitAccessByEnvironment: true,
        permissions: {
          createPresentations: true,
          createDimensions: false,
          createSegments: false,
          organizationSettings: false,
          superDelete: false,
          manageTeam: false,
          manageTags: true,
          manageApiKeys: false,
          manageIntegrations: false,
          manageWebhooks: false,
          manageBilling: false,
          manageNorthStarMetric: false,
          manageTargetingAttributes: true,
          manageNamespaces: true,
          manageSavedGroups: true,
          viewEvents: false,
          addComments: true,
          createFeatureDrafts: true,
          manageFeatures: true,
          manageProjects: false,
          createAnalyses: false,
          createIdeas: true,
          createMetrics: false,
          createDatasources: false,
          editDatasourceSettings: false,
          runQueries: false,
          publishFeatures: true,
          manageEnvironments: true,
          runExperiments: true,
        },
      },
      projects: {
        prj_exl5jr5dl4rbw856: {
          environments: ["production"],
          limitAccessByEnvironment: true,
          permissions: {
            createPresentations: true,
            createDimensions: false,
            createSegments: false,
            organizationSettings: false,
            superDelete: false,
            manageTeam: false,
            manageTags: true,
            manageApiKeys: false,
            manageIntegrations: false,
            manageWebhooks: false,
            manageBilling: false,
            manageNorthStarMetric: false,
            manageTargetingAttributes: true,
            manageNamespaces: true,
            manageSavedGroups: true,
            viewEvents: false,
            addComments: true,
            createFeatureDrafts: true,
            manageFeatures: true,
            manageProjects: false,
            createAnalyses: false,
            createIdeas: true,
            createMetrics: false,
            createDatasources: false,
            editDatasourceSettings: false,
            runQueries: false,
            publishFeatures: true,
            manageEnvironments: true,
            runExperiments: true,
          },
        },
        prj_exl5jr5dl4rbw123: {
          environments: [],
          limitAccessByEnvironment: false,
          permissions: {
            createPresentations: true,
            createDimensions: true,
            createSegments: false,
            organizationSettings: false,
            superDelete: false,
            manageTeam: false,
            manageTags: true,
            manageApiKeys: false,
            manageIntegrations: false,
            manageWebhooks: false,
            manageBilling: false,
            manageNorthStarMetric: false,
            manageTargetingAttributes: false,
            manageNamespaces: false,
            manageSavedGroups: false,
            viewEvents: false,
            addComments: true,
            createFeatureDrafts: false,
            manageFeatures: false,
            manageProjects: false,
            createAnalyses: true,
            createIdeas: true,
            createMetrics: true,
            createDatasources: false,
            editDatasourceSettings: true,
            runQueries: true,
            publishFeatures: false,
            manageEnvironments: false,
            runExperiments: false,
          },
        },
      },
    });
  });
  // Advanced user permissions - global role, project-level permissions, and user is on team(s)
  it("should handle a readonly user with environment specific permissions and project-level roles that have environment specific permissions correctly", async () => {
    (findTeamById as jest.Mock).mockResolvedValueOnce({
      id: "team_collaborators",
      role: "collaborator",
      limitAccessByEnvironment: false,
      environments: [],
      projectRoles: [],
    });

    const userPermissions = await getUserPermissions(
      "advanced_readonly_user",
      testOrg
    );

    expect(userPermissions).toEqual({
      global: {
        environments: [],
        limitAccessByEnvironment: false,
        permissions: {
          createPresentations: true,
          createDimensions: false,
          createSegments: false,
          organizationSettings: false,
          superDelete: false,
          manageTeam: false,
          manageTags: false,
          manageApiKeys: false,
          manageIntegrations: false,
          manageWebhooks: false,
          manageBilling: false,
          manageNorthStarMetric: false,
          manageTargetingAttributes: false,
          manageNamespaces: false,
          manageSavedGroups: false,
          viewEvents: false,
          addComments: true,
          createFeatureDrafts: false,
          manageFeatures: false,
          manageProjects: false,
          createAnalyses: false,
          createIdeas: true,
          createMetrics: false,
          createDatasources: false,
          editDatasourceSettings: false,
          runQueries: false,
          publishFeatures: false,
          manageEnvironments: false,
          runExperiments: false,
        },
      },
      projects: {
        prj_exl5jr5dl4rbw856: {
          environments: ["production"],
          limitAccessByEnvironment: true,
          permissions: {
            createPresentations: true,
            createDimensions: false,
            createSegments: false,
            organizationSettings: false,
            superDelete: false,
            manageTeam: false,
            manageTags: true,
            manageApiKeys: false,
            manageIntegrations: false,
            manageWebhooks: false,
            manageBilling: false,
            manageNorthStarMetric: false,
            manageTargetingAttributes: true,
            manageNamespaces: true,
            manageSavedGroups: true,
            viewEvents: false,
            addComments: true,
            createFeatureDrafts: true,
            manageFeatures: true,
            manageProjects: false,
            createAnalyses: false,
            createIdeas: true,
            createMetrics: false,
            createDatasources: false,
            editDatasourceSettings: false,
            runQueries: false,
            publishFeatures: true,
            manageEnvironments: true,
            runExperiments: true,
          },
        },
        prj_exl5jr5dl4rbw123: {
          environments: [],
          limitAccessByEnvironment: false,
          permissions: {
            createPresentations: true,
            createDimensions: true,
            createSegments: false,
            organizationSettings: false,
            superDelete: false,
            manageTeam: false,
            manageTags: true,
            manageApiKeys: false,
            manageIntegrations: false,
            manageWebhooks: false,
            manageBilling: false,
            manageNorthStarMetric: false,
            manageTargetingAttributes: false,
            manageNamespaces: false,
            manageSavedGroups: false,
            viewEvents: false,
            addComments: true,
            createFeatureDrafts: false,
            manageFeatures: false,
            manageProjects: false,
            createAnalyses: true,
            createIdeas: true,
            createMetrics: true,
            createDatasources: false,
            editDatasourceSettings: true,
            runQueries: true,
            publishFeatures: false,
            manageEnvironments: false,
            runExperiments: false,
          },
        },
      },
    });
  });
});
