export const sdkLanguages = [
  "nocode-webflow",
  "nocode-wordpress",
  "nocode-shopify",
  "nocode-other",
  "javascript",
  "nodejs",
  "react",
  "php",
  "ruby",
  "python",
  "go",
  "java",
  "csharp",
  "android",
  "ios",
  "flutter",
  "elixir",
  "edge-cloudflare",
  "edge-fastly",
  "edge-lambda",
  "edge-other",
  "other",
] as const;
