FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-12

# The front-end app (NextJS)
EXPOSE 3000
# The back-end api (Express)
EXPOSE 3100
# Start both front-end and back-end at once
CMD ["yarn","start"]
