/**
 * Registry of GrowthBook docs links used by `DocLink` and the command palette.
 *
 * This module is deliberately dependency-free and written in erasable-syntax-only
 * TypeScript (no enums, namespaces, parameter properties, or JSX) so that
 * `scripts/check-doclink-registry.mjs` can `import()` it directly under Node's
 * native type stripping, with no build step.
 */

//for testing use "http://localhost:3200"
export const docsOrigin = "https://docs.growthbook.io";

/**
 * REST API reference, one entry per resource: the first page of that
 * resource's group in the docs.json API navigation. Cmd+K lists these through
 * `apiReferencePalette.ts`, so they are left out of the generic docs rows.
 */
export const apiReferenceSections = {
  apiProjects: "/api/projects/operation/listProjects",
  apiEnvironments: "/api/environments/operation/listEnvironments",
  apiFeatures: "/api/features-v2/operation/listFeaturesV2",
  apiDataSources: "/api/data-sources/operation/listDataSources",
  apiFactTables: "/api/fact-tables/operation/listFactTables",
  apiFactMetrics: "/api/fact-metrics/operation/listFactMetrics",
  apiMetrics: "/api/metrics/operation/listMetrics",
  apiExperiments: "/api/experiments/operation/listExperiments",
  apiSnapshots: "/api/snapshots/operation/getExperimentSnapshot",
  apiDimensions: "/api/dimensions/operation/listDimensions",
  apiSegments: "/api/segments/operation/listSegments",
  apiSdkConnections: "/api/sdk-connections/operation/listSdkConnections",
  apiVisualChangesets: "/api/visual-changesets/operation/listVisualChangesets",
  apiSavedGroups: "/api/saved-groups/operation/listSavedGroups",
  apiOrganizations: "/api/organizations/operation/listOrganizations",
  apiMembers: "/api/members/operation/listMembers",
  apiCodeReferences: "/api/code-references/operation/listCodeRefs",
  apiArchetypes: "/api/archetypes/operation/listArchetypes",
  apiQueries: "/api/queries/operation/getQuery",
  apiSettings: "/api/settings/operation/getSettings",
  apiAttributes: "/api/attributes/operation/listAttributes",
  apiUsage: "/api/usage/operation/getMetricUsage",
  apiCustomFields: "/api/CustomFields/operation/listCustomFields",
  apiDashboards: "/api/Dashboards/operation/getDashboard",
  apiExperimentTemplates:
    "/api/ExperimentTemplates/operation/getExperimentTemplate",
  apiMetricGroups: "/api/MetricGroups/operation/getMetricGroup",
  apiTeams: "/api/Teams/operation/getTeam",
};

export type ApiReferenceSection = keyof typeof apiReferenceSections;

export const docSections = {
  //Pages
  home: "",
  features: "/app/features",
  experimentConfiguration: "/app/experiment-configuration",
  experimentResults: "/app/experiment-results",
  preExposureBiasCheck: "/app/experiment-results#pre-exposure-bias-check",
  healthTabDimensions:
    "/app/experiment-results#adding-dimensions-to-health-tab",
  troubleshootingExperiments: "/kb/experiments/troubleshooting-experiments",
  experimentDecisionFramework: "/app/experiment-decisions",
  experimentsOverview: "/experiments",
  featureFlagExperiments: "/features/feature-flag-experiments",
  experimentTimeSeries: "/app/experiment-time-series",
  experimentTemplates: "/running-experiments/experiment-templates",
  makingExperimentChanges: "/app/making-experiment-changes",
  experimentDashboards: "/app/experiment-dashboards",
  importingExperiments: "/app/importing-experiments",
  clusterExperiments: "/experimentation-analysis/cluster-experiments",
  preLaunchChecklist: "/app/pre-launch-checklist",
  banditsConfig: "/bandits/config",
  banditsResults: "/bandits/results",
  stickyBucketing: "/app/sticky-bucketing",
  metrics: "/app/metrics",
  factTables: "/app/metrics",
  preAggregatedTables: "/app/metrics/examples#pre-aggregated-tables",
  dimensions: "/app/dimensions",
  datasources: "/app/datasources",
  insights: "/insights",
  learnings: "/insights#learnings",
  metricEffects: "/insights#metric-effects",
  metricCorrelations: "/insights#metric-correlations",
  powerCalculator: "/statistics/power",
  api: "/app/api",
  eventWebhooks: "/app/webhooks/event-webhooks",
  sdkWebhooks: "/app/webhooks/sdk-webhooks",
  productAnalytics: "/app/product-analytics",
  "sdkWebhooks#payload-format": "/app/webhooks/sdk-webhooks#payload-format",
  webhookSecrets: "/app/webhooks#webhook-secrets",
  bandits: "/bandits/overview",
  contextualBandits: "/bandits/contextual",
  targeting: "/features/targeting",
  namespaces: "/features/feature-flag-experiments#namespaces",
  environments: "/features/environments",
  archetypes: "/features/rules#archetypes",
  testingRules: "/features/rules#testing-rules",
  team: "/account/user-permissions#teams",
  projectScopedTeams: "/account/user-permissions#project-scoped-teams",
  codeReferences: "/features/code-references",
  featureBasics: "/features/basics",
  configs: "/features/configs",
  constants: "/features/constants",
  featureRules: "/features/rules",
  safeRollouts: "/features/safe-rollouts",
  publishingAndApprovalFlows: "/features/publishing-and-approval-flows",
  staleDetection: "/features/stale-detection",
  featureDiagnostics: "/features/diagnostics",
  customHooks: "/features/custom-hooks",
  "customHooks#validatefeature": "/features/custom-hooks#validatefeature",
  "customHooks#validatefeaturerevision":
    "/features/custom-hooks#validatefeaturerevision",
  "customHooks#validateconfig": "/features/custom-hooks#validateconfig",
  "customHooks#validateconfigrevision":
    "/features/custom-hooks#validateconfigrevision",
  "customHooks#validateexperiment": "/features/custom-hooks#validateexperiment",
  customRoles: "/account/user-permissions#custom-roles",
  //DataSourceType
  warehouses: "/warehouses",
  athena: "/warehouses/athena",
  mixpanel: "/guide/mixpanel",
  bigquery: "/guide/bigquery",
  presto: "/warehouses/prestodb-or-trino",
  snowflake: "/warehouses/snowflake",
  vertica: "/warehouses/vertica",
  adobe_experience_platform_query_service:
    "/warehouses/adobe-experience-platform-query-service",
  databricks: "/warehouses/databricks",
  clickhouse: "/warehouses/clickhouse",
  postgres: "/warehouses/postgres",
  mysql: "/warehouses/mysql-or-mariadb",
  mssql: "/warehouses/ms-sql-or-sql-server",
  redshift: "/warehouses/redshift",
  google_analytics: "/guide/GA4-google-analytics",
  growthbook_clickhouse: "/app/managed-warehouse",
  //Language
  buildYourOwn: "/lib/build-your-own",
  sdks: "/lib",
  javascript: "/lib/js",
  javascriptAutoAttributes: "/lib/js#auto-attributes",
  tsx: "/lib/react",
  nextjs: "/lib/nextjs",
  go: "/lib/go",
  kotlin: "/lib/kotlin",
  swift: "/lib/swift",
  ruby: "/lib/ruby",
  php: "/lib/php",
  python: "/lib/python",
  java: "/lib/java",
  csharp: "/lib/csharp",
  elixir: "/lib/elixir",
  flutter: "/lib/flutter",
  rust: "/lib/rust",
  nocode: "/lib/script-tag",
  cloudflare: "/lib/edge/cloudflare",
  fastly: "/lib/edge/fastly",
  lambda: "/lib/edge/lambda",
  edge: "/lib/edge/other",
  roku: "/lib/roku",
  //Other
  user_guide: "/",
  config: "/self-host/config",
  config_yml: "/self-host/config",
  config_domains_and_ports: "/self-host/env#domains-and-ports",
  config_organization_settings: "/self-host/config#organization-settings",
  env_prod: "/self-host/env#production-settings",
  visual_editor: "/app/visual",
  url_redirects: "/app/url-redirects",
  temporaryRollout: "/app/visual/legacy#stopping-an-experiment",
  encryptedSDKEndpoints: "/lib/js#loading-features-and-experiments",
  hashSecureAttributes: "/lib/js#secure-attributes",
  autoMetrics: "/app/metrics/legacy#auto-generate-metrics",
  targetingChanges:
    "/app/experiment-configuration#making-changes-while-running",
  shopify: "/integrations/shopify",
  webflow: "/integrations/webflow",
  wordpress: "/integrations/wordpress",
  vercel: "/integrations/vercel",
  slack: "/integrations/slack",
  aiIntegrations: "/integrations/ai",
  agentSkills: "/integrations/ai-agents/agent-skills",
  prerequisites: "/features/prerequisites",
  statisticsOverview: "/statistics/overview",
  statisticsDetails: "/statistics/details",
  statisticsQuantile: "/statistics/quantile",
  statisticsCuped: "/statistics/cuped",
  statisticsSequential: "/statistics/sequential",
  statisticsMultipleCorrections: "/statistics/multiple-corrections",
  statisticsAggregation: "/statistics/aggregation",
  statisticsPowerTechnical: "/statistics/power-technical",
  statisticsCupedTechnical: "/statistics/cuped-technical",
  statisticsPostStratification: "/statistics/post-stratification",
  customMarkdown: "/using/growthbook-best-practices#custom-markdown",
  customMetadata: "/using/growthbook-best-practices#custom-fields",
  programsSharing: "/using/programs#sharing",
  savedGroups: "/features/targeting#saved-groups",
  ga4BigQuery: "/guide/GA4-google-analytics",
  gtmSetup: "/guide/google-tag-manager-and-growthbook",
  gtmCustomTracking:
    "/guide/google-tag-manager-and-growthbook#4-tracking-via-datalayer-and-gtm",
  rudderstack: "/guide/rudderstack",
  matomo: "/guide/matomo",
  apiPostEnvironment: "/api/environments/operation/postEnvironment",
  apiIntroduction: "/api/introduction",
  apiPostCodeRefs: "/api/code-references/operation/postCodeRefs",
  idLists: "/features/targeting#id-lists",
  queryOptimization: "/app/query-optimization",
  metricGroups: "/app/metrics#metric-groups",
  managedWarehouseTracking: "/app/managed-warehouse#sending-events",
  managedWarehouseIngestionApi: "/app/managed-warehouse#ingestion-api",
  managedWarehouseLimits: "/app/managed-warehouse#limits",
  eventForwarder: "/app/event-forwarder",
  chooseDataPath: "/app/choose-data-path",
  devTools: "/tools/chrome-extension",
  pipelineMode: "/app/data-pipeline",
  holdouts: "/app/holdouts",
  autoSlices: "/app/metrics#auto-slices",
  customSlices: "/app/metrics#custom-slices",
  metricSlices: "/app/metrics#metric-slices",
  faq: "/faq",
  cloudCdnUsageLimits: "/faq#what-are-the-growthbook-cloud-cdn-usage-limits",
  ...apiReferenceSections,
};

export type DocSection = keyof typeof docSections;
