import { z } from "zod";
import { experimentAnalysisSummary, baseSchema } from "shared/validators";

export const safeRolloutStatusArray = [
  "running",
  "rolled-back",
  "released",
  "stopped",
] as const;
export type SafeRolloutStatus = (typeof safeRolloutStatusArray)[number];

export const MaxDuration = z.object({
  amount: z.number(),
  unit: z.enum(["weeks", "days", "hours", "minutes"]),
});
// NB: These are the fields that the user submit, and the rest of the interface
// is generated by us based on this information + feature & rule definition.
const rampUpSchedule = z.object({
  enabled: z.boolean(),
  step: z.number(),
  steps: z.array(
    z.object({
      percent: z.number(),
      dateRampedUp: z.date().optional(),
    }),
  ),
  nextUpdate: z.date().optional(),
  lastUpdate: z.date().optional(),
  rampUpCompleted: z.boolean(),
});
export type RampUpSchedule = z.infer<typeof rampUpSchedule>;

export const createSafeRolloutValidator = z.object({
  datasourceId: z.string(),
  exposureQueryId: z.string(),
  guardrailMetricIds: z.array(z.string()),
  maxDuration: MaxDuration,
  autoRollback: z.boolean(),
  rampUpSchedule: rampUpSchedule.partial().optional(),
  seed: z.string().optional(),
});
export type CreateSafeRolloutInterface = z.infer<
  typeof createSafeRolloutValidator
>;

const safeRolloutNotification = [
  "srm",
  "multipleExposures",
  "ship",
  "rollback",
] as const;
export type SafeRolloutNotification = (typeof safeRolloutNotification)[number];

const safeRollout = createSafeRolloutValidator.extend({
  // Refs
  featureId: z.string(),
  environment: z.string(),

  // Managed fields
  status: z.enum(safeRolloutStatusArray),
  autoSnapshots: z.boolean().default(true),
  startedAt: z.date().optional(),
  lastSnapshotAttempt: z.date().optional(),
  nextSnapshotAttempt: z.date().optional(),
  analysisSummary: experimentAnalysisSummary.optional(),
  pastNotifications: z.array(z.enum(safeRolloutNotification)).optional(),
  rampUpSchedule: rampUpSchedule,
});
export const safeRolloutValidator = baseSchema
  .extend(safeRollout.shape)
  .strict();
export type SafeRolloutInterface = z.infer<typeof safeRolloutValidator>;
