import fs from "node:fs";
import path from "node:path";
import { format, resolveConfig } from "prettier";
import { z } from "zod";
import {
  notificationEvents,
  notificationEventPayload,
  experimentInfoSignificance,
  legacyExperimentInfoSignificance,
} from "shared/validators";

const basePath = path.resolve(path.dirname(process.argv[1]), "../../../docs");

const TARGET = `${basePath}/snippets/partials/event-webhook/_event-webhook-list.mdx`;

const typeScriptSchema = async <T extends z.ZodTypeAny>(schema: T) => {
  const { printZodAsTs } = await import("@ephys/zod-to-ts");
  const result = printZodAsTs({ schemas: [schema] });
  return result;
};

const events = Object.keys(notificationEvents).reduce(
  (events, resource) => [
    ...events,
    ...Object.keys(notificationEvents[resource])
      .filter((event) => !notificationEvents[resource][event].noDoc)
      .map((event) => ({
        name: `${resource}.${event}`,
        description: notificationEvents[resource][event].description,
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        payload: notificationEventPayload(resource as any, event as any),
      })),
  ],
  [],
);

const eventAnchor = (name: string) => name.replace(/\./g, "-").toLowerCase();

const eventTableEntry = ({ name, description }) =>
  `| **[${name}](#${eventAnchor(name)})** | ${description} |`;

const quote = "```";

const payloadEntry = async (payload: z.ZodType) => `<Accordion title="Payload">

${quote}typescript
${await typeScriptSchema(payload)}
${quote}

</Accordion>
`;

const eventEntry = async ({ name, description, payload }) => {
  const payloads =
    name === "experiment.info.significance"
      ? await Promise.all(
          (
            [
              ["2026-09-11", experimentInfoSignificance],
              ["2024-07-31", legacyExperimentInfoSignificance],
            ] as const
          ).map(async ([version, schema]) => {
            const versionedPayload = payload.extend({
              api_version: z.literal(version),
              data: z.object({ object: schema }),
            });
            return `#### API version ${version}\n\n${await payloadEntry(versionedPayload)}`;
          }),
        )
      : [await payloadEntry(payload)];
  return `### ${name}\n\n${description}\n\n${payloads.join("\n")}`;
};

const content = async () => {
  const eventEntries = await Promise.all(events.map(eventEntry));

  return `{/* This content is autogenerated by \`pnpm gen-event-webhook-for-docs\`. Do not edit directly. */}

| Event name | Description |
|------------|-------------|
${events.map(eventTableEntry).join("\n")}
${eventEntries.join("\n")}
`;
};

(async () => {
  const config = await resolveConfig(TARGET);
  const formatted = await format(await content(), {
    ...config,
    filepath: TARGET,
  });
  fs.mkdirSync(path.dirname(TARGET), { recursive: true });
  fs.writeFileSync(TARGET, formatted);
})();
