import fs from "node:fs";
import path from "node:path";
import { format, resolveConfig } from "prettier";
import { z } from "zod";
import {
  notificationEventMetadata,
  publicNotificationEventNames,
} from "../src/notifications";
import type {
  NotificationEventName,
  NotificationEventResource,
  ResourceEvents,
} from "../types/events/base-types";
import {
  notificationEvents,
  notificationEventPayload,
  notificationEventResources,
} from "../src/validators/events";

const basePath = path.resolve(path.dirname(process.argv[1]), "../../../docs");

const TARGET = `${basePath}/snippets/partials/event-webhook/_event-webhook-list.mdx`;

const typeScriptSchema = async <T extends z.ZodTypeAny>(schema: T) => {
  const { printZodAsTs } = await import("@ephys/zod-to-ts");
  const result = printZodAsTs({ schemas: [schema] });
  return result;
};

function documentedResourceEvents<Resource extends NotificationEventResource>(
  resource: Resource,
) {
  const events = Object.keys(
    notificationEvents[resource],
  ) as ResourceEvents<Resource>[];
  return events.map((event) => {
    const name = `${resource}.${event}` as NotificationEventName;
    return {
      name,
      description: notificationEventMetadata[name].description,
      payload: notificationEventPayload(resource, event),
    };
  });
}

const events = notificationEventResources
  .flatMap(documentedResourceEvents)
  .filter(({ name }) => publicNotificationEventNames.includes(name));
type DocumentedEvent = (typeof events)[number];

const eventAnchor = (name: string) => name.replace(/\./g, "-").toLowerCase();

const eventTableEntry = ({ name, description }: DocumentedEvent) =>
  `| **[${name}](#${eventAnchor(name)})** | ${description} |`;

const quote = "```";

const eventEntry = async ({ name, description, payload }: DocumentedEvent) => `
### ${name}

${description}

<Accordion title="Payload">

${quote}typescript
${await typeScriptSchema(payload)}
${quote}

</Accordion>
`;

const content = async () => {
  const eventEntries = await Promise.all(events.map(eventEntry));

  return `{/* This content is autogenerated by \`pnpm gen-event-webhook-for-docs\`. Do not edit directly. */}

| Event name | Description |
|------------|-------------|
${events.map(eventTableEntry).join("\n")}
${eventEntries.join("\n")}
`;
};

(async () => {
  const config = await resolveConfig(TARGET);
  const formatted = await format(await content(), {
    ...config,
    filepath: TARGET,
  });
  fs.mkdirSync(path.dirname(TARGET), { recursive: true });
  fs.writeFileSync(TARGET, formatted);
})();
