import fs from "node:fs";
import path from "node:path";
import { format, resolveConfig } from "prettier";
import { z } from "zod";
import {
  notificationEvents,
  notificationEventPayload,
} from "shared/validators";

const basePath = path.resolve(path.dirname(process.argv[1]), "../../../docs");

const TARGET = `${basePath}/snippets/partials/event-webhook/_event-webhook-list.mdx`;

const typeScriptSchema = async <T extends z.ZodTypeAny>(schema: T) => {
  const { printZodAsTs } = await import("@ephys/zod-to-ts");
  const result = printZodAsTs({ schemas: [schema] });
  return result;
};

const events = Object.keys(notificationEvents).reduce(
  (events, resource) => [
    ...events,
    ...Object.keys(notificationEvents[resource])
      .filter((event) => !notificationEvents[resource][event].noDoc)
      .map((event) => ({
        name: `${resource}.${event}`,
        description: notificationEvents[resource][event].description,
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        payload: notificationEventPayload(resource as any, event as any),
      })),
  ],
  [],
);

const eventTableEntry = ({ name, description }) =>
  `| **[${name}](#${name.replace(/\./g, "-")})** | ${description} |`;

const quote = "```";

const eventEntry = async ({ name, description, payload }) => `
### ${name}

${description}

<Accordion title="Payload">

${quote}typescript
${await typeScriptSchema(payload)}
${quote}

</Accordion>
`;

const content = async () => {
  const eventEntries = await Promise.all(events.map(eventEntry));

  return `{/* This content is autogenerated by \`pnpm gen-event-webhook-for-docs\`. Do not edit directly. */}

| Event name | Description |
|------------|-------------|
${events.map(eventTableEntry).join("\n")}
${eventEntries.join("\n")}
`;
};

(async () => {
  const config = await resolveConfig(TARGET);
  const formatted = await format(await content(), {
    ...config,
    filepath: TARGET,
  });
  fs.mkdirSync(path.dirname(TARGET), { recursive: true });
  fs.writeFileSync(TARGET, formatted);
})();
