import {
  ExperimentMetricInterface,
  isFactMetric,
  isLegacyMetric,
  isPercentileCappedMetric,
  isRatioMetric,
  isRegressionAdjusted,
  quantileMetricType,
  eligibleForUncappedMetric,
} from "shared/experiments";
import { FactMetricInterface } from "shared/types/fact-table";
import { MetricInterface } from "shared/types/metric";
import { ExperimentSnapshotSettings } from "shared/types/experiment-snapshot";
import { OrganizationInterface } from "shared/types/organization";
import { IncrementalRefreshMetricRole } from "shared/validators";
import cloneDeep from "lodash/cloneDeep";
import { SourceIntegrationInterface } from "back-end/src/types/Integration";
import { orgHasPremiumFeature } from "back-end/src/enterprise";
import { applyMetricOverrides } from "back-end/src/util/integration";
import {
  BANDIT_CUPED_FLOAT_COLS,
  BASE_METRIC_CUPED_FLOAT_COLS,
  BASE_METRIC_CUPED_FLOAT_COLS_UNCAPPED,
  BASE_METRIC_FLOAT_COLS,
  BASE_METRIC_FLOAT_COLS_UNCAPPED,
  BASE_METRIC_PERCENTILE_CAPPING_FLOAT_COLS,
  MAX_METRICS_PER_QUERY,
  N_STAR_VALUES,
  RATIO_METRIC_CUPED_FLOAT_COLS,
  RATIO_METRIC_CUPED_FLOAT_COLS_UNCAPPED,
  RATIO_METRIC_FLOAT_COLS,
  RATIO_METRIC_PERCENTILE_CAPPING_FLOAT_COLS,
  RATIO_METRIC_FLOAT_COLS_UNCAPPED,
} from "./constants";

// Gets all columns besides the speciality quantile columns for all metrics.
//
// `role` is used by the incremental-refresh path where a cross-fact-table
// ratio metric only contributes one side of its aggregates to a given source's
// cache table (and to the same-FT stats query that reads it). The cross-side
// stats columns (e.g. denominator_sum, main_denominator_sum_product) are
// generated by a separate cross-FT stats query and should not be counted here.
//   - "complete" (default): legacy behavior — count every column.
//   - "numerator": treat the metric as if it were non-ratio (skip ratio
//     denominator + cross-product columns and ratio CUPED columns).
//   - "denominator": only count denominator-side columns (skip main, main
//     CUPED, percentile capping of main).
export function getNonQuantileFloatColumns({
  metric,
  regressionAdjusted,
  isBandit,
  role = "complete",
}: {
  metric: FactMetricInterface;
  regressionAdjusted: boolean;
  isBandit: boolean;
  role?: IncrementalRefreshMetricRole;
}): string[] {
  const includeMainSide = role === "complete" || role === "numerator";
  const includeDenominatorSide = role === "complete" || role === "denominator";

  const isRatio = isRatioMetric(metric);
  // When role is "numerator", treat ratio columns as absent. When role is
  // "denominator", treat the metric as a denominator-only contributor with no
  // main side.
  const includeRatioCols = isRatio && includeDenominatorSide;

  const baseCols = (() => {
    switch (metric.metricType) {
      case "mean":
      case "proportion":
      case "dailyParticipation":
      case "retention":
        return includeMainSide ? BASE_METRIC_FLOAT_COLS : [];
      case "ratio":
        return [
          ...(includeMainSide ? BASE_METRIC_FLOAT_COLS : []),
          ...(includeRatioCols ? RATIO_METRIC_FLOAT_COLS : []),
        ];
      case "quantile":
        return [
          ...(includeMainSide ? BASE_METRIC_FLOAT_COLS : []),
          ...(includeRatioCols ? RATIO_METRIC_FLOAT_COLS : []),
        ];
    }
  })();

  const cupedCols = (() => {
    if (!regressionAdjusted) {
      return [];
    }
    switch (metric.metricType) {
      case "mean":
      case "proportion":
      case "dailyParticipation":
      case "retention":
        return includeMainSide ? BASE_METRIC_CUPED_FLOAT_COLS : [];
      case "ratio":
        return [
          ...(includeMainSide ? BASE_METRIC_CUPED_FLOAT_COLS : []),
          ...(includeRatioCols ? RATIO_METRIC_CUPED_FLOAT_COLS : []),
        ];
      case "quantile":
        return [
          ...(includeMainSide ? BASE_METRIC_CUPED_FLOAT_COLS : []),
          ...(includeRatioCols ? RATIO_METRIC_CUPED_FLOAT_COLS : []),
        ];
    }
  })();

  const percentileCappingCols = (() => {
    if (!isPercentileCappedMetric(metric)) {
      return [];
    }
    switch (metric.metricType) {
      case "mean":
      case "proportion":
      case "dailyParticipation":
      case "retention":
        return includeMainSide ? BASE_METRIC_PERCENTILE_CAPPING_FLOAT_COLS : [];
      case "ratio":
        return [
          ...(includeMainSide ? BASE_METRIC_PERCENTILE_CAPPING_FLOAT_COLS : []),
          ...(includeRatioCols ? RATIO_METRIC_PERCENTILE_CAPPING_FLOAT_COLS : []),
        ];
      case "quantile":
        return [];
    }
  })();

  const uncappedCols = (() => {
    if (!eligibleForUncappedMetric(metric)) {
      return [];
    }
    switch (metric.metricType) {
      case "proportion":
      case "retention":
      case "quantile":
        return [];
      case "mean":
      case "dailyParticipation":
        return includeMainSide
          ? [
              ...BASE_METRIC_FLOAT_COLS_UNCAPPED,
              ...(regressionAdjusted
                ? BASE_METRIC_CUPED_FLOAT_COLS_UNCAPPED
                : []),
            ]
          : [];
      case "ratio":
        return [
          ...(includeMainSide ? BASE_METRIC_FLOAT_COLS_UNCAPPED : []),
          ...(includeRatioCols ? RATIO_METRIC_FLOAT_COLS_UNCAPPED : []),
          ...(regressionAdjusted && includeMainSide
            ? BASE_METRIC_CUPED_FLOAT_COLS_UNCAPPED
            : []),
          ...(regressionAdjusted && includeRatioCols
            ? RATIO_METRIC_CUPED_FLOAT_COLS_UNCAPPED
            : []),
        ];
    }
  })();

  const cols = [
    ...baseCols,
    ...cupedCols,
    ...percentileCappingCols,
    ...uncappedCols,
  ];

  // Bandit CUPED is a single column on the main side; only include when the
  // main side is in this source.
  if (isBandit && includeMainSide) {
    cols.push(...BANDIT_CUPED_FLOAT_COLS);
  }

  return cols;
}

export function maxColumnsNeededForMetric({
  metric,
  regressionAdjusted,
  isBandit,
  role = "complete",
}: {
  metric: FactMetricInterface;
  regressionAdjusted: boolean;
  isBandit: boolean;
  role?: IncrementalRefreshMetricRole;
}) {
  // id column
  const boilerplateCols = 1;

  const floatCols = getNonQuantileFloatColumns({
    metric,
    regressionAdjusted,
    isBandit,
    role,
  });
  switch (metric.metricType) {
    case "mean":
    case "proportion":
    case "dailyParticipation":
    case "retention":
    case "ratio":
      return boilerplateCols + floatCols.length;
    case "quantile":
      return (
        boilerplateCols +
        floatCols.length +
        // quantile_n and quantile
        2 +
        // quantile_lower and quantile_upper per n_star
        N_STAR_VALUES.length * 2
      );
  }
}

export function chunkMetrics({
  metrics,
  maxColumnsPerQuery,
  isBandit,
}: {
  metrics: {
    metric: FactMetricInterface;
    regressionAdjusted: boolean;
  }[];
  maxColumnsPerQuery: number;
  isBandit: boolean;
}): FactMetricInterface[][] {
  // up to 100 dimensions (overkill, but also adds in buffer)
  // + 1 for variation + 2 for users and count
  const baseColumnsNeeded = 103;

  const chunks: FactMetricInterface[][] = [];

  let runningCols = baseColumnsNeeded;
  let runningChunk: FactMetricInterface[] = [];
  metrics.forEach(({ metric: m, regressionAdjusted }) => {
    const colsNeeded = maxColumnsNeededForMetric({
      metric: m,
      regressionAdjusted,
      isBandit,
    });
    const updatedCols = runningCols + colsNeeded;
    if (
      updatedCols > maxColumnsPerQuery ||
      runningChunk.length >= MAX_METRICS_PER_QUERY
    ) {
      chunks.push([...runningChunk]);
      runningChunk = [m];
      runningCols = baseColumnsNeeded + colsNeeded;
    } else {
      runningChunk.push(m);
      runningCols = runningCols + colsNeeded;
    }
  });
  // Add whatever metrics are left in the last chunk
  if (runningChunk.length > 0) {
    chunks.push(runningChunk);
  }

  return chunks;
}

export type MetricWithRole = {
  metric: FactMetricInterface;
  regressionAdjusted: boolean;
  role: IncrementalRefreshMetricRole;
};

// Variant of chunkMetrics for the incremental-refresh path. Each entry carries
// a role indicating which side(s) of the metric are materialized in this
// source's cache table; the column budget consumed by each metric is sized
// only to the columns that side owns. See getNonQuantileFloatColumns for the
// role-aware accounting.
export function chunkMetricsByRole({
  metrics,
  maxColumnsPerQuery,
  isBandit,
}: {
  metrics: MetricWithRole[];
  maxColumnsPerQuery: number;
  isBandit: boolean;
}): MetricWithRole[][] {
  // up to 100 dimensions (overkill, but also adds in buffer)
  // + 1 for variation + 2 for users and count
  const baseColumnsNeeded = 103;

  const chunks: MetricWithRole[][] = [];

  let runningCols = baseColumnsNeeded;
  let runningChunk: MetricWithRole[] = [];
  metrics.forEach((entry) => {
    const colsNeeded = maxColumnsNeededForMetric({
      metric: entry.metric,
      regressionAdjusted: entry.regressionAdjusted,
      isBandit,
      role: entry.role,
    });
    const updatedCols = runningCols + colsNeeded;
    if (
      updatedCols > maxColumnsPerQuery ||
      runningChunk.length >= MAX_METRICS_PER_QUERY
    ) {
      chunks.push([...runningChunk]);
      runningChunk = [entry];
      runningCols = baseColumnsNeeded + colsNeeded;
    } else {
      runningChunk.push(entry);
      runningCols = runningCols + colsNeeded;
    }
  });
  if (runningChunk.length > 0) {
    chunks.push(runningChunk);
  }

  return chunks;
}

export function getFactMetricGroup(metric: FactMetricInterface) {
  // Ratio metrics must have the same numerator and denominator fact table to be grouped
  if (isRatioMetric(metric)) {
    if (metric.numerator.factTableId !== metric.denominator?.factTableId) {
      // TODO: smarter logic to make fewer groupings work
      const tableIds = [
        metric.numerator.factTableId,
        metric.denominator?.factTableId,
      ].sort((a, b) => a?.localeCompare(b ?? "") ?? 0);
      return tableIds.length >= 2
        ? `${tableIds[0]} ${tableIds[1]} (cross-table ratio metrics)`
        : metric.id;
    }
  }

  // Quantile metrics get their own group to prevent slowing down the main query
  // and because they do not support re-aggregation across pre-computed dimensions
  if (quantileMetricType(metric)) {
    return metric.numerator.factTableId
      ? `${metric.numerator.factTableId}_qtile`
      : "";
  }
  return metric.numerator.factTableId || "";
}

export interface GroupedMetrics {
  // Fact metrics grouped together or alone
  factMetricGroups: FactMetricInterface[][];
  // Legacy metrics always as singletons
  legacyMetricSingles: MetricInterface[];
}

export function getFactMetricGroups(
  metrics: ExperimentMetricInterface[],
  settings: ExperimentSnapshotSettings,
  integration: SourceIntegrationInterface,
  organization: OrganizationInterface,
): GroupedMetrics {
  const legacyMetrics: MetricInterface[] = metrics.filter((m) =>
    isLegacyMetric(m),
  );
  const factMetrics: FactMetricInterface[] = metrics.filter(isFactMetric);

  const defaultReturn: GroupedMetrics = {
    // by default, put all fact metrics in their own group
    factMetricGroups: factMetrics.map((m) => [m]),
    legacyMetricSingles: legacyMetrics,
  };

  // Combining metrics in a single query is an Enterprise-only feature
  if (!orgHasPremiumFeature(organization, "multi-metric-queries")) {
    return defaultReturn;
  }

  // Metrics might have different conversion windows which makes the query complicated
  // TODO(sql): join together metrics with the same date windows for some added efficiency
  if (settings.skipPartialData) {
    return defaultReturn;
  }

  // Org-level setting (in case the multi-metric query introduces bugs)
  // TODO(sql): deprecate this setting and hide it for orgs that have not set it
  if (organization.settings?.disableMultiMetricQueries) {
    return defaultReturn;
  }

  // Group fact metrics into efficient groups (primarily if they share a fact table)
  const groups: Record<string, FactMetricInterface[]> = {};
  factMetrics.forEach((m) => {
    // Skip grouping metrics with percentile caps if they cannot be grouped at all
    if (
      m.cappingSettings.type === "percentile" &&
      !integration.getSourceProperties().canGroupPercentileCappedMetrics
    ) {
      return;
    }

    // Skip grouping quantile metrics if there's not an efficient implementation
    if (
      quantileMetricType(m) &&
      !integration.getSourceProperties().hasEfficientPercentiles
    ) {
      return;
    }

    const group = getFactMetricGroup(m);
    if (group) {
      groups[group] = groups[group] || [];
      groups[group].push(m);
    }
  });

  const groupArrays: FactMetricInterface[][] = [];
  Object.values(groups).forEach((group) => {
    // Split groups into chunks of MAX_METRICS_PER_QUERY
    const chunks = chunkMetrics({
      metrics: group.map((m) => {
        const metric = cloneDeep(m);
        // TODO(overrides): refactor overrides to beginning of analysis
        applyMetricOverrides(metric, settings);
        return {
          metric,
          regressionAdjusted:
            isRegressionAdjusted(metric) &&
            settings.regressionAdjustmentEnabled,
        };
      }),
      maxColumnsPerQuery: integration.getSourceProperties().maxColumns,
      isBandit: !!settings.banditSettings,
    });
    groupArrays.push(...chunks);
  });

  // Add unused fact metrics as singles to the group array
  const groupedMetricIds = new Set(
    groupArrays.flatMap((group) => group.map((g) => g.id)),
  );
  factMetrics.forEach((m) => {
    if (!groupedMetricIds.has(m.id)) {
      groupArrays.push([m]);
    }
  });

  return {
    factMetricGroups: groupArrays,
    legacyMetricSingles: legacyMetrics,
  };
}
