type: object
required:
  - id
  - organization
  - dateCreated
  - dateUpdated
  - datasource
  - status
  - dateStart
  - dateEnd
properties:
  id:
    type: string
  organization:
    type: string
  dateCreated:
    type: string
    format: date-time
  dateUpdated:
    type: string
    format: date-time
  datasource:
    type: string
  status:
    type: string
    enum:
      - running
      - success
      - error
  dateStart:
    type: string
    format: date-time
  dateEnd:
    type: string
    format: date-time
  error:
    type: string
    nullable: true
  result:
    type: object
    required:
      - rows
    properties:
      rows:
        type: array
        items:
          type: object
          required:
            - dimensions
            - values
          properties:
            dimensions:
              type: array
              items:
                type: string
                nullable: true
            values:
              type: array
              items:
                type: object
                required:
                  - metricId
                  - numerator
                  - denominator
                properties:
                  metricId:
                    type: string
                  numerator:
                    type: number
                    nullable: true
                  denominator:
                    type: number
                    nullable: true
