#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

openapi=$(git status --porcelain | grep '^[MADRC]' | grep "back-end/src/api/openapi" || true )

if [ -n "$openapi" ]
  then
    echo "#### OpenAPI spec changed"
fi

modelschanged=$(git status --porcelain | grep '^[MADRC]' | grep "back-end/src/models" || true)

if [ -n "$modelschanged" ]
  then
    echo "#### Backend models changed"
fi

if [ -n "$openapi" ] | [ -n "$modelschanged" ]
  then
    echo "#### Running generate-api-types and adding changes"
    yarn generate-api-types
    git add packages/shared/types/openapi.d.ts
    git add packages/back-end/generated/spec.yaml
    git add packages/shared/src/validators/openapi.ts
fi

echo "#### Linting typescript, scss, and markdown files"
yarn lint-staged

docchanged=$(git status --porcelain | grep '^[MADRC]' | grep "back-end/src/events/\|shared/scripts/gen-event-webhook-doc.ts" || true)

if [ -n "$docchanged" ]
  then
    echo "#### Generating doc files"
    yarn workspace shared gen-event-webhook-for-docs
    git add docs
fi

sdkchanged=$(git status --porcelain | grep '^[MADRC]' | grep -E "shared/src/sdk-versioning|shared/scripts/gen-sdk-resources.ts" || true)
if [ -n "$sdkchanged" ]; then
  echo "#### sdk-versioning or gen-sdk-resources.ts changed, running gen-sdk-resources"
  yarn workspace shared build
  yarn workspace shared gen-sdk-resources-for-docs
  git add docs
fi
