coordinator=true
node-scheduler.include-coordinator=true
http-server.http.enabled=false
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/etc/trino/keystore.jks
http-server.https.keystore.key=changeit

discovery.uri=https://trino.docker.internal:8443
internal-communication.https.required=true

http-server.authentication.type=KERBEROS
http.authentication.krb5.config=/etc/krb5.conf
http-server.authentication.krb5.service-name=trino
http-server.authentication.krb5.principal-hostname=trino.docker.internal
http-server.authentication.krb5.keytab=/keytabs/trino.keytab

internal-communication.shared-secret=growthbook-shared-secret
