com.sun.security.jgss.krb5.initiate {
  com.sun.security.auth.module.Krb5LoginModule required
  doNotPrompt=true
  useKeyTab=true
  storeKey=true
  keyTab="/keytabs/trino.keytab"
  principal="trino/trino.docker.internal@TEST.LOCAL";
};

com.sun.security.jgss.krb5.accept {
  com.sun.security.auth.module.Krb5LoginModule required
  doNotPrompt=true
  useKeyTab=true
  storeKey=true
  keyTab="/keytabs/trino.keytab"
  principal="trino/trino.docker.internal@TEST.LOCAL";
};
