name: Helm Chart
on:
  push:
  workflow_dispatch:
    inputs:
      publish:
        description: "Build and maybe publish Helm Chart to OCI registry"
        required: false
        default: false
        type: boolean

jobs:
  build-chart:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: charts/growthbook
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Rebuild helm dependencies
        run: helm dependency build
      - name: Lint helm chart
        run: helm lint --strict --with-subcharts .
      - name: Package helm chart
        run: helm package .
      - name: Login to OCI registry
        if: ${{ startsWith(github.ref, 'refs/tags/') || inputs.publish }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push helm chart to OCI registry
        if: ${{ startsWith(github.ref, 'refs/tags/') || inputs.publish }}
        run: |
          for chart in *.tgz; do
              helm push "$chart" oci://ghcr.io/growthbook/charts
          done
