name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write
jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          # This token is required only if you have configured to store the signatures in a remote repository/organization
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: "signatures/version1/cla.json"
          path-to-document: "https://github.com/growthbook/growthbook/blob/main/CLA.md"
          branch: "main"
          allowlist: bot*,august-growthbook,Auz,bryce-fitzsimons,gazzding,jdorn,lukebrawleysmith,lukesonnet,madhuchavva,mattdp,mknowlton89,msamper,natasha-growthbook,romain-growthbook,toots,tzjames,Kevin-Chant
          remote-organization-name: growthbook
          remote-repository-name: cla-signatures
