name: Find feature flag code references
on:
  pull_request:
    branches:
      - main
jobs:
  fetchFlags:
    runs-on: ubuntu-latest
    outputs:
      json-path: ${{ steps.set-path.outputs.json-path }}
    steps:
      - name: Fetch Data
        run: |
          curl -H "Authorization: Bearer secret_admin_CRZwgOBCa4wUeN4yWiWaYvn3b70jLKAs1MidMNf3Z1w" "https://growthbook-3100-pr-2066-bttf.growthbook.okteto.dev/api/v1/feature-keys" -o flags.json
      - name: Upload flags.json
        uses: actions/upload-artifact@v3
        with:
          name: flags-json
          path: flags.json
  codeRefs:
    needs: fetchFlags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 11 # This value must be set if the lookback configuration option is defined for find-code-refs. Read more: https://github.com/growthbook/gb-find-code-refs#searching-for-unused-flags-extinctions
      - name: Download JSON file
        uses: actions/download-artifact@v3
        with:
          name: flags-json
          path: ${{ needs.fetchFlags.outputs.json-path }}
      - name: GrowthBook Code References
        uses: growthbook/coderefs-github-action@2.11.5-2
        with:
          flagsPath: ${{ needs.fetchFlags.outputs.json-path }}
          dir: ${{ github.workspace }}
      - name: Upload coderefs.json
        uses: actions/upload-artifact@v3
        with:
          name: coderefs-json
          path: ./*.json
