name: One-time 2.9.0 Retag Release

on:
  push:
    branches:
      - ji/retag2.9

jobs:
  # Tag the latest docker release with the tag
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'growthbook/growthbook' }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install buildx
        uses: docker/setup-buildx-action@v3

      - name: Add tag to latest image
        run: |
          docker buildx imagetools create -t growthbook/growthbook:2.9.0 growthbook/growthbook:latest
